"""Dungeon portals. GENERATED by gen_dungeon_portals.py - do not edit by hand."""

SKILL_ADVENTURING = 795
SPELL_BASE = 44300
SLA_BASE = 8000

DUNGEONS = [
    {'spell': 44300, 'map': 33, 'name': 'Shadowfang Keep', 'req': 10, 'door_map': 0, 'x': -229.49, 'y': 1576.35, 'z': 78.89},
    {'spell': 44301, 'map': 34, 'name': 'Stormwind Stockade', 'req': 15, 'door_map': 0, 'x': -8761.85, 'y': 848.56, 'z': 87.81},
    {'spell': 44302, 'map': 35, 'name': 'Stormwind Vault', 'req': 58, 'door_map': 0, 'x': -8667.56, 'y': 623.56, 'z': 85.41},
    {'spell': 44303, 'map': 36, 'name': 'Deadmines', 'req': 10, 'door_map': 0, 'x': -11208.50, 'y': 1685.34, 'z': 25.76},
    {'spell': 44304, 'map': 43, 'name': 'Wailing Caverns', 'req': 10, 'door_map': 1, 'x': -753.60, 'y': -2212.78, 'z': 21.54},
    {'spell': 44305, 'map': 47, 'name': 'Razorfen Kraul', 'req': 15, 'door_map': 1, 'x': -4456.70, 'y': -1655.99, 'z': 86.11},
    {'spell': 44306, 'map': 48, 'name': 'Blackfathom Deeps', 'req': 10, 'door_map': 1, 'x': 4252.37, 'y': 756.97, 'z': -23.06},
    {'spell': 44307, 'map': 70, 'name': 'Uldaman', 'req': 30, 'door_map': 0, 'x': -6053.73, 'y': -2954.63, 'z': 213.69},
    {'spell': 44308, 'map': 90, 'name': 'Gnomeregan', 'req': 15, 'door_map': 0, 'x': -5161.33, 'y': 939.62, 'z': 258.29},
    {'spell': 44309, 'map': 109, 'name': 'Sunken Temple', 'req': 35, 'door_map': 0, 'x': -10162.70, 'y': -3998.65, 'z': -107.98},
    {'spell': 44310, 'map': 129, 'name': 'Razorfen Downs', 'req': 25, 'door_map': 1, 'x': -4666.52, 'y': -2536.82, 'z': 86.97},
    {'spell': 44311, 'map': 189, 'name': 'Scarlet Monastery', 'req': 20, 'door_map': 0, 'x': 2924.38, 'y': -798.43, 'z': 161.61},
    {'spell': 44312, 'map': 209, 'name': "Zul'Farrak", 'req': 35, 'door_map': 1, 'x': -6773.49, 'y': -2889.77, 'z': 15.11},
    {'spell': 44313, 'map': 229, 'name': 'Blackrock Spire', 'req': 45, 'door_map': 0, 'x': -7518.19, 'y': -1239.13, 'z': 287.24},
    {'spell': 44314, 'map': 230, 'name': 'Blackrock Depths', 'req': 40, 'door_map': 0, 'x': -7176.63, 'y': -937.67, 'z': 170.21},
    {'spell': 44315, 'map': 269, 'name': 'Black Morass', 'req': 58, 'door_map': 1, 'x': -8799.19, 'y': -4115.16, 'z': -200.00},
    {'spell': 44316, 'map': 289, 'name': 'Scholomance', 'req': 45, 'door_map': 0, 'x': 1282.05, 'y': -2548.73, 'z': 85.40},
    {'spell': 44317, 'map': 329, 'name': 'Stratholme', 'req': 45, 'door_map': 0, 'x': 3237.46, 'y': -4060.60, 'z': 112.01},
    {'spell': 44318, 'map': 349, 'name': 'Maraudon', 'req': 30, 'door_map': 1, 'x': -1484.07, 'y': 2617.57, 'z': 75.71},
    {'spell': 44319, 'map': 389, 'name': 'Ragefire Chasm', 'req': 8, 'door_map': 1, 'x': 1818.40, 'y': -4427.26, 'z': -10.45},
    {'spell': 44320, 'map': 429, 'name': 'Dire Maul', 'req': 45, 'door_map': 1, 'x': -3730.48, 'y': 933.97, 'z': 160.97},
    {'spell': 44321, 'map': 800, 'name': 'Karazhan Crypt', 'req': 55, 'door_map': 0, 'x': -11068.30, 'y': -1811.69, 'z': 53.00},
    {'spell': 44322, 'map': 802, 'name': 'Crescent Grove', 'req': 32, 'door_map': 1, 'x': 1689.78, 'y': -1272.15, 'z': 161.68},
    {'spell': 44323, 'map': 808, 'name': 'Hateforge Quarry', 'req': 48, 'door_map': 0, 'x': -8173.00, 'y': -3114.57, 'z': 201.22},
    {'spell': 44324, 'map': 815, 'name': 'Gilneas City', 'req': 40, 'door_map': 0, 'x': -1096.81, 'y': 2234.77, 'z': 182.86},
    {'spell': 44325, 'map': 816, 'name': 'Dragonmaw Retreat', 'req': 25, 'door_map': 0, 'x': -3812.28, 'y': -3595.80, 'z': -45.95},
    {'spell': 44326, 'map': 818, 'name': 'Stormwrought Ruins', 'req': 35, 'door_map': 0, 'x': -8823.10, 'y': 2903.17, 'z': 135.49},
    {'spell': 44327, 'map': 820, 'name': 'Windhorn Canyon', 'req': 26, 'door_map': 1, 'x': -5117.52, 'y': -3534.29, 'z': 3.97},
    {'spell': 44328, 'map': 822, 'name': 'Frostmane Hollow', 'req': 13, 'door_map': 0, 'x': -5020.44, 'y': -1449.43, 'z': 500.08},
]


def grid():
    return DUNGEONS
