"""Export item sell prices from the world database into a Lua table for TerapinTips.

    python gen_price_table.py

WHY THIS EXISTS
  The 1.12 client has NO sell-price API. Checked directly against WoW.exe: neither
  GetSellValue nor GetItemSellPrice exists, and GetItemInfo does not return a price in this
  client build. Addons of that era worked around it by scanning merchant windows and caching
  what they saw, so prices were missing until you had personally seen the item at a vendor.

  The server knows every price, so we ship it instead of discovering it. 19,667 of 26,556
  items have a non-zero sell_price; the rest are genuinely worthless (quest items, etc.) and
  are omitted rather than stored as zeros.

OUTPUT SHAPE
  A flat `TerapinPrices = { [itemID] = copper, ... }` table. Written in numeric id order with
  several pairs per line - purely so the file diffs sanely in git and does not become one
  enormous line.
"""
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ADDON = r"D:\Games\turtlewow\client\Interface\AddOns\TerapinTips"
MYSQL = r"D:\Games\turtlewow\tortoise-oneclick-compiler\DB\bin\mysql.exe"

rows = subprocess.run(
    [MYSQL, "-h127.0.0.1", "-P3307", "-umangos", "-pmangos", "-N", "-e",
     "SELECT entry, sell_price FROM tw_world.item_template "
     "WHERE sell_price > 0 ORDER BY entry;"],
    capture_output=True, text=True).stdout

pairs = []
for line in rows.strip().splitlines():
    p = line.split()
    if len(p) == 2:
        pairs.append((int(p[0]), int(p[1])))

if not pairs:
    raise SystemExit("no rows returned - is the database up on port 3307?")

if not os.path.isdir(ADDON):
    os.makedirs(ADDON)

out = [
    "-- GENERATED by TurtleMod/gen_price_table.py - do not edit by hand.",
    "--",
    "-- Vendor sell prices, in copper, straight from item_template.sell_price.",
    "-- The 1.12 client exposes no sell-price API at all, so the data is shipped rather",
    "-- than discovered by scanning merchants.",
    "--",
    "-- %d items. Items with no sell value are omitted, not stored as zero." % len(pairs),
    "",
    "TerapinPrices = {",
]
line = "  "
for i, (entry, price) in enumerate(pairs):
    chunk = "[%d]=%d," % (entry, price)
    if len(line) + len(chunk) > 110:
        out.append(line)
        line = "  "
    line += chunk
if line.strip():
    out.append(line)
out.append("}")
out.append("")

path = os.path.join(ADDON, "prices.lua")
with open(path, "w") as f:
    f.write("\n".join(out))

print("wrote %s" % path)
print("  %d items, %.0f KB" % (len(pairs), os.path.getsize(path) / 1024.0))
print("  cheapest %d copper, dearest %d copper" % (min(p for _, p in pairs),
                                                   max(p for _, p in pairs)))
