"""Generate sql/06-test-content.sql from testcontent.py.

Regenerate rather than hand-editing the SQL, so the server half cannot drift from the
client half (content.py builds the DBC rows from the same tables).

    python gen_test_sql.py

WHY EVERY SPELL IS A CLONE
  spell_template has 200-odd columns. Copying a row that already behaves correctly and
  overriding the handful that differ is the only sane way to do this by hand. Each block
  below is the same shape: temp table LIKE spell_template, copy one row in, UPDATE the
  differences, INSERT it back.

WHY EACH ABILITY NEEDS A SECOND "TEACHER" SPELL
  npc_trainer.spell must be a LEARN_SPELL (effect 36) wrapper. Pointing a trainer row at
  the ability itself is rejected at load with
      Table `npc_trainer` for trainer (Entry: X) has non-learning spell Y, ignore
  so 27 buffs need 27 teachers, and 11 recipes need 11 more.

ON "RANDOMLY BUFFS ONE STAT"
  Spell data cannot express randomness. SPELL_AURA_MOD_STAT takes ONE misc value (0-4);
  there is no effect in this core that picks a spell or a stat at random. Each spec's buff
  therefore raises one FIXED stat, spread across all five so every misc value is exercised,
  and the tooltip names the stat it actually gives. True per-cast randomness needs a
  script - see TurtleMod/ELUNA.md.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import testcontent as tc   # noqa: E402

OUT = os.path.join(HERE, "sql", "06-test-content.sql")
L = []
w = L.append


def q(s):
    return "'" + s.replace("'", "''") + "'"


def clone_spell(new_id, clone_from, sets, tmp):
    w("DROP TEMPORARY TABLE IF EXISTS %s;" % tmp)
    w("CREATE TEMPORARY TABLE %s LIKE spell_template;" % tmp)
    w("INSERT INTO %s SELECT * FROM spell_template WHERE entry = %d;" % (tmp, clone_from))
    w("UPDATE %s SET entry = %d,\n  %s;" % (tmp, new_id, ",\n  ".join(sets)))
    w("INSERT INTO spell_template SELECT * FROM %s;" % tmp)
    w("DROP TEMPORARY TABLE %s;" % tmp)
    w("")


cs = tc.class_spells()
ps = tc.prof_spells()
all_spell_ids = ([r[0] for r in cs] + [r[1] for r in cs] +
                 [r[0] for r in ps] + [r[1] for r in ps])
all_item_ids = [r[2] for r in ps]

BAR = "-- " + "-" * 85
EQ = "-- " + "=" * 85

w(BAR)
w("-- TurtleMod test content - GENERATED by gen_test_sql.py. Do not edit by hand.")
w("--")
w("--   * one buff spell per class specialization (%d), filed under that spec's" % len(cs))
w("--     spellbook tab and trainable at level %d from the matching class master" % tc.TRAIN_LEVEL)
w("--   * one craft recipe per profession (%d) at skill %d, from basic mats" % (len(ps), tc.CRAFT_SKILL))
w("--")
w("-- Run against tw_world. IDEMPOTENT. Requires a mangosd RESTART and the rebuilt")
w("-- patch-6.mpq, which carries the client-side Spell.dbc and SkillLineAbility.dbc rows.")
w("--")
w("-- All spell ids are in the reserved 38xxx block. See TurtleMod/SPELL-IDS.md - ids")
w("-- above 65535 are silently truncated to 16 bits by SMSG_INITIAL_SPELLS and arrive at")
w("-- the client as a completely different spell.")
w(BAR)
w("")
w("USE tw_world;")
w("")
w("-- Idempotency: clear anything a previous run left behind.")
w("DELETE FROM spell_template     WHERE entry    IN (%s);" % ",".join(map(str, all_spell_ids)))
w("DELETE FROM npc_trainer        WHERE spell    IN (%s);" % ",".join(map(str, all_spell_ids)))
w("DELETE FROM skill_line_ability WHERE spell_id IN (%s);" % ",".join(map(str, all_spell_ids)))
w("DELETE FROM item_template      WHERE entry    IN (%s);" % ",".join(map(str, all_item_ids)))
w("")

sla = []          # (id, skill, spell, classmask, req_skill_value)
trainers = []     # (npc, spell, cost, reqskill, reqskillvalue, reqlevel)
sla_id = tc.SLA_ID_BASE

w(EQ)
w("-- PART 1 - %d class specialization buffs" % len(cs))
w("--")
w("-- Each is filed under a REAL SkillLine.dbc class skill line (Arms, Fury, Frost, ...),")
w("-- which is what puts it on that tab in the spellbook rather than under General.")
w(EQ)
w("")
for ability, teacher, cname, cmask, trainer, skill_id, spec, stat in cs:
    name = tc.spec_spell_name(spec)
    desc = tc.spec_spell_desc(spec, stat)
    w("-- %-8s %-17s %-9s ability %d, teacher %d, skill line %d"
      % (cname, spec, tc.STATS[stat], ability, teacher, skill_id))
    clone_spell(ability, tc.CLONE_CLASS_ABILITY, [
        "name = %s" % q(name),
        "nameSubtext = ''",
        "description = %s" % q(desc),
        "effect1 = 6",                       # SPELL_EFFECT_APPLY_AURA
        "effectApplyAuraName1 = 29",         # SPELL_AURA_MOD_STAT
        "effectMiscValue1 = %d" % stat,      # 0 STR 1 AGI 2 STA 3 INT 4 SPI
        "effectBasePoints1 = 4",             # amount is basePoints + 1 -> +5
        "effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0",
        "effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0",
        "SpellFamilyName = %d" % tc.FAMILY[cname],
        "spellLevel = %d" % tc.TRAIN_LEVEL,
        "baseLevel = %d" % tc.TRAIN_LEVEL,
        "manaCost = 0",
    ], "tmp_ab")
    clone_spell(teacher, tc.CLONE_TEACHER, [
        "name = %s" % q(name),
        "nameSubtext = ''",
        "description = %s" % q("Teaches %s." % name),
        "effect1 = 36",                      # SPELL_EFFECT_LEARN_SPELL
        "effectTriggerSpell1 = %d" % ability,
        "effect2 = 0, effect3 = 0",
        "effectApplyAuraName1 = 0, effectBasePoints1 = 0",
        "SpellFamilyName = %d" % tc.FAMILY[cname],
        "spellLevel = %d" % tc.TRAIN_LEVEL,
        "baseLevel = %d" % tc.TRAIN_LEVEL,
        "DurationIndex = 0", "RecoveryTime = 0", "manaCost = 0",
    ], "tmp_te")
    sla.append((sla_id, skill_id, ability, cmask, 0))
    sla_id += 1
    trainers.append((trainer, teacher, tc.TRAIN_COST, 0, 0, tc.TRAIN_LEVEL))

w(EQ)
w("-- PART 2 - %d profession test recipes at skill %d" % (len(ps), tc.CRAFT_SKILL))
w("--")
w("-- Each craft spell is a clone of that profession's OWN lowest-tier recipe, so it")
w("-- inherits the right RequiresSpellFocus: Cooking needs a fire, Smelting and")
w("-- Jewelcrafting a forge, Enchanting nothing. Cloning across professions would produce")
w("-- a recipe that can never be cast, with no useful error message.")
w(EQ)
w("")
for craft, teacher, item, skill, pname, trainer, clone, reagents in ps:
    iname = tc.prof_item_name(pname)
    w("-- %-15s item %d, craft %d (clone of %d), teacher %d"
      % (pname, item, craft, clone, teacher))
    w("DROP TEMPORARY TABLE IF EXISTS tmp_it;")
    w("CREATE TEMPORARY TABLE tmp_it LIKE item_template;")
    w("INSERT INTO tmp_it SELECT * FROM item_template WHERE entry = %d;" % tc.CLONE_PROF_ITEM)
    w("UPDATE tmp_it SET entry = %d, name = %s, Quality = %d, description = %s;"
      % (item, q(iname), tc.PROF_ITEM_QUALITY,
         q("A test item proving %s recipes can be added." % pname)))
    w("INSERT INTO item_template SELECT * FROM tmp_it;")
    w("DROP TEMPORARY TABLE tmp_it;")
    w("")
    sets = [
        "name = %s" % q(iname),
        "nameSubtext = ''",
        "description = %s" % q("Creates a %s." % iname),
        "effect1 = 24",                      # SPELL_EFFECT_CREATE_ITEM
        "effectItemType1 = %d" % item,
        "effect2 = 0, effect3 = 0",
        "effectTriggerSpell1 = 0",
    ]
    for n in range(1, 5):
        if n <= len(reagents):
            sets.append("reagent%d = %d, reagentCount%d = %d"
                        % (n, reagents[n - 1][0], n, reagents[n - 1][1]))
        else:
            sets.append("reagent%d = 0, reagentCount%d = 0" % (n, n))
    clone_spell(craft, clone, sets, "tmp_cr")
    clone_spell(teacher, tc.CLONE_PROF_TEACHER, [
        "name = %s" % q(iname),
        "nameSubtext = ''",
        "description = %s" % q("Teaches you how to make a %s." % iname),
        "effect1 = 36",
        "effectTriggerSpell1 = %d" % craft,
        "effectImplicitTargetA1 = 0",   # NOT 1 (caster) - the trainer would teach itself
        "effect2 = 0, effect3 = 0",
    ], "tmp_pt")
    sla.append((sla_id, skill, craft, 0, tc.CRAFT_SKILL))
    sla_id += 1
    trainers.append((trainer, teacher, tc.TRAIN_COST, skill, tc.CRAFT_SKILL, 0))

w(EQ)
w("-- PART 3 - file every spell under its skill line")
w("--")
w("-- This is what places a spell on a spellbook tab and a recipe in a crafting window.")
w("-- The SERVER reads this SQL table; the CLIENT reads SkillLineAbility.dbc and never")
w("-- sees the table. Both need the same rows, which is why patch-6.mpq carries the DBC.")
w(EQ)
w("")
w("INSERT INTO skill_line_ability")
w("  (id, skill_id, spell_id, race_mask, class_mask, req_skill_value,")
w("   superseded_by_spell, learn_on_get_skill, max_value, min_value, req_train_points)")
w("VALUES")
w(",\n".join("  (%d, %d, %d, 0, %d, %d, 0, 0, 0, 0, 0)" % r for r in sla) + ";")
w("")
w(EQ)
w("-- PART 4 - put the teachers on the trainers")
w(EQ)
w("")
w("INSERT INTO npc_trainer (entry, spell, spellcost, reqskill, reqskillvalue, reqlevel)")
w("VALUES")
w(",\n".join("  (%d, %d, %d, %d, %d, %d)" % r for r in trainers) + ";")
w("")
w(EQ)
w("-- PART 5 - report. Expected: %d, %d, %d, %d, %d"
  % (len(cs), len(ps), len(ps), len(sla), len(trainers)))
w(EQ)
w("SELECT 'class buffs' AS what, COUNT(*) AS n FROM spell_template WHERE entry BETWEEN %d AND %d;"
  % (tc.CLASS_ABILITY_BASE, tc.CLASS_ABILITY_BASE + len(cs) - 1))
w("SELECT 'prof recipes' AS what, COUNT(*) AS n FROM spell_template WHERE entry BETWEEN %d AND %d;"
  % (tc.PROF_CRAFT_BASE, tc.PROF_CRAFT_BASE + len(ps) - 1))
w("SELECT 'test items' AS what, COUNT(*) AS n FROM item_template WHERE entry IN (%s);"
  % ",".join(map(str, all_item_ids)))
w("SELECT 'skill links' AS what, COUNT(*) AS n FROM skill_line_ability WHERE spell_id IN (%s);"
  % ",".join(map(str, all_spell_ids)))
w("SELECT 'trainer rows' AS what, COUNT(*) AS n FROM npc_trainer WHERE spell IN (%s);"
  % ",".join(map(str, all_spell_ids)))

with open(OUT, "w") as f:
    f.write("\n".join(L) + "\n")

print("wrote %s" % OUT)
print("  %d class buffs + %d teachers" % (len(cs), len(cs)))
print("  %d profession recipes + %d teachers + %d items" % (len(ps), len(ps), len(ps)))
print("  %d skill_line_ability rows, %d npc_trainer rows" % (len(sla), len(trainers)))
