"""Generate mounts.lua - the set of mount buff names, for TerapinTips' auto-dismount.

    python gen_mount_names.py

WHY A NAME TABLE AND NOT AN ICON CHECK
  The obvious detector - "does the buff icon start with Ability_Mount_" - does not work.
  Measured against this client's own Spell.dbc: 484 mount spells share 86 distinct icons,
  and the most common is Spell_Nature_Swiftness (83 spells), which is not a mount icon at
  all. Ability_Hunter_BeastCall covers another 48. Only 41 use Ability_Mount_*.

  There is no spell id on a buff in the 1.12 API either - GetPlayerBuff hands back an
  opaque index - so the name is the only thing left to match on, read out of the tooltip.

SOURCE OF TRUTH
  The CLIENT's Spell.dbc, through the same MPQ chain build.py reads, so the names match
  what the tooltip will actually show - byte for byte, including any Turtle-only mounts.
"""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools"))
import mpyq, dbc, content

SEP = chr(92)
CLIENT_DATA = r"D:\Games\turtlewow\client\Data"
ADDON = r"D:\Games\turtlewow\client\Interface\AddOns\TerapinTips"
SEARCH = ["patch-6.mpq", "patch-5.mpq", "patch-4.mpq", "patch-3.mpq",
          "patch-2.mpq", "patch-1.mpq", "patch.MPQ", "dbc.MPQ"]
SPELL_AURA_MOUNTED = 78
F = content.F

raw = None
for name in SEARCH:
    p = os.path.join(CLIENT_DATA, name)
    if not os.path.exists(p):
        continue
    try:
        raw = mpyq.MPQArchive(p, listfile=False).read_file("DBFilesClient" + SEP + "Spell.dbc")
    except Exception:
        continue
    if raw:
        print("source: %s" % name)
        break
if not raw:
    raise SystemExit("Spell.dbc not found in the client MPQ chain")

t = dbc.Dbc(raw)
names = set()
for r in t.records:
    if SPELL_AURA_MOUNTED in (r[F["aura1"]], r[F["aura2"]], r[F["aura3"]]):
        n = t.get_string(r[F["name"]])
        if n:
            names.add(n)

if len(names) < 300:
    raise SystemExit("only %d mount names found - that is too few, refusing to ship it" % len(names))

out = os.path.join(ADDON, "mounts.lua")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("-- GENERATED by TurtleMod/gen_mount_names.py - do not edit by hand.\n")
    f.write("-- Every SPELL_AURA_MOUNTED name in the client's own Spell.dbc, as a set.\n")
    f.write("-- Used by dismount.lua to tell a mount buff from any other buff; see that\n")
    f.write("-- file and the generator for why an icon check does not work.\n--\n")
    f.write("-- %d names.\n\nTERAPIN_MOUNTS = {\n" % len(names))
    for n in sorted(names):
        f.write('  ["%s"] = true,\n' % n.replace("\\", "\\\\").replace('"', '\\"'))
    f.write("}\n")
print("wrote %s  (%d names, %d bytes)" % (out, len(names), os.path.getsize(out)))
