"""Emits sql/36-inn-teleports.sql from inns.py.

One teleport spell per inn, filed under the Adventuring skill line so they collect in their
own spellbook tab instead of drowning General.

WHY THE CLONE SOURCE IS A MAGE TELEPORT AND NOT THE HEARTHSTONE
  Spell 3561 "Teleport: Stormwind" is already exactly the behaviour we want:

      effect1                5   SPELL_EFFECT_TELEPORT_UNITS
      effectImplicitTargetA1 1   self - the DESTINATION comes from spell_target_position
      castingTimeIndex       7   ten seconds
      InterruptFlags        15   pushed off it by damage and movement
      RecoveryTime           0   no cooldown

  The Hearthstone (8690) looks like the obvious source but is the wrong one: it is bound to
  an item, and its destination is the player's home bind rather than a row we control.

  A destination is a row in spell_target_position keyed by spell id, which is why every one
  of these can share a single cloned template and still land somewhere different.

NO COOLDOWN IS DELIBERATE
  A ten second cast that breaks on damage is already the whole limit. It is useless as an
  escape and useless in a fight, which is where a hearthstone cooldown earns its keep. What
  is left is walking somewhere you have already been, and charging a cooldown for that is
  just making the player wait for no reason.
"""

import os

import inns

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "sql", "36-inn-teleports.sql")
SERVER_LUA = r"D:\Games\turtlewow\TortoiseNew\TortoiseCompiledNew\server\lua_scripts"

CLONE_SPELL = 3561          # Teleport: Stormwind
HEARTH_ICON = 2179          # INV_Misc_Rune_01, the hearthstone icon


def main():
    rows = inns.grid()
    ids = ",".join(str(r["spell"]) for r in rows)
    L = []
    w = L.append

    w("-- " + "-" * 85)
    w("-- Inn teleports: one spell per inn, filed under the Adventuring skill (%d)."
      % inns.SKILL_ADVENTURING)
    w("--")
    w("-- GENERATED by gen_inns.py from inns.py - do not edit by hand.")
    w("-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART and a rebuilt patch-6.mpq.")
    w("-- " + "-" * 85)
    w("--")
    w("-- Each spell is cloned from %d (Teleport: Stormwind), which already casts for ten"
      % CLONE_SPELL)
    w("-- seconds, breaks on damage and has no cooldown. The destination is NOT in the spell -")
    w("-- it is a row in spell_target_position keyed by spell id, which is how %d spells share"
      % len(rows))
    w("-- one template and still land in %d different places." % len(rows))
    w("--")
    w("-- You are not taught these. Walk into an inn and lua_scripts/inn_discovery.lua gives you")
    w("-- that one, so the tab fills in as you see the world rather than arriving complete.")
    w("-- " + "-" * 85)
    w("")
    w("USE tw_world;")
    w("")
    w("-- Clean slate, so a re-run cannot leave a half-updated list behind.")
    w("DELETE FROM spell_template         WHERE entry    IN (%s);" % ids)
    w("DELETE FROM spell_target_position  WHERE id       IN (%s);" % ids)
    w("DELETE FROM skill_line_ability     WHERE spell_id IN (%s);" % ids)
    w("")

    for i, r in enumerate(rows):
        where = ", ".join(x for x in (r["town"], r["zone"]) if x and x != r["inn"])
        if r["lo"]:
            desc = ("Teleport to %s in %s. The land around it suits levels %d to %d."
                    % (r["inn"], where or r["zone"], r["lo"], r["hi"]))
        else:
            desc = "Teleport to %s in %s." % (r["inn"], where or r["zone"])
        w("-- %-34s %-26s %s" % (r["inn"][:34], (where or "")[:26],
                                 ("lvl %d-%d" % (r["lo"], r["hi"])) if r["lo"] else "lvl --"))
        w("DROP TEMPORARY TABLE IF EXISTS tmp_i;")
        w("CREATE TEMPORARY TABLE tmp_i LIKE spell_template;")
        w("INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = %d;" % CLONE_SPELL)
        w("UPDATE tmp_i SET")
        w("  entry = %d," % r["spell"])
        w("  name = '%s'," % sq(r["inn"]))
        w("  nameSubtext = '%s'," % sq(r["zone"]))
        w("  description = '%s'," % sq(desc))
        w("  spellIconId = %d," % HEARTH_ICON)
        w("  manaCost = 0, manaCostPercentage = 0, powerType = 0,")
        w("  spellLevel = 1, baseLevel = 1;")
        w("INSERT INTO spell_template SELECT * FROM tmp_i;")
        w("DROP TEMPORARY TABLE tmp_i;")
        w("INSERT INTO spell_target_position")
        w("  (id, target_map, target_position_x, target_position_y, target_position_z,"
          " target_orientation)")
        w("  VALUES (%d, %d, %.4f, %.4f, %.4f, %.4f);"
          % (r["spell"], r["map"], r["x"], r["y"], r["z"], r["o"]))
        w("INSERT INTO skill_line_ability")
        w("  (id, skill_id, spell_id, req_skill_value, max_value, min_value)")
        w("  VALUES (%d, %d, %d, 0, 0, 0);"
          % (7900 + i, inns.SKILL_ADVENTURING, r["spell"]))
        w("")

    w("-- " + "-" * 85)
    w("-- Verification")
    w("-- " + "-" * 85)
    w("SELECT 'spells' AS what, COUNT(*) AS n FROM spell_template WHERE entry IN (%s)" % ids)
    w("UNION ALL SELECT 'destinations', COUNT(*) FROM spell_target_position WHERE id IN (%s)"
      % ids)
    w("UNION ALL SELECT 'skill lines', COUNT(*) FROM skill_line_ability WHERE spell_id IN (%s);"
      % ids)
    w("")
    w("-- Every destination should be on map 0 or 1 and nowhere near the origin.")
    w("SELECT id, target_map, ROUND(target_position_x) x, ROUND(target_position_y) y")
    w("FROM spell_target_position WHERE id IN (%s)" % ids)
    w("  AND (ABS(target_position_x) < 1 AND ABS(target_position_y) < 1);")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote %s (%d inns)" % (OUT, len(rows)))
    write_lua(rows)


def write_lua(rows):
    """The same list again, for the server script that hands these out.

    THE GLOBAL IS READ LAZILY BY inn_discovery.lua, NOT AT ITS LOAD TIME.
    ElunaLoader.cpp:338 sorts scripts by file path, so "inn_discovery" loads BEFORE
    "inn_targets" and this table does not exist yet when that script's chunk runs.
    """
    L = ["-- Every inn and where it is. GENERATED by gen_inns.py - do not edit by hand.",
         "--",
         "-- Read lazily by inn_discovery.lua: scripts load in path order, so this file runs",
         "-- second and the global is not there when that one is first executed.",
         "",
         "TerapinInns = {"]
    for r in rows:
        where = ", ".join(x for x in (r["town"], r["zone"]) if x and x != r["inn"])
        L.append("    {spell = %d, name = %s, where = %s, map = %d, x = %.2f, y = %.2f, "
                 "z = %.2f, lo = %d, hi = %d},"
                 % (r["spell"], lq(r["inn"]), lq(where or r["zone"]),
                    r["map"], r["x"], r["y"], r["z"], r["lo"], r["hi"]))
    L.append("}")
    L.append("")
    L.append("TerapinInnSkill = %d" % inns.SKILL_ADVENTURING)
    L.append("")
    path = os.path.join(SERVER_LUA, "inn_targets.lua")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print("wrote %s" % path)


def sq(s):
    return s.replace("'", "''")


def lq(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


if __name__ == "__main__":
    main()
