"""Generate sql/26-dungeon-scaling.sql and the Lua dungeon-level table.

    python gen_scaling.py

Writes:
    sql/26-dungeon-scaling.sql                    the aura ladder + the opt-out marker
    <server>/lua_scripts/dungeon_levels.lua       map id -> entry level, read from the DB

The dungeon table is GENERATED rather than hand-written because every one of the 29 dungeons
already carries a usable level in areatrigger_teleport.required_level, and a hand-copied list
would rot the first time one changed.
"""
import os, sys, subprocess
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import scaling as S

HERE = os.path.dirname(os.path.abspath(__file__))
MYSQL = r"D:\Games\turtlewow\tortoise-oneclick-compiler\DB\bin\mysql.exe"
LUA_OUT = r"D:\Games\turtlewow\TortoiseNew\TortoiseCompiledNew\server\lua_scripts\dungeon_levels.lua"
SQL_OUT = os.path.join(HERE, "sql", "26-dungeon-scaling.sql")


def q(sql):
    r = subprocess.run([MYSQL, "-h127.0.0.1", "-P3307", "-umangos", "-pmangos", "-N", "-B",
                        "-e", sql], capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("mysql failed: " + r.stderr.strip())
    return [l.split("\t") for l in r.stdout.strip().splitlines() if l.strip()]


# ---------------------------------------------------------------------------------------
# 1. The dungeon level table
# ---------------------------------------------------------------------------------------
# MIN, NOT MAX, AND THIS WAS A LIVE BUG.
#
#   Turtle puts Grim Batol's entrance on map 43 - the same map id as Wailing Caverns - and it
#   requires level 61 where the Wailing Caverns door requires 10. With MAX, Wailing Caverns
#   inherited 61, and dungeon_scaling.lua adds its +10 offset on top: a level 15 player walking
#   into a level 17-24 dungeon was being scaled toward SEVENTY-ONE.
#
#   Map 43 is the only map in this database whose entrances disagree, so nothing else moved.
#
#   MIN is the right aggregate regardless of that quirk: where a dungeon has several doors, the
#   lowest one is the gate you can actually walk through, so it is the level the dungeon is
#   really balanced for.
rows = q("SELECT at.target_map, m.map_name, MIN(at.required_level) "
         "FROM tw_world.areatrigger_teleport at "
         "JOIN tw_world.map_template m ON m.entry = at.target_map "
         "WHERE m.map_type = 1 AND at.required_level > 0 "
         "GROUP BY at.target_map, m.map_name ORDER BY at.target_map;")
if len(rows) < 20:
    raise SystemExit("only %d dungeons found - that is too few, refusing to ship it" % len(rows))

L = ["-- GENERATED by TurtleMod/gen_scaling.py - do not edit by hand.",
     "--",
     "-- map id -> the level the dungeon requires to enter, read from",
     "-- areatrigger_teleport.required_level. All %d dungeons in this database carry one." % len(rows),
     "-- dungeon_scaling.lua adds TARGET_OFFSET (%d) to get the level it scales you toward." % S.TARGET_OFFSET,
     "",
     "TERAPIN_DUNGEON_LEVELS = {"]
for m, name, lvl in rows:
    L.append("  [%s] = %s,%s-- %s" % (m, lvl, " " * max(1, 10 - len(m) - len(lvl)), name))
L.append("}")
with open(LUA_OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(L) + "\n")
print("wrote %s (%d dungeons)" % (LUA_OUT, len(rows)))

# ---------------------------------------------------------------------------------------
# 2. The SQL
# ---------------------------------------------------------------------------------------
ladder = S.steps()
ids = [S.MARKER_SPELL] + [s for s, _ in ladder]

W = []
w = W.append
w("""-- ---------------------------------------------------------------------------------------
-- Dungeon mentor scaling.
--
-- GENERATED by gen_scaling.py from scaling.py. Do not edit by hand.
-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART, a rebuilt patch-6.mpq, and
-- lua_scripts/dungeon_scaling.lua + dungeon_levels.lua.
-- ---------------------------------------------------------------------------------------
--
-- WHAT IT DOES
--   Walk into a dungeon well above its level and your damage done, healing done and maximum
--   health are scaled down toward that dungeon's level. Leave, and it is gone. A level 60
--   can run Ragefire Chasm with a level 15 friend without trivialising it.
--
-- WHAT IS *NOT* REDUCED, DELIBERATELY
--   Stats. The obvious implementation - SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE (137) - reduces
--   TOTAL stats, which includes everything your gear gives you. That makes good gear feel
--   worthless, which is the opposite of the intent: the gear should still feel great, the
--   numbers coming out the other end should just be level-appropriate. So the three auras
--   used are 79 (damage done), 136 (healing done) and 133 (max health), all percentage.
--
--   Abilities, talents, gear and skill are all untouched. You are still a level 60 - you
--   just hit like the dungeon expects.
--
-- WHY A LADDER OF %d SPELLS
--   Eluna's Unit:AddAura applies a FIXED spell and there is no binding to set an aura's
--   magnitude at runtime, so the reduction is quantised into %d%%%% steps and the script picks
--   the nearest one down.
--
-- BASE POINTS
--   CalculateSimpleValue is EffectBasePoints + EffectBaseDice, and these carry a dice of 1,
--   so -40%%%% needs basePoints -41. Confirmed against stock spell 7000 "Tamed Pet Passive",
--   which uses basePoints -11 / dice 1 for -10%%%% damage.
--
-- THE OPT-OUT
--   %d "%s". If a player KNOWS it, scaling is skipped for them. Default is therefore ON for
--   everyone with nothing to grant. Players toggle it themselves by typing  !scale  in say;
--   dungeon_scaling.lua consumes the message and learns/unlearns the marker.
-- ---------------------------------------------------------------------------------------

USE tw_world;

DELETE FROM spell_template     WHERE entry IN (%s);
DELETE FROM skill_line_ability WHERE spell_id IN (%s);

DROP TEMPORARY TABLE IF EXISTS tmp_sc;
CREATE TEMPORARY TABLE tmp_sc LIKE spell_template;
""" % (len(ladder), S.STEP, S.MARKER_SPELL, S.MARKER_NAME,
       ",".join(map(str, ids)), ",".join(map(str, ids))))

w("-- The opt-out marker. Passive and hidden: it is a flag, not a button.")
w("INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = %d;" % S.CLONE_FROM)
w("UPDATE tmp_sc SET")
w("  entry = %d, name = '%s', nameSubtext = ''," % (S.MARKER_SPELL, S.MARKER_NAME))
w("  description = 'Dungeon scaling will not be applied to you.',")
w("  effect1 = 0, effect2 = 0, effect3 = 0,")
w("  effectItemType1 = 0, effectTriggerSpell1 = 0,")
w("  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,")
w("  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,")
w("  RecoveryTime = 0, categoryRecoveryTime = 0,")
w("  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,")
w("  EquippedItemClass = -1, RequiresSpellFocus = 0,")
w("  Attributes = 64 | 128;   -- PASSIVE | HIDDEN_CLIENTSIDE")
w("INSERT INTO spell_template SELECT * FROM tmp_sc;")
w("TRUNCATE tmp_sc;")
w("")

for sid, pct in ladder:
    bp = -(pct + 1)
    w("-- -%d%% damage done, healing done and maximum health" % pct)
    w("INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = %d;" % S.CLONE_FROM)
    w("UPDATE tmp_sc SET")
    w("  entry = %d, name = 'Mentor''s Restraint', nameSubtext = '%d%%'," % (sid, pct))
    w("  description = 'Your power is held back to suit this dungeon. Damage, healing and "
      "health reduced by %d%%.'," % pct)
    w("  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3")
    w("  effectApplyAuraName1 = %d, effectBasePoints1 = %d, effectBaseDice1 = 1, effectDieSides1 = 1,"
      % (S.AURA_DAMAGE_DONE, bp))
    w("  effectApplyAuraName2 = %d, effectBasePoints2 = %d, effectBaseDice2 = 1, effectDieSides2 = 1,"
      % (S.AURA_HEALING_DONE, bp))
    w("  effectApplyAuraName3 = %d, effectBasePoints3 = %d, effectBaseDice3 = 1, effectDieSides3 = 1,"
      % (S.AURA_HEALTH_PCT, bp))
    w("  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,")
    w("  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,")
    w("  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools")
    w("  effectItemType1 = 0, effectTriggerSpell1 = 0,")
    w("  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,")
    w("  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite")
    w("  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,")
    w("  EquippedItemClass = -1, RequiresSpellFocus = 0,")
    w("  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.")
    w("  AttributesEx = 0, spellIconId = 2458;")
    w("INSERT INTO spell_template SELECT * FROM tmp_sc;")
    w("TRUNCATE tmp_sc;")
    w("")

w("DROP TEMPORARY TABLE tmp_sc;")
w("")
w("SELECT entry, name, nameSubtext, effectBasePoints1, effectApplyAuraName1, effectApplyAuraName2, effectApplyAuraName3")
w("FROM spell_template WHERE entry IN (%s) ORDER BY entry;" % ",".join(map(str, ids)))

with open(SQL_OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(W) + "\n")
print("wrote %s (%d spells: 1 marker + %d ladder)" % (SQL_OUT, len(ids), len(ladder)))

# ---------------------------------------------------------------------------------------
# 3. Show the resulting curve so the numbers can be sanity-checked at a glance
# ---------------------------------------------------------------------------------------
print("\nreduction curve (player level -> %% cut), for a few dungeons:")
for m, name, lvl in rows[:1] + [r for r in rows if r[1] in ("Deadmines", "Scarlet Monastery", "Stratholme")]:
    lv = int(lvl)
    line = "  %-20s (req %2d, target %2d): " % (name[:20], lv, lv + S.TARGET_OFFSET)
    line += "  ".join("L%d=%d%%" % (p, S.reduction_for(p, lv)) for p in (20, 30, 40, 60))
    print(line)
