"""Generate sql/23-summon-services.sql from summons.py. Do not edit the SQL by hand."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import summons as S

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sql", "23-summon-services.sql")
L = []
w = L.append

w("""-- ---------------------------------------------------------------------------------------
-- Summonable services: a class-trainer call per class, plus a banker.
--
-- GENERATED by gen_summons.py from summons.py. Do not edit by hand.
-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART, a rebuilt patch-6.mpq, and
-- lua_scripts/summon_services.lua.
-- ---------------------------------------------------------------------------------------
--
-- WHY NINE SPELLS AND NOT ONE
--   Creature::IsTrainerOf enforces an exact class match for TRAINER_TYPE_CLASS, so there
--   are nine distinct trainer NPCs no matter what. Given that, a per-class spell costs one
--   extra row and lets a warrior see "Call Warrior Master" instead of something generic.
--
-- CLASS GATING IS BY GRANT, NOT BY SPELL DATA
--   Each spell is inserted into playercreateinfo_spell only for its own class, and granted
--   to existing characters only of that class. A warrior is never taught the paladin call,
--   so there is nothing to hide. No skill_line_ability row, so these sit in GENERAL.
--
-- THE BANKER NPC IS CUSTOM ON PURPOSE
--   Every stock banker is faction-specific - Olivia Burnside is faction 12 (Alliance),
--   Randolph Montague 68 (Horde) - so neither works for both sides. 2600400 is cloned from
--   21002 like the other custom NPCs, which gives faction 35: friendly to everyone.
--
--   UNIT_NPC_FLAG_BANKER is 0x100 (256) in this core, NOT the 0x80 you may expect. npc_flags
--   257 = GOSSIP + BANKER. Getting this wrong gives an NPC whose window silently never
--   opens, which is exactly the trap the VENDOR flag sets in setup-class-and-profession-npcs.
--
-- Strongbox (38601) is still the simpler way to reach your own bank. The summoned banker
-- exists because it is a PHYSICAL npc, so in a duo one summon serves both players.
-- ---------------------------------------------------------------------------------------

USE tw_world;

-- ---------------------------------------------------------------------------------------
-- 1. The banker NPC, cloned from 21002 (faction 35, level 1, no unit flags).
-- ---------------------------------------------------------------------------------------
DELETE FROM creature_template WHERE entry = %d;
DROP TEMPORARY TABLE IF EXISTS tmp_npc;
CREATE TEMPORARY TABLE tmp_npc LIKE creature_template;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET
  entry       = %d,
  name        = 'Banker',
  subname     = 'Summoned',
  npc_flags   = 257,          -- GOSSIP (0x01) + BANKER (0x100). NOT 0x80.
  display_id1 = 15420;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DROP TEMPORARY TABLE tmp_npc;
""" % (S.BANKER_CREATURE, S.BANKER_CREATURE))

w("-- ---------------------------------------------------------------------------------------")
w("-- 2. The spells. Cloned from Disenchant like Salvage and Strongbox, then retargeted at")
w("--    the caster and stripped of cost, reagents and cooldown.")
w("-- ---------------------------------------------------------------------------------------")

spells = S.all_spells()
ids = ",".join(str(s[0]) for s in spells)
w("DELETE FROM spell_template        WHERE entry   IN (%s);" % ids)
w("DELETE FROM skill_line_ability    WHERE spell_id IN (%s);   -- GENERAL tab on purpose" % ids)
w("DELETE FROM playercreateinfo_spell WHERE spell  IN (%s);" % ids)
w("")

for sid, name, desc, icon, npc, cid in spells:
    w("-- %-22s -> creature %d%s" % (name, npc, "" if cid is None else "  (class %d only)" % cid))
    w("DROP TEMPORARY TABLE IF EXISTS tmp_s;")
    w("CREATE TEMPORARY TABLE tmp_s LIKE spell_template;")
    w("INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = %d;" % S.CLONE_FROM)
    w("UPDATE tmp_s SET")
    w("  entry = %d, name = '%s', nameSubtext = ''," % (sid, name.replace("'", "''")))
    w("  description = '%s'," % desc.replace("'", "''"))
    w("  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it")
    w("  effectItemType1 = 0, effectTriggerSpell1 = 0,")
    w("  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,")
    w("  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,")
    w("  RecoveryTime = 0, categoryRecoveryTime = 0,")
    w("  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,")
    w("  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = %d;" % icon)
    w("INSERT INTO spell_template SELECT * FROM tmp_s;")
    w("DROP TEMPORARY TABLE tmp_s;")
    if cid is None:
        w("INSERT INTO playercreateinfo_spell (race, class, spell, note)")
        w("  SELECT DISTINCT race, class, %d, 'TurtleMod: summon' FROM playercreateinfo;" % sid)
        w("INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)")
        w("  SELECT guid, %d, 1, 0 FROM tw_char.characters;" % sid)
    else:
        w("INSERT INTO playercreateinfo_spell (race, class, spell, note)")
        w("  SELECT DISTINCT race, class, %d, 'TurtleMod: summon' FROM playercreateinfo" % sid)
        w("  WHERE class = %d;" % cid)
        w("INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)")
        w("  SELECT guid, %d, 1, 0 FROM tw_char.characters WHERE class = %d;" % (sid, cid))
    w("")

w("-- ---------------------------------------------------------------------------------------")
w("SELECT entry, name, spellIconId FROM spell_template WHERE entry IN (%s) ORDER BY entry;" % ids)
w("SELECT entry, name, npc_flags FROM creature_template WHERE entry = %d;" % S.BANKER_CREATURE)
w("SELECT s.name, COUNT(*) AS granted FROM tw_char.character_spell cs")
w("  JOIN spell_template s ON s.entry = cs.spell")
w("  WHERE cs.spell IN (%s) GROUP BY s.name ORDER BY s.name;" % ids)

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(L) + "\n")
print("wrote %s (%d lines, %d spells)" % (OUT, len(L), len(spells)))
