"""Builds professions_tab.py - every profession spell that belongs in a Professions tab.

WHY A TAB NEEDS A NEW SKILL LINE AT ALL
  A spellbook tab is a SkillLine of CATEGORY 7. That is not a guess: category 7's members are
  Frost, Fire, Arms, Combat, Subtlety, Poisons - exactly the tab names in a vanilla spellbook.
  Professions are category 11, which is why Blacksmithing, Mining, Smelting, First Aid and the
  rest all pile into General with no tab of their own.

  So a new category-7 line, "Professions", is created and these spells are filed under it.

THE RE-FILING IS CLIENT-SIDE ONLY, AND THAT IS THE WHOLE TRICK
  The server must keep seeing Smelting under Mining, because Player::UpdateCraftSkill walks
  the skill-line rows for a spell and rolls the skill-up against the FIRST one with a skill
  id. Re-file it server-side and skill-ups would roll against a skill nobody has.

  build.py edits the CLIENT's SkillLineAbility.dbc only, and the server's skill_line_ability
  table is left alone. The client files the spell under Professions for display; the server
  still knows it is Mining. The same deliberate divergence as mounted casting.

WHAT IS INCLUDED, AND WHAT IS NOT
  Spells under a profession skill line that are NOT recipes:

      effect 24  CREATE_ITEM   excluded - a recipe, it lives in the trade window
      effect 36  LEARN_SPELL   excluded - a trainer wrapper, never in a spellbook
      effect 53  ENCHANT_ITEM  excluded - 162 enchants, they live in the enchanting window

  What is left is what actually sits in the spellbook: the profession itself and its ranks,
  specializations (Weaponsmith, Dragonscale Leatherworking), gathering (Mining, Herb
  Gathering, Skinning), Smelting, Disenchant, First Aid, Cooking, Fishing, and the Survival
  utilities like Cooking Fire and Traveler's Tent.
"""

import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
MYSQL = r"D:\Games\turtlewow\tortoise-oneclick-compiler\DB\bin\mysql.exe"

SKILL_PROFESSIONS = 796
SKILL_CATEGORY = 7          # the only category that produces a spellbook tab

# Every profession, gathering and secondary skill line whose spellbook entries we gather up.
PROFESSION_SKILLS = [
    129,   # First Aid
    142,   # Survival
    164,   # Blacksmithing
    165,   # Leatherworking
    171,   # Alchemy
    182,   # Herbalism
    185,   # Cooking
    186,   # Mining
    197,   # Tailoring
    202,   # Engineering
    333,   # Enchanting
    356,   # Fishing
    393,   # Skinning
    755,   # Jewelcrafting
]

# Recipes and trainer wrappers are not spellbook entries.
EXCLUDED_EFFECTS = (24, 36, 53)


def q(sql):
    r = subprocess.run([MYSQL, "-h127.0.0.1", "-P3307", "-umangos", "-pmangos", "-N", "-B",
                        "-e", sql], capture_output=True, text=True, encoding="utf-8")
    if r.returncode:
        raise SystemExit("mysql failed: %s" % r.stderr.strip()[:400])
    return [l.split("\t") for l in r.stdout.strip().split("\n") if l]


def main():
    rows = q(
        "SELECT DISTINCT s.entry, s.name, sla.skill_id "
        "FROM tw_world.spell_template s "
        "JOIN tw_world.skill_line_ability sla ON sla.spell_id = s.entry "
        "WHERE sla.skill_id IN (%s) "
        "  AND s.effect1 NOT IN (%s) "
        "  AND s.entry < 60000 "
        "ORDER BY sla.skill_id, s.entry"
        % (",".join(str(x) for x in PROFESSION_SKILLS),
           ",".join(str(x) for x in EXCLUDED_EFFECTS)))

    # One entry per spell. A spell filed under two profession lines keeps the first.
    seen, out = set(), []
    for entry, name, skill in rows:
        e = int(entry)
        if e in seen:
            continue
        seen.add(e)
        out.append((e, name, int(skill)))

    L = ['"""Profession spells that belong in the Professions tab.',
         'GENERATED by gen_professions_tab.py - do not edit by hand.',
         "",
         "Each entry is re-filed under SKILL_PROFESSIONS in the CLIENT's SkillLineAbility.dbc",
         "only. The server keeps its own filing so skill-ups still roll against the real",
         "profession - see the generator's docstring.",
         '"""',
         "",
         "SKILL_PROFESSIONS = %d" % SKILL_PROFESSIONS,
         "SKILL_CATEGORY = %d" % SKILL_CATEGORY,
         "",
         "# (spell id, name, the skill it really belongs to server-side)",
         "SPELLS = ["]
    for e, name, skill in out:
        L.append("    (%d, %r, %d)," % (e, name, skill))
    L += ["]", "", "", "def grid():", "    return SPELLS", ""]

    path = os.path.join(HERE, "professions_tab.py")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))

    per = {}
    for _, _, skill in out:
        per[skill] = per.get(skill, 0) + 1
    print("wrote %s" % path)
    print("  %d spells across %d profession skill lines" % (len(out), len(per)))
    for skill in sorted(per):
        print("    skill %-4d %d" % (skill, per[skill]))


if __name__ == "__main__":
    main()
