"""Export trainer-taught recipe reagents into a Lua table for TerapinTips.

    python gen_recipe_table.py

WHY THIS IS KEYED BY NAME
  The 1.12 trainer API gives a service NAME and nothing else - GetTrainerServiceInfo returns
  (name, subText, type, isExpanded), and there is no GetTrainerServiceItemLink in this client
  (checked against WoW.exe). So there is no spell id to look anything up by.

  Name matching works because a trainer wrapper is named identically to the craft spell it
  teaches - that is the vanilla convention (2754 "Copper Mace" teaches 2737 "Copper Mace"),
  and the same convention the TurtleMod recipes now follow.

WHY THE REAGENT NAMES ARE BAKED IN
  GetItemInfo only knows items the client has already seen. Looking reagents up at runtime
  would leave blanks for anything the player has never encountered - exactly the mats you
  most want listed before deciding to buy a recipe. So the names are resolved here, where
  the whole item table is available.
"""
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ADDON = r"D:\Games\turtlewow\client\Interface\AddOns\TerapinTips"
MYSQL = r"D:\Games\turtlewow\tortoise-oneclick-compiler\DB\bin\mysql.exe"

# One row per (recipe, reagent). Joins the trainer's wrapper to the craft spell it teaches,
# then each of the craft spell's four reagent slots to its item name.
SQL = """
SELECT c.name, i.name, r.cnt
FROM tw_world.npc_trainer nt
JOIN tw_world.spell_template t ON t.entry = nt.spell
JOIN tw_world.spell_template c ON c.entry = t.effectTriggerSpell1
JOIN (
    SELECT entry, reagent1 AS rg, reagentCount1 AS cnt, 1 AS slot FROM tw_world.spell_template WHERE reagent1 > 0
    UNION ALL SELECT entry, reagent2, reagentCount2, 2 FROM tw_world.spell_template WHERE reagent2 > 0
    UNION ALL SELECT entry, reagent3, reagentCount3, 3 FROM tw_world.spell_template WHERE reagent3 > 0
    UNION ALL SELECT entry, reagent4, reagentCount4, 4 FROM tw_world.spell_template WHERE reagent4 > 0
) r ON r.entry = c.entry
JOIN tw_world.item_template i ON i.entry = r.rg
GROUP BY c.name, r.slot, i.name, r.cnt
ORDER BY c.name, r.slot;
"""

out = subprocess.run([MYSQL, "-h127.0.0.1", "-P3307", "-umangos", "-pmangos", "-N", "-e", SQL],
                     capture_output=True, text=True).stdout

recipes = {}
for line in out.strip().splitlines():
    parts = line.split("\t")
    if len(parts) != 3:
        continue
    spell, item, count = parts[0], parts[1], parts[2]
    recipes.setdefault(spell, []).append("%sx %s" % (count, item))

if not recipes:
    raise SystemExit("no rows - is the database up on port 3307?")


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


lines = [
    "-- GENERATED by TurtleMod/gen_recipe_table.py - do not edit by hand.",
    "--",
    "-- Reagents for every trainer-taught recipe, keyed by the recipe's NAME because the",
    "-- 1.12 trainer API exposes a name and nothing else - there is no",
    "-- GetTrainerServiceItemLink in this client.",
    "--",
    "-- %d recipes." % len(recipes),
    "",
    "TerapinRecipes = {",
]
for spell in sorted(recipes):
    lines.append('  ["%s"] = "%s",' % (esc(spell), esc(", ".join(recipes[spell]))))
lines.append("}")
lines.append("")

if not os.path.isdir(ADDON):
    os.makedirs(ADDON)
path = os.path.join(ADDON, "recipes.lua")
with open(path, "w") as f:
    f.write("\n".join(lines))

print("wrote %s" % path)
print("  %d recipes, %.0f KB" % (len(recipes), os.path.getsize(path) / 1024.0))
for s in list(sorted(recipes))[:3]:
    print("    %-32s %s" % (s, recipes[s]))
