"""Remove tool and workbench requirements from every trade-skill recipe.

    python gen_crafting_tools.py

Writes:
    sql/30-no-tools-or-focus.sql   the server side
    crafting_tools.py              the spell id list, imported by content.py for the DBC

WHY BOTH SIDES
  The client enforces this from its OWN Spell.dbc, exactly like the mounted-cast restriction.
  A server-only change would leave the client still refusing to start the cast.

  The two sides do not even agree on scope: 925 server-side trade spells require a tool, but
  only 362 records in the client's Spell.dbc carry one. Clearing only the 362 the client
  knows about would leave 563 still blocked by the server, and vice versa.

SCOPE IS DELIBERATELY NARROW
  Only spells filed under a TRADE SKILL. `totem1`/`totem2` is a generic "required item" field
  and is also how shaman totem spells require their totem item - which is not a crafting tool
  and is left alone.
"""
import os, sys, subprocess
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

HERE = os.path.dirname(os.path.abspath(__file__))
MYSQL = r"D:\Games\turtlewow\tortoise-oneclick-compiler\DB\bin\mysql.exe"
SQL_OUT = os.path.join(HERE, "sql", "30-no-tools-or-focus.sql")
PY_OUT = os.path.join(HERE, "crafting_tools.py")

# Every trade skill line in this database.
TRADE_SKILLS = [164, 165, 171, 182, 185, 186, 197, 202, 333, 129, 356, 393, 755, 142]


def q(sql):
    r = subprocess.run([MYSQL, "-h127.0.0.1", "-P3307", "-umangos", "-pmangos", "-N", "-B",
                        "-e", sql], capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("mysql failed: " + r.stderr.strip())
    return [l.split("\t") for l in r.stdout.strip().splitlines() if l.strip()]


skills = ",".join(map(str, TRADE_SKILLS))
# EVERY trade-skill spell, not just the ones that currently carry a tool.
#
# Filtering on "totem1 > 0 OR requiresSpellFocus > 0" seemed tidier and was wrong: once the
# migration had been applied, re-running the generator found nothing server-side and quietly
# produced a SHORTER list. On a fresh database that list would have under-applied, leaving
# every server-only tool requirement in place. Selecting unconditionally makes the output
# stable no matter how many times it has already been run.
rows = q("SELECT DISTINCT s.entry FROM tw_world.spell_template s "
         "JOIN tw_world.skill_line_ability sla ON sla.spell_id = s.entry "
         "WHERE sla.skill_id IN (%s) ORDER BY s.entry;" % skills)
ids = set(int(r[0]) for r in rows)

# ---------------------------------------------------------------------------------------
# Union in the CLIENT's own view. The two sides genuinely disagree about which spells carry
# a tool, and a server-derived list alone leaves the tooltip still saying "Requires Anvil"
# on anything the client flags but the server does not. Measured: exactly one such spell
# (65210, focus 1) survived the first pass and kept showing the line in game.
# ---------------------------------------------------------------------------------------
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "tools"))
import mpyq, dbc, content                                            # noqa: E402
SEP = chr(92)
_a = mpyq.MPQArchive(os.path.join("D:/Games/turtlewow/client/Data", "patch-5.mpq"), listfile=False)
_sp = dbc.Dbc(_a.read_file("DBFilesClient" + SEP + "Spell.dbc"))
_sla = dbc.Dbc(_a.read_file("DBFilesClient" + SEP + "SkillLineAbility.dbc"))
_F = content.F
_trade = {r[2] for r in _sla.records if r[1] in set(TRADE_SKILLS)}
_before = len(ids)
for _r in _sp.records:
    if _r[0] in _trade:
        ids.add(_r[0])
print("client-only additions: %d" % (len(ids) - _before))
ids = sorted(ids)

if len(ids) < 1500:
    raise SystemExit("only %d affected spells found - that is too few, refusing to ship" % len(ids))
print("trade spells needing a tool or a workbench: %d" % len(ids))

# ---------------------------------------------------------------------------------------
with open(PY_OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write('"""GENERATED by gen_crafting_tools.py - do not edit by hand.\n\n'
            'Trade-skill spells that required a tool (totem1/totem2) or a workbench\n'
            '(requiresSpellFocus). content.py clears those fields in the client Spell.dbc;\n'
            'sql/30 clears them server-side. Both are needed - see the generator.\n"""\n\n')
    f.write("SPELLS_WITH_TOOLS = [\n")
    for i in range(0, len(ids), 12):
        f.write("    " + ", ".join(str(x) for x in ids[i:i + 12]) + ",\n")
    f.write("]\n")
print("wrote %s (%d ids)" % (PY_OUT, len(ids)))

# ---------------------------------------------------------------------------------------
L = []
w = L.append
w("""-- ---------------------------------------------------------------------------------------
-- No tools, no workbenches: craft anything, anywhere.
--
-- GENERATED by gen_crafting_tools.py. Do not edit by hand.
-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART and a rebuilt patch-6.mpq.
-- ---------------------------------------------------------------------------------------
--
-- WHAT IS REMOVED, for %d trade-skill recipes:
--
--   totem1 / totem2        the required TOOL. Blacksmith Hammer (427 recipes), Jewelers Kit
--                          (112), Precision Jewelers Kit (90), the Runed Rods (~180 between
--                          them), Arclight Spanner, Whittle, and the rest.
--
--   requiresSpellFocus     the required WORKBENCH, a nearby GAMEOBJECT_TYPE_SPELL_FOCUS:
--                            1  Anvil            (418 recipes)
--                            3  Forge            (188)
--                            4  (unnamed focus)  (99)
--                          623  The Black Anvil, 663 Alchemy Lab, 543 The Black Forge,
--                          883  Moon Well, 1362 Icebellow Anvil
--
-- WHY THIS NEEDS THE CLIENT PATCH TOO
--   The client enforces both from its OWN Spell.dbc - the same way it enforces the mounted
--   restriction. A server-only change leaves the client refusing to start the cast, so
--   nothing appears to happen.
--
--   The two sides do not even agree on scope: 925 server-side trade spells carry a tool, but
--   only 362 records in the client's Spell.dbc do. Each side has to be cleared on its own.
--
-- WHY SHAMAN TOTEMS ARE SAFE
--   totem1/totem2 is a generic "required item" field, and shaman totem spells use it for
--   their totem item. Only spells filed under a TRADE SKILL are touched here, so those are
--   left exactly as they were.
-- ---------------------------------------------------------------------------------------

USE tw_world;

SELECT 'BEFORE' AS stage,
       SUM(totem1 > 0 OR totem2 > 0) AS needs_tool,
       SUM(requiresSpellFocus > 0)   AS needs_workbench
FROM spell_template WHERE entry IN (%s);
""" % (len(ids), ",".join(map(str, ids))))

w("UPDATE spell_template SET totem1 = 0, totem2 = 0, requiresSpellFocus = 0")
w("WHERE entry IN (%s);" % ",".join(map(str, ids)))
w("")
w("SELECT 'AFTER' AS stage,")
w("       SUM(totem1 > 0 OR totem2 > 0) AS needs_tool,")
w("       SUM(requiresSpellFocus > 0)   AS needs_workbench")
w("FROM spell_template WHERE entry IN (%s);" % ",".join(map(str, ids)))

with open(SQL_OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(L) + "\n")
print("wrote %s" % SQL_OUT)
