"""Every inn in the world. GENERATED by gen_inn_data.py - do not edit by hand.

Each row is one teleport destination for the Adventuring skill. See gen_inn_data.py
for where each field comes from and why.

    inn/town/zone   display text, from the curated areatrigger_tavern name
    map/x/y/z/o     where you land - beside the innkeeper where there is one
    lo/hi           hostile levels around the inn, 0 when there was no sample
"""

# Skill line 795, category 9 - the same category as First Aid and Survival.
# NOT category 11: primary professions are capped at two per character, and
# Adventuring must never cost anyone a Blacksmithing slot.
SKILL_ADVENTURING = 795
SKILL_CATEGORY = 9
SPELL_BASE = 44200

INNS = [
    {'spell': 44200, 'trigger': 1, 'inn': "Hawk's Vigil", 'town': None, 'zone': 'Wetlands', 'map': 0, 'x': -3854.21, 'y': -1872.23, 'z': 142.19, 'o': 2.82, 'lo': 0, 'hi': 0},
    {'spell': 44201, 'trigger': 2, 'inn': 'Glenshire', 'town': None, 'zone': 'Tirisfal Uplands', 'map': 0, 'x': 1793.06, 'y': 2044.35, 'z': 120.89, 'o': 0.00, 'lo': 3, 'hi': 16},
    {'spell': 44202, 'trigger': 3, 'inn': "Alah'Thalas", 'town': None, 'zone': "Quel'Thalas", 'map': 0, 'x': 4232.66, 'y': -2778.11, 'z': 97.47, 'o': 0.00, 'lo': 5, 'hi': 57},
    {'spell': 44203, 'trigger': 4, 'inn': "Caelan's Rest", 'town': None, 'zone': 'Lapidis Isle', 'map': 0, 'x': -11886.60, 'y': 3161.77, 'z': 16.51, 'o': 0.00, 'lo': 45, 'hi': 53},
    {'spell': 44204, 'trigger': 5, 'inn': "Maul'ogg Refuge", 'town': None, 'zone': "Gillijim's Isle", 'map': 0, 'x': -14014.20, 'y': 2329.32, 'z': 60.12, 'o': 0.00, 'lo': 49, 'hi': 52},
    {'spell': 44205, 'trigger': 6, 'inn': 'Karfang Hold', 'town': None, 'zone': 'Burning Steppes', 'map': 0, 'x': -7471.82, 'y': -2893.55, 'z': 230.06, 'o': 0.00, 'lo': 50, 'hi': 55},
    {'spell': 44206, 'trigger': 7, 'inn': 'Earthen Ring Inn', 'town': None, 'zone': 'Stonetalon Mountains', 'map': 1, 'x': 659.00, 'y': 842.00, 'z': 123.00, 'o': 0.00, 'lo': 10, 'hi': 19},
    {'spell': 44207, 'trigger': 8, 'inn': 'Moonhoof Village Inn', 'town': None, 'zone': 'Moonwhisper Coast', 'map': 1, 'x': 8305.56, 'y': -6606.98, 'z': 22.83, 'o': 3.01, 'lo': 43, 'hi': 55},
    {'spell': 44208, 'trigger': 71, 'inn': 'Sentinel Hill Inn', 'town': None, 'zone': 'Westfall', 'map': 0, 'x': -10653.30, 'y': 1166.43, 'z': 34.93, 'o': 5.78, 'lo': 11, 'hi': 16},
    {'spell': 44209, 'trigger': 178, 'inn': 'Strahnbrad Inn', 'town': 'Strahnbrad', 'zone': 'Strahnbrad', 'map': 0, 'x': 683.77, 'y': -912.14, 'z': 174.50, 'o': 0.00, 'lo': 34, 'hi': 36},
    {'spell': 44210, 'trigger': 204, 'inn': 'Bael Hardul Inn', 'town': None, 'zone': 'Stonetalon Mountains', 'map': 1, 'x': 928.15, 'y': -830.01, 'z': 166.10, 'o': 0.00, 'lo': 16, 'hi': 55},
    {'spell': 44211, 'trigger': 206, 'inn': 'Mudsprocket', 'town': None, 'zone': 'Dustwallow Marsh', 'map': 1, 'x': -4593.90, 'y': -3162.81, 'z': 34.70, 'o': 6.19, 'lo': 40, 'hi': 42},
    {'spell': 44212, 'trigger': 210, 'inn': 'Sparkwater Port', 'town': None, 'zone': 'Durotar', 'map': 1, 'x': 921.14, 'y': -5064.10, 'z': 8.02, 'o': 0.00, 'lo': 7, 'hi': 10},
    {'spell': 44213, 'trigger': 562, 'inn': "Lion's Pride Inn", 'town': 'Goldshire', 'zone': 'Elwynn Forest', 'map': 0, 'x': -9466.37, 'y': 21.42, 'z': 56.34, 'o': 1.50, 'lo': 5, 'hi': 6},
    {'spell': 44214, 'trigger': 682, 'inn': 'Lakeshire Inn', 'town': None, 'zone': 'Redridge Mountains', 'map': 0, 'x': -9223.98, 'y': -2157.12, 'z': 64.02, 'o': 3.05, 'lo': 17, 'hi': 20},
    {'spell': 44215, 'trigger': 707, 'inn': 'Scarlet Raven Inn', 'town': 'Darkshire', 'zone': 'Duskwood', 'map': 0, 'x': -10516.00, 'y': -1161.21, 'z': 28.12, 'o': 4.03, 'lo': 24, 'hi': 38},
    {'spell': 44216, 'trigger': 708, 'inn': 'Southshore Inn', 'town': None, 'zone': 'Hillsbrad Foothills', 'map': 0, 'x': -857.10, 'y': -570.75, 'z': 11.26, 'o': 1.55, 'lo': 24, 'hi': 55},
    {'spell': 44217, 'trigger': 709, 'inn': 'Theramore Isle', 'town': None, 'zone': 'Dustwallow Marsh', 'map': 1, 'x': -3616.13, 'y': -4470.82, 'z': 14.33, 'o': 2.22, 'lo': 36, 'hi': 55},
    {'spell': 44218, 'trigger': 710, 'inn': 'Thunderbrew Distillery', 'town': 'Kharanos', 'zone': 'Dun Morogh', 'map': 0, 'x': -5601.60, 'y': -531.20, 'z': 399.74, 'o': 2.13, 'lo': 5, 'hi': 6},
    {'spell': 44219, 'trigger': 712, 'inn': 'Stoutlager Inn', 'town': 'Thelsamar', 'zone': 'Loch Modan', 'map': 0, 'x': -5377.91, 'y': -2973.91, 'z': 323.25, 'o': 1.78, 'lo': 10, 'hi': 11},
    {'spell': 44220, 'trigger': 713, 'inn': 'Deepwater Tavern', 'town': 'Menethil Harbor', 'zone': 'Wetlands', 'map': 0, 'x': -3827.93, 'y': -831.90, 'z': 10.09, 'o': 0.40, 'lo': 28, 'hi': 38},
    {'spell': 44221, 'trigger': 715, 'inn': 'Dolanaar', 'town': None, 'zone': 'Teldrassil', 'map': 1, 'x': 9802.21, 'y': 982.61, 'z': 1313.98, 'o': 4.80, 'lo': 5, 'hi': 5},
    {'spell': 44222, 'trigger': 716, 'inn': 'Auberdine', 'town': None, 'zone': 'Darkshore', 'map': 1, 'x': 6406.51, 'y': 515.37, 'z': 8.73, 'o': 1.27, 'lo': 10, 'hi': 12},
    {'spell': 44223, 'trigger': 717, 'inn': 'Astranaar', 'town': None, 'zone': 'Ashenvale', 'map': 1, 'x': 2781.16, 'y': -433.00, 'z': 116.67, 'o': 2.58, 'lo': 20, 'hi': 40},
    {'spell': 44224, 'trigger': 719, 'inn': "Gallows' End Tavern", 'town': 'Brill', 'zone': 'Tirisfal Glades', 'map': 0, 'x': 2269.51, 'y': 244.94, 'z': 34.34, 'o': 3.75, 'lo': 5, 'hi': 9},
    {'spell': 44225, 'trigger': 720, 'inn': 'The Sepulcher Inn', 'town': 'The Sepulcher', 'zone': 'Silverpine Forest', 'map': 0, 'x': 510.92, 'y': 1636.47, 'z': 126.03, 'o': 4.31, 'lo': 10, 'hi': 13},
    {'spell': 44226, 'trigger': 721, 'inn': 'Tarren Mill Inn', 'town': 'Tarren Mill', 'zone': 'Hillsbrad Foothills', 'map': 0, 'x': -5.97, 'y': -942.28, 'z': 57.16, 'o': 2.74, 'lo': 20, 'hi': 55},
    {'spell': 44227, 'trigger': 722, 'inn': 'Bloodhoof Village Inn', 'town': 'Bloodhoof Village', 'zone': 'Mulgore', 'map': 1, 'x': -2365.37, 'y': -347.31, 'z': -8.87, 'o': 5.85, 'lo': 5, 'hi': 6},
    {'spell': 44228, 'trigger': 742, 'inn': 'The Crossroads Inn', 'town': 'The Crossroads', 'zone': 'The Barrens', 'map': 1, 'x': -413.60, 'y': -2644.88, 'z': 96.22, 'o': 3.34, 'lo': 3, 'hi': 11},
    {'spell': 44229, 'trigger': 743, 'inn': 'Ratchet Inn', 'town': 'Ratchet', 'zone': 'The Barrens', 'map': 1, 'x': -1050.04, 'y': -3664.80, 'z': 23.97, 'o': 6.00, 'lo': 14, 'hi': 57},
    {'spell': 44230, 'trigger': 843, 'inn': 'Razor Hill Inn', 'town': 'Razor Hill', 'zone': 'Durotar', 'map': 1, 'x': 340.36, 'y': -4686.29, 'z': 16.54, 'o': 4.19, 'lo': 6, 'hi': 7},
    {'spell': 44231, 'trigger': 844, 'inn': 'Stonard Inn', 'town': 'Stonard', 'zone': 'Swamp of Sorrows', 'map': 0, 'x': -10487.30, 'y': -3258.84, 'z': 21.11, 'o': 0.10, 'lo': 36, 'hi': 50},
    {'spell': 44232, 'trigger': 862, 'inn': 'Booty Bay Inn', 'town': 'Booty Bay', 'zone': 'Stranglethorn Vale', 'map': 0, 'x': -14457.70, 'y': 495.35, 'z': 15.21, 'o': 3.98, 'lo': 41, 'hi': 57},
    {'spell': 44233, 'trigger': 982, 'inn': 'Camp Taurajo Inn', 'town': 'Camp Taurajo', 'zone': 'The Barrens', 'map': 1, 'x': -2376.27, 'y': -1995.74, 'z': 96.79, 'o': 1.06, 'lo': 11, 'hi': 20},
    {'spell': 44234, 'trigger': 1022, 'inn': 'Sun Rock Retreat Inn', 'town': 'Sun Rock Retreat', 'zone': 'Stonetalon Mountains', 'map': 1, 'x': 893.65, 'y': 927.95, 'z': 106.36, 'o': 5.71, 'lo': 10, 'hi': 17},
    {'spell': 44235, 'trigger': 1023, 'inn': 'Gadgetzan Inn', 'town': 'Gadgetzan', 'zone': 'Tanaris', 'map': 1, 'x': -7158.96, 'y': -3841.61, 'z': 8.85, 'o': 1.95, 'lo': 40, 'hi': 57},
    {'spell': 44236, 'trigger': 1024, 'inn': 'Feathermoon Stronghold Inn', 'town': 'Feathermoon Stronghold', 'zone': 'Feralas', 'map': 1, 'x': -4381.59, 'y': 3289.45, 'z': 13.63, 'o': 0.03, 'lo': 40, 'hi': 55},
    {'spell': 44237, 'trigger': 1025, 'inn': 'Camp Mojache Inn', 'town': 'Camp Mojache', 'zone': 'Feralas', 'map': 1, 'x': -4460.10, 'y': 242.72, 'z': 39.19, 'o': 0.51, 'lo': 40, 'hi': 41},
    {'spell': 44238, 'trigger': 1042, 'inn': 'Aerie Peak Inn', 'town': 'Aerie Peak', 'zone': 'Wildhammer Keep', 'map': 0, 'x': 394.66, 'y': -2097.14, 'z': 131.56, 'o': 4.93, 'lo': 40, 'hi': 41},
    {'spell': 44239, 'trigger': 1606, 'inn': 'Kargath Inn', 'town': 'Kargath', 'zone': 'Badlands', 'map': 0, 'x': -6650.10, 'y': -2149.41, 'z': 245.35, 'o': 4.00, 'lo': 39, 'hi': 55},
    {'spell': 44240, 'trigger': 1646, 'inn': 'Hammerfall Inn', 'town': 'Hammerfall', 'zone': 'Arathi Highlands', 'map': 0, 'x': -912.37, 'y': -3524.92, 'z': 72.77, 'o': 3.14, 'lo': 31, 'hi': 50},
    {'spell': 44241, 'trigger': 1700, 'inn': 'Ambershire Inn', 'town': None, 'zone': 'Northwind', 'map': 0, 'x': -7623.89, 'y': 621.24, 'z': 50.33, 'o': 0.00, 'lo': 28, 'hi': 29},
    {'spell': 44242, 'trigger': 1702, 'inn': 'Shatterblade Point Inn', 'town': None, 'zone': 'Grim Reaches', 'map': 0, 'x': -4024.25, 'y': -5291.40, 'z': 206.69, 'o': 0.00, 'lo': 35, 'hi': 37},
    {'spell': 44243, 'trigger': 1703, 'inn': 'Dun Kithas Inn', 'town': None, 'zone': 'Grim Reaches', 'map': 0, 'x': -4938.09, 'y': -4837.04, 'z': 172.72, 'o': 0.00, 'lo': 31, 'hi': 40},
    {'spell': 44244, 'trigger': 1704, 'inn': 'Steepcliff Port Inn', 'town': None, 'zone': 'Tirisfal Glades', 'map': 0, 'x': 1959.91, 'y': 2828.65, 'z': 3.62, 'o': 4.72, 'lo': 15, 'hi': 17},
    {'spell': 44245, 'trigger': 1705, 'inn': 'Nordanaar Inn', 'town': None, 'zone': 'Hyjal', 'map': 1, 'x': 5501.85, 'y': -3805.45, 'z': 1609.59, 'o': 0.00, 'lo': 60, 'hi': 60},
    {'spell': 44246, 'trigger': 2266, 'inn': "Nijel's Point Inn", 'town': "Nijel's Point", 'zone': 'Desolace', 'map': 1, 'x': 255.62, 'y': 1253.76, 'z': 192.22, 'o': 3.25, 'lo': 0, 'hi': 0},
    {'spell': 44247, 'trigger': 2267, 'inn': 'Shadowprey Village Inn', 'town': 'Shadowprey Village', 'zone': 'Desolace', 'map': 1, 'x': -1592.84, 'y': 3150.27, 'z': 46.58, 'o': 4.19, 'lo': 37, 'hi': 55},
    {'spell': 44248, 'trigger': 2286, 'inn': 'Freewind Post Inn', 'town': 'Freewind Post', 'zone': 'Thousand Needles', 'map': 1, 'x': -5477.85, 'y': -2460.43, 'z': 89.37, 'o': 0.31, 'lo': 25, 'hi': 45},
    {'spell': 44249, 'trigger': 2287, 'inn': 'Everlook Inn', 'town': 'Everlook', 'zone': 'Winterspring', 'map': 1, 'x': 6695.15, 'y': -4673.04, 'z': 721.65, 'o': 0.54, 'lo': 55, 'hi': 57},
    {'spell': 44250, 'trigger': 2610, 'inn': 'Splintertree Post Inn', 'town': 'Splintertree Post', 'zone': 'Ashenvale', 'map': 1, 'x': 2341.86, 'y': -2566.99, 'z': 102.86, 'o': 2.29, 'lo': 25, 'hi': 40},
    {'spell': 44251, 'trigger': 2708, 'inn': 'Brinthilien Inn', 'town': None, 'zone': 'Thalassian Highlands', 'map': 0, 'x': 3169.57, 'y': -2530.02, 'z': 110.90, 'o': 0.00, 'lo': 3, 'hi': 55},
    {'spell': 44252, 'trigger': 2786, 'inn': 'farm Inn', 'town': 'farm', 'zone': 'Stormwind backup rest', 'map': 0, 'x': -9050.87, 'y': 445.46, 'z': 93.06, 'o': 0.00, 'lo': 5, 'hi': 9},
    {'spell': 44253, 'trigger': 3547, 'inn': 'Undercity Inn', 'town': 'Undercity', 'zone': 'The Undercity', 'map': 0, 'x': 1642.10, 'y': 239.84, 'z': 62.59, 'o': 0.00, 'lo': 7, 'hi': 60},
    {'spell': 44254, 'trigger': 3690, 'inn': 'Revantusk Village Inn', 'town': 'Revantusk Village', 'zone': 'Revantusk Village', 'map': 0, 'x': -622.14, 'y': -4582.14, 'z': 22.58, 'o': 0.00, 'lo': 55, 'hi': 55},
    {'spell': 44255, 'trigger': 3886, 'inn': 'z2 Inn', 'town': 'z2', 'zone': "Grom'gol Base Camp", 'map': 0, 'x': -12434.40, 'y': 211.56, 'z': 2.45, 'o': 0.91, 'lo': 35, 'hi': 55},
    {'spell': 44256, 'trigger': 3985, 'inn': 'Cenarion Hold Inn', 'town': 'Cenarion Hold', 'zone': 'Cenarion Hold', 'map': 1, 'x': -6864.98, 'y': 731.61, 'z': 50.00, 'o': 0.00, 'lo': 57, 'hi': 60},
    {'spell': 44257, 'trigger': 4058, 'inn': "Light's Hope Chapel Inn", 'town': "Light's Hope Chapel", 'zone': "Light's Hope Chapel", 'map': 0, 'x': 2298.17, 'y': -5340.98, 'z': 90.88, 'o': 0.00, 'lo': 54, 'hi': 60},
    {'spell': 44258, 'trigger': 4090, 'inn': 'Stonetalon Peak Inn', 'town': 'Stonetalon Peak', 'zone': 'Stonetalon Peak', 'map': 1, 'x': 2729.88, 'y': 1498.14, 'z': 237.59, 'o': 4.05, 'lo': 22, 'hi': 24},
    {'spell': 44259, 'trigger': 4306, 'inn': 'Powder Town Inn', 'town': None, 'zone': 'Stonetalon Mountains', 'map': 1, 'x': 1375.75, 'y': 1719.41, 'z': 144.72, 'o': 0.00, 'lo': 22, 'hi': 25},
    {'spell': 44260, 'trigger': 4310, 'inn': 'Tel Co. Basecamp', 'town': None, 'zone': "Tel'Abim", 'map': 1, 'x': -8849.21, 'y': -6506.48, 'z': 12.81, 'o': 0.00, 'lo': 53, 'hi': 55},
    {'spell': 44261, 'trigger': 5020, 'inn': 'Rustgate Inn', 'town': None, 'zone': 'Blackstone Island', 'map': 1, 'x': -344.60, 'y': -7465.13, 'z': 80.32, 'o': 0.00, 'lo': 3, 'hi': 7},
    {'spell': 44262, 'trigger': 5338, 'inn': 'Shademore Tavern', 'town': None, 'zone': 'Gilneas', 'map': 0, 'x': -1664.70, 'y': 2028.87, 'z': 54.69, 'o': 0.00, 'lo': 39, 'hi': 41},
]


def grid():
    return INNS
