-- -------------------------------------------------------------------------------------
-- TurtleMod test content - GENERATED by gen_test_sql.py. Do not edit by hand.
--
--   * one buff spell per class specialization (27), filed under that spec's
--     spellbook tab and trainable at level 2 from the matching class master
--   * one craft recipe per profession (0) at skill 5, from basic mats
--
-- Run against tw_world. IDEMPOTENT. Requires a mangosd RESTART and the rebuilt
-- patch-6.mpq, which carries the client-side Spell.dbc and SkillLineAbility.dbc rows.
--
-- All spell ids are in the reserved 38xxx block. See TurtleMod/SPELL-IDS.md - ids
-- above 65535 are silently truncated to 16 bits by SMSG_INITIAL_SPELLS and arrive at
-- the client as a completely different spell.
-- -------------------------------------------------------------------------------------

USE tw_world;

-- Idempotency: clear anything a previous run left behind.
DELETE FROM spell_template     WHERE entry    IN (38100,38101,38102,38103,38104,38105,38106,38107,38108,38109,38110,38111,38112,38113,38114,38115,38116,38117,38118,38119,38120,38121,38122,38123,38124,38125,38126,38150,38151,38152,38153,38154,38155,38156,38157,38158,38159,38160,38161,38162,38163,38164,38165,38166,38167,38168,38169,38170,38171,38172,38173,38174,38175,38176);
DELETE FROM npc_trainer        WHERE spell    IN (38100,38101,38102,38103,38104,38105,38106,38107,38108,38109,38110,38111,38112,38113,38114,38115,38116,38117,38118,38119,38120,38121,38122,38123,38124,38125,38126,38150,38151,38152,38153,38154,38155,38156,38157,38158,38159,38160,38161,38162,38163,38164,38165,38166,38167,38168,38169,38170,38171,38172,38173,38174,38175,38176);
DELETE FROM skill_line_ability WHERE spell_id IN (38100,38101,38102,38103,38104,38105,38106,38107,38108,38109,38110,38111,38112,38113,38114,38115,38116,38117,38118,38119,38120,38121,38122,38123,38124,38125,38126,38150,38151,38152,38153,38154,38155,38156,38157,38158,38159,38160,38161,38162,38163,38164,38165,38166,38167,38168,38169,38170,38171,38172,38173,38174,38175,38176);
DELETE FROM item_template      WHERE entry    IN ();

-- =====================================================================================
-- PART 1 - 27 class specialization buffs
--
-- Each is filed under a REAL SkillLine.dbc class skill line (Arms, Fury, Frost, ...),
-- which is what puts it on that tab in the spellbook rather than under General.
-- =====================================================================================

-- Warrior  Arms              Strength  ability 38100, teacher 38150, skill line 26
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38100,
  name = 'Arms Buff',
  nameSubtext = '',
  description = 'This is the Arms test custom spell. Buffs Strength by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 0,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 4,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38150,
  name = 'Arms Buff',
  nameSubtext = '',
  description = 'Teaches Arms Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38100,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 4,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Warrior  Fury              Agility   ability 38101, teacher 38151, skill line 256
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38101,
  name = 'Fury Buff',
  nameSubtext = '',
  description = 'This is the Fury test custom spell. Buffs Agility by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 1,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 4,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38151,
  name = 'Fury Buff',
  nameSubtext = '',
  description = 'Teaches Fury Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38101,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 4,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Warrior  Protection        Stamina   ability 38102, teacher 38152, skill line 257
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38102,
  name = 'Protection Buff',
  nameSubtext = '',
  description = 'This is the Protection test custom spell. Buffs Stamina by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 2,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 4,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38152,
  name = 'Protection Buff',
  nameSubtext = '',
  description = 'Teaches Protection Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38102,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 4,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Paladin  Holy              Intellect ability 38103, teacher 38153, skill line 594
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38103,
  name = 'Holy Buff',
  nameSubtext = '',
  description = 'This is the Holy test custom spell. Buffs Intellect by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 3,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 10,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38153,
  name = 'Holy Buff',
  nameSubtext = '',
  description = 'Teaches Holy Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38103,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 10,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Paladin  Protection        Spirit    ability 38104, teacher 38154, skill line 267
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38104,
  name = 'Protection Buff',
  nameSubtext = '',
  description = 'This is the Protection test custom spell. Buffs Spirit by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 4,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 10,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38154,
  name = 'Protection Buff',
  nameSubtext = '',
  description = 'Teaches Protection Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38104,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 10,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Paladin  Retribution       Strength  ability 38105, teacher 38155, skill line 184
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38105,
  name = 'Retribution Buff',
  nameSubtext = '',
  description = 'This is the Retribution test custom spell. Buffs Strength by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 0,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 10,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38155,
  name = 'Retribution Buff',
  nameSubtext = '',
  description = 'Teaches Retribution Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38105,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 10,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Hunter   Beast Mastery     Agility   ability 38106, teacher 38156, skill line 50
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38106,
  name = 'Beast Mastery Buff',
  nameSubtext = '',
  description = 'This is the Beast Mastery test custom spell. Buffs Agility by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 1,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 9,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38156,
  name = 'Beast Mastery Buff',
  nameSubtext = '',
  description = 'Teaches Beast Mastery Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38106,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 9,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Hunter   Marksmanship      Stamina   ability 38107, teacher 38157, skill line 163
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38107,
  name = 'Marksmanship Buff',
  nameSubtext = '',
  description = 'This is the Marksmanship test custom spell. Buffs Stamina by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 2,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 9,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38157,
  name = 'Marksmanship Buff',
  nameSubtext = '',
  description = 'Teaches Marksmanship Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38107,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 9,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Hunter   Survival          Intellect ability 38108, teacher 38158, skill line 51
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38108,
  name = 'Survival Buff',
  nameSubtext = '',
  description = 'This is the Survival test custom spell. Buffs Intellect by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 3,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 9,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38158,
  name = 'Survival Buff',
  nameSubtext = '',
  description = 'Teaches Survival Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38108,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 9,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Rogue    Assassination     Spirit    ability 38109, teacher 38159, skill line 253
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38109,
  name = 'Assassination Buff',
  nameSubtext = '',
  description = 'This is the Assassination test custom spell. Buffs Spirit by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 4,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 8,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38159,
  name = 'Assassination Buff',
  nameSubtext = '',
  description = 'Teaches Assassination Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38109,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 8,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Rogue    Combat            Strength  ability 38110, teacher 38160, skill line 38
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38110,
  name = 'Combat Buff',
  nameSubtext = '',
  description = 'This is the Combat test custom spell. Buffs Strength by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 0,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 8,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38160,
  name = 'Combat Buff',
  nameSubtext = '',
  description = 'Teaches Combat Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38110,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 8,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Rogue    Subtlety          Agility   ability 38111, teacher 38161, skill line 39
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38111,
  name = 'Subtlety Buff',
  nameSubtext = '',
  description = 'This is the Subtlety test custom spell. Buffs Agility by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 1,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 8,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38161,
  name = 'Subtlety Buff',
  nameSubtext = '',
  description = 'Teaches Subtlety Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38111,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 8,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Priest   Discipline        Stamina   ability 38112, teacher 38162, skill line 613
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38112,
  name = 'Discipline Buff',
  nameSubtext = '',
  description = 'This is the Discipline test custom spell. Buffs Stamina by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 2,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 6,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38162,
  name = 'Discipline Buff',
  nameSubtext = '',
  description = 'Teaches Discipline Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38112,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 6,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Priest   Holy              Intellect ability 38113, teacher 38163, skill line 56
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38113,
  name = 'Holy Buff',
  nameSubtext = '',
  description = 'This is the Holy test custom spell. Buffs Intellect by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 3,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 6,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38163,
  name = 'Holy Buff',
  nameSubtext = '',
  description = 'Teaches Holy Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38113,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 6,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Priest   Shadow Magic      Spirit    ability 38114, teacher 38164, skill line 78
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38114,
  name = 'Shadow Magic Buff',
  nameSubtext = '',
  description = 'This is the Shadow Magic test custom spell. Buffs Spirit by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 4,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 6,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38164,
  name = 'Shadow Magic Buff',
  nameSubtext = '',
  description = 'Teaches Shadow Magic Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38114,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 6,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Shaman   Elemental Combat  Strength  ability 38115, teacher 38165, skill line 375
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38115,
  name = 'Elemental Combat Buff',
  nameSubtext = '',
  description = 'This is the Elemental Combat test custom spell. Buffs Strength by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 0,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 11,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38165,
  name = 'Elemental Combat Buff',
  nameSubtext = '',
  description = 'Teaches Elemental Combat Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38115,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 11,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Shaman   Enhancement       Agility   ability 38116, teacher 38166, skill line 373
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38116,
  name = 'Enhancement Buff',
  nameSubtext = '',
  description = 'This is the Enhancement test custom spell. Buffs Agility by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 1,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 11,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38166,
  name = 'Enhancement Buff',
  nameSubtext = '',
  description = 'Teaches Enhancement Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38116,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 11,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Shaman   Restoration       Stamina   ability 38117, teacher 38167, skill line 374
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38117,
  name = 'Restoration Buff',
  nameSubtext = '',
  description = 'This is the Restoration test custom spell. Buffs Stamina by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 2,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 11,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38167,
  name = 'Restoration Buff',
  nameSubtext = '',
  description = 'Teaches Restoration Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38117,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 11,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Mage     Arcane            Intellect ability 38118, teacher 38168, skill line 237
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38118,
  name = 'Arcane Buff',
  nameSubtext = '',
  description = 'This is the Arcane test custom spell. Buffs Intellect by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 3,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 3,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38168,
  name = 'Arcane Buff',
  nameSubtext = '',
  description = 'Teaches Arcane Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38118,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 3,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Mage     Fire              Spirit    ability 38119, teacher 38169, skill line 8
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38119,
  name = 'Fire Buff',
  nameSubtext = '',
  description = 'This is the Fire test custom spell. Buffs Spirit by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 4,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 3,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38169,
  name = 'Fire Buff',
  nameSubtext = '',
  description = 'Teaches Fire Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38119,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 3,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Mage     Frost             Strength  ability 38120, teacher 38170, skill line 6
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38120,
  name = 'Frost Buff',
  nameSubtext = '',
  description = 'This is the Frost test custom spell. Buffs Strength by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 0,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 3,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38170,
  name = 'Frost Buff',
  nameSubtext = '',
  description = 'Teaches Frost Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38120,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 3,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Warlock  Affliction        Agility   ability 38121, teacher 38171, skill line 355
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38121,
  name = 'Affliction Buff',
  nameSubtext = '',
  description = 'This is the Affliction test custom spell. Buffs Agility by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 1,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 5,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38171,
  name = 'Affliction Buff',
  nameSubtext = '',
  description = 'Teaches Affliction Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38121,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 5,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Warlock  Demonology        Stamina   ability 38122, teacher 38172, skill line 354
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38122,
  name = 'Demonology Buff',
  nameSubtext = '',
  description = 'This is the Demonology test custom spell. Buffs Stamina by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 2,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 5,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38172,
  name = 'Demonology Buff',
  nameSubtext = '',
  description = 'Teaches Demonology Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38122,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 5,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Warlock  Destruction       Intellect ability 38123, teacher 38173, skill line 593
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38123,
  name = 'Destruction Buff',
  nameSubtext = '',
  description = 'This is the Destruction test custom spell. Buffs Intellect by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 3,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 5,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38173,
  name = 'Destruction Buff',
  nameSubtext = '',
  description = 'Teaches Destruction Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38123,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 5,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Druid    Balance           Spirit    ability 38124, teacher 38174, skill line 574
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38124,
  name = 'Balance Buff',
  nameSubtext = '',
  description = 'This is the Balance test custom spell. Buffs Spirit by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 4,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 7,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38174,
  name = 'Balance Buff',
  nameSubtext = '',
  description = 'Teaches Balance Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38124,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 7,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Druid    Feral Combat      Strength  ability 38125, teacher 38175, skill line 134
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38125,
  name = 'Feral Combat Buff',
  nameSubtext = '',
  description = 'This is the Feral Combat test custom spell. Buffs Strength by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 0,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 7,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38175,
  name = 'Feral Combat Buff',
  nameSubtext = '',
  description = 'Teaches Feral Combat Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38125,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 7,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- Druid    Restoration       Agility   ability 38126, teacher 38176, skill line 573
DROP TEMPORARY TABLE IF EXISTS tmp_ab;
CREATE TEMPORARY TABLE tmp_ab LIKE spell_template;
INSERT INTO tmp_ab SELECT * FROM spell_template WHERE entry = 1243;
UPDATE tmp_ab SET entry = 38126,
  name = 'Restoration Buff',
  nameSubtext = '',
  description = 'This is the Restoration test custom spell. Buffs Agility by 5 points.',
  effect1 = 6,
  effectApplyAuraName1 = 29,
  effectMiscValue1 = 1,
  effectBasePoints1 = 4,
  effect2 = 0, effectApplyAuraName2 = 0, effectBasePoints2 = 0,
  effect3 = 0, effectApplyAuraName3 = 0, effectBasePoints3 = 0,
  SpellFamilyName = 7,
  spellLevel = 2,
  baseLevel = 2,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_ab;
DROP TEMPORARY TABLE tmp_ab;

DROP TEMPORARY TABLE IF EXISTS tmp_te;
CREATE TEMPORARY TABLE tmp_te LIKE spell_template;
INSERT INTO tmp_te SELECT * FROM spell_template WHERE entry = 5243;
UPDATE tmp_te SET entry = 38176,
  name = 'Restoration Buff',
  nameSubtext = '',
  description = 'Teaches Restoration Buff.',
  effect1 = 36,
  effectTriggerSpell1 = 38126,
  effect2 = 0, effect3 = 0,
  effectApplyAuraName1 = 0, effectBasePoints1 = 0,
  SpellFamilyName = 7,
  spellLevel = 2,
  baseLevel = 2,
  DurationIndex = 0,
  RecoveryTime = 0,
  manaCost = 0;
INSERT INTO spell_template SELECT * FROM tmp_te;
DROP TEMPORARY TABLE tmp_te;

-- =====================================================================================
-- PART 2 - 0 profession test recipes at skill 5
--
-- Each craft spell is a clone of that profession's OWN lowest-tier recipe, so it
-- inherits the right RequiresSpellFocus: Cooking needs a fire, Smelting and
-- Jewelcrafting a forge, Enchanting nothing. Cloning across professions would produce
-- a recipe that can never be cast, with no useful error message.
-- =====================================================================================

-- =====================================================================================
-- PART 3 - file every spell under its skill line
--
-- This is what places a spell on a spellbook tab and a recipe in a crafting window.
-- The SERVER reads this SQL table; the CLIENT reads SkillLineAbility.dbc and never
-- sees the table. Both need the same rows, which is why patch-6.mpq carries the DBC.
-- =====================================================================================

INSERT INTO skill_line_ability
  (id, skill_id, spell_id, race_mask, class_mask, req_skill_value,
   superseded_by_spell, learn_on_get_skill, max_value, min_value, req_train_points)
VALUES
  (7212, 26, 38100, 0, 1, 0, 0, 0, 0, 0, 0),
  (7213, 256, 38101, 0, 1, 0, 0, 0, 0, 0, 0),
  (7214, 257, 38102, 0, 1, 0, 0, 0, 0, 0, 0),
  (7215, 594, 38103, 0, 2, 0, 0, 0, 0, 0, 0),
  (7216, 267, 38104, 0, 2, 0, 0, 0, 0, 0, 0),
  (7217, 184, 38105, 0, 2, 0, 0, 0, 0, 0, 0),
  (7218, 50, 38106, 0, 4, 0, 0, 0, 0, 0, 0),
  (7219, 163, 38107, 0, 4, 0, 0, 0, 0, 0, 0),
  (7220, 51, 38108, 0, 4, 0, 0, 0, 0, 0, 0),
  (7221, 253, 38109, 0, 8, 0, 0, 0, 0, 0, 0),
  (7222, 38, 38110, 0, 8, 0, 0, 0, 0, 0, 0),
  (7223, 39, 38111, 0, 8, 0, 0, 0, 0, 0, 0),
  (7224, 613, 38112, 0, 16, 0, 0, 0, 0, 0, 0),
  (7225, 56, 38113, 0, 16, 0, 0, 0, 0, 0, 0),
  (7226, 78, 38114, 0, 16, 0, 0, 0, 0, 0, 0),
  (7227, 375, 38115, 0, 64, 0, 0, 0, 0, 0, 0),
  (7228, 373, 38116, 0, 64, 0, 0, 0, 0, 0, 0),
  (7229, 374, 38117, 0, 64, 0, 0, 0, 0, 0, 0),
  (7230, 237, 38118, 0, 128, 0, 0, 0, 0, 0, 0),
  (7231, 8, 38119, 0, 128, 0, 0, 0, 0, 0, 0),
  (7232, 6, 38120, 0, 128, 0, 0, 0, 0, 0, 0),
  (7233, 355, 38121, 0, 256, 0, 0, 0, 0, 0, 0),
  (7234, 354, 38122, 0, 256, 0, 0, 0, 0, 0, 0),
  (7235, 593, 38123, 0, 256, 0, 0, 0, 0, 0, 0),
  (7236, 574, 38124, 0, 1024, 0, 0, 0, 0, 0, 0),
  (7237, 134, 38125, 0, 1024, 0, 0, 0, 0, 0, 0),
  (7238, 573, 38126, 0, 1024, 0, 0, 0, 0, 0, 0);

-- =====================================================================================
-- PART 4 - put the teachers on the trainers
-- =====================================================================================

INSERT INTO npc_trainer (entry, spell, spellcost, reqskill, reqskillvalue, reqlevel)
VALUES
  (2600200, 38150, 100, 0, 0, 2),
  (2600200, 38151, 100, 0, 0, 2),
  (2600200, 38152, 100, 0, 0, 2),
  (2600201, 38153, 100, 0, 0, 2),
  (2600201, 38154, 100, 0, 0, 2),
  (2600201, 38155, 100, 0, 0, 2),
  (2600202, 38156, 100, 0, 0, 2),
  (2600202, 38157, 100, 0, 0, 2),
  (2600202, 38158, 100, 0, 0, 2),
  (2600203, 38159, 100, 0, 0, 2),
  (2600203, 38160, 100, 0, 0, 2),
  (2600203, 38161, 100, 0, 0, 2),
  (2600204, 38162, 100, 0, 0, 2),
  (2600204, 38163, 100, 0, 0, 2),
  (2600204, 38164, 100, 0, 0, 2),
  (2600205, 38165, 100, 0, 0, 2),
  (2600205, 38166, 100, 0, 0, 2),
  (2600205, 38167, 100, 0, 0, 2),
  (2600206, 38168, 100, 0, 0, 2),
  (2600206, 38169, 100, 0, 0, 2),
  (2600206, 38170, 100, 0, 0, 2),
  (2600207, 38171, 100, 0, 0, 2),
  (2600207, 38172, 100, 0, 0, 2),
  (2600207, 38173, 100, 0, 0, 2),
  (2600208, 38174, 100, 0, 0, 2),
  (2600208, 38175, 100, 0, 0, 2),
  (2600208, 38176, 100, 0, 0, 2);

-- =====================================================================================
-- PART 5 - report. Expected: 27, 0, 0, 27, 27
-- =====================================================================================
SELECT 'class buffs' AS what, COUNT(*) AS n FROM spell_template WHERE entry BETWEEN 38100 AND 38126;
SELECT 'prof recipes' AS what, COUNT(*) AS n FROM spell_template WHERE entry BETWEEN 38200 AND 38199;
SELECT 'test items' AS what, COUNT(*) AS n FROM item_template WHERE entry IN ();
SELECT 'skill links' AS what, COUNT(*) AS n FROM skill_line_ability WHERE spell_id IN (38100,38101,38102,38103,38104,38105,38106,38107,38108,38109,38110,38111,38112,38113,38114,38115,38116,38117,38118,38119,38120,38121,38122,38123,38124,38125,38126,38150,38151,38152,38153,38154,38155,38156,38157,38158,38159,38160,38161,38162,38163,38164,38165,38166,38167,38168,38169,38170,38171,38172,38173,38174,38175,38176);
SELECT 'trainer rows' AS what, COUNT(*) AS n FROM npc_trainer WHERE spell IN (38100,38101,38102,38103,38104,38105,38106,38107,38108,38109,38110,38111,38112,38113,38114,38115,38116,38117,38118,38119,38120,38121,38122,38123,38124,38125,38126,38150,38151,38152,38153,38154,38155,38156,38157,38158,38159,38160,38161,38162,38163,38164,38165,38166,38167,38168,38169,38170,38171,38172,38173,38174,38175,38176);
