-- -------------------------------------------------------------------------------------
-- Blacksmithing weapon coverage - GENERATED by weapons.py. Do not edit by hand.
--
--   15 new weapons closing every gap in the type x tier grid: Thrown and Crossbow
--   (absent entirely), Polearm at the bottom three tiers, Fist at 50-59, 2H Mace at
--   35-49. Swords, maces, axes and daggers were already covered and are untouched.
--
-- Crossbows need Survival's wood and rope as well as metal, so the two professions
-- depend on each other. Both mats already existed.
--
-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART and a rebuilt patch-6.mpq.
-- -------------------------------------------------------------------------------------

USE tw_world;

DELETE FROM item_template      WHERE entry    IN (90120,90121,90122,90123,90124,90125,90126,90127,90128,90129,90130,90131,90132,90133,90134);
DELETE FROM spell_template     WHERE entry    IN (38300,38301,38302,38303,38304,38305,38306,38307,38308,38309,38310,38311,38312,38313,38314,38330,38331,38332,38333,38334,38335,38336,38337,38338,38339,38340,38341,38342,38343,38344);
DELETE FROM npc_trainer        WHERE spell    IN (38300,38301,38302,38303,38304,38305,38306,38307,38308,38309,38310,38311,38312,38313,38314,38330,38331,38332,38333,38334,38335,38336,38337,38338,38339,38340,38341,38342,38343,38344);
DELETE FROM skill_line_ability WHERE spell_id IN (38300,38301,38302,38303,38304,38305,38306,38307,38308,38309,38310,38311,38312,38313,38314,38330,38331,38332,38333,38334,38335,38336,38337,38338,38339,38340,38341,38342,38343,38344);

-- Copper Throwing Blade      ilvl 10  req 5    5-9 dmg / 2.0s  skill 40
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 2947;
UPDATE tmp_i SET entry=90120, name='Copper Throwing Blade', item_level=10, required_level=5,
  dmg_min1=5, dmg_max1=9, delay=2000, quality=2,
  sell_price=1200, buy_price=6000, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38300,
  name='Copper Throwing Blade',
  nameSubtext='',
  description='Forges a Copper Throwing Blade.',
  effect1=24,
  effectItemType1=90120,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=2840, reagentCount1=3,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38330, name='Copper Throwing Blade', nameSubtext='', description='Teaches you how to make a Copper Throwing Blade.',
  effect1=36, effectTriggerSpell1=38300, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Bronze Throwing Blade      ilvl 25  req 20   14-25 dmg / 2.0s  skill 110
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 2947;
UPDATE tmp_i SET entry=90121, name='Bronze Throwing Blade', item_level=25, required_level=20,
  dmg_min1=14, dmg_max1=25, delay=2000, quality=2,
  sell_price=3000, buy_price=15000, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38301,
  name='Bronze Throwing Blade',
  nameSubtext='',
  description='Forges a Bronze Throwing Blade.',
  effect1=24,
  effectItemType1=90121,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=2841, reagentCount1=4,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38331, name='Bronze Throwing Blade', nameSubtext='', description='Teaches you how to make a Bronze Throwing Blade.',
  effect1=36, effectTriggerSpell1=38301, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Iron Throwing Blade        ilvl 38  req 32   24-42 dmg / 2.0s  skill 160
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 2947;
UPDATE tmp_i SET entry=90122, name='Iron Throwing Blade', item_level=38, required_level=32,
  dmg_min1=24, dmg_max1=42, delay=2000, quality=2,
  sell_price=4560, buy_price=22800, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38302,
  name='Iron Throwing Blade',
  nameSubtext='',
  description='Forges a Iron Throwing Blade.',
  effect1=24,
  effectItemType1=90122,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=3575, reagentCount1=4,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38332, name='Iron Throwing Blade', nameSubtext='', description='Teaches you how to make a Iron Throwing Blade.',
  effect1=36, effectTriggerSpell1=38302, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Mithril Throwing Blade     ilvl 52  req 46   38-66 dmg / 2.0s  skill 215
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 2947;
UPDATE tmp_i SET entry=90123, name='Mithril Throwing Blade', item_level=52, required_level=46,
  dmg_min1=38, dmg_max1=66, delay=2000, quality=2,
  sell_price=6240, buy_price=31200, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38303,
  name='Mithril Throwing Blade',
  nameSubtext='',
  description='Forges a Mithril Throwing Blade.',
  effect1=24,
  effectItemType1=90123,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=3860, reagentCount1=5,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38333, name='Mithril Throwing Blade', nameSubtext='', description='Teaches you how to make a Mithril Throwing Blade.',
  effect1=36, effectTriggerSpell1=38303, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Thorium Throwing Blade     ilvl 63  req 57   52-88 dmg / 2.0s  skill 265
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 2947;
UPDATE tmp_i SET entry=90124, name='Thorium Throwing Blade', item_level=63, required_level=57,
  dmg_min1=52, dmg_max1=88, delay=2000, quality=2,
  sell_price=7560, buy_price=37800, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38304,
  name='Thorium Throwing Blade',
  nameSubtext='',
  description='Forges a Thorium Throwing Blade.',
  effect1=24,
  effectItemType1=90124,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=12359, reagentCount1=5,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38334, name='Thorium Throwing Blade', nameSubtext='', description='Teaches you how to make a Thorium Throwing Blade.',
  effect1=36, effectTriggerSpell1=38304, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Copper Crossbow            ilvl 10  req 5    7-13 dmg / 2.8s  skill 40
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 15807;
UPDATE tmp_i SET entry=90125, name='Copper Crossbow', item_level=10, required_level=5,
  dmg_min1=7, dmg_max1=13, delay=2800, quality=2,
  sell_price=1200, buy_price=6000, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38305,
  name='Copper Crossbow',
  nameSubtext='',
  description='Forges a Copper Crossbow.',
  effect1=24,
  effectItemType1=90125,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=2840, reagentCount1=6,
  reagent2=42149, reagentCount2=2,
  reagent3=50231, reagentCount3=1,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38335, name='Copper Crossbow', nameSubtext='', description='Teaches you how to make a Copper Crossbow.',
  effect1=36, effectTriggerSpell1=38305, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Bronze Crossbow            ilvl 25  req 20   18-34 dmg / 2.8s  skill 110
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 15807;
UPDATE tmp_i SET entry=90126, name='Bronze Crossbow', item_level=25, required_level=20,
  dmg_min1=18, dmg_max1=34, delay=2800, quality=2,
  sell_price=3000, buy_price=15000, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38306,
  name='Bronze Crossbow',
  nameSubtext='',
  description='Forges a Bronze Crossbow.',
  effect1=24,
  effectItemType1=90126,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=2841, reagentCount1=8,
  reagent2=42150, reagentCount2=2,
  reagent3=50231, reagentCount3=2,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38336, name='Bronze Crossbow', nameSubtext='', description='Teaches you how to make a Bronze Crossbow.',
  effect1=36, effectTriggerSpell1=38306, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Iron Crossbow              ilvl 38  req 32   31-57 dmg / 2.8s  skill 160
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 15807;
UPDATE tmp_i SET entry=90127, name='Iron Crossbow', item_level=38, required_level=32,
  dmg_min1=31, dmg_max1=57, delay=2800, quality=2,
  sell_price=4560, buy_price=22800, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38307,
  name='Iron Crossbow',
  nameSubtext='',
  description='Forges a Iron Crossbow.',
  effect1=24,
  effectItemType1=90127,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=3575, reagentCount1=8,
  reagent2=42151, reagentCount2=2,
  reagent3=50231, reagentCount3=2,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38337, name='Iron Crossbow', nameSubtext='', description='Teaches you how to make a Iron Crossbow.',
  effect1=36, effectTriggerSpell1=38307, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Mithril Crossbow           ilvl 52  req 46   48-89 dmg / 2.8s  skill 215
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 15807;
UPDATE tmp_i SET entry=90128, name='Mithril Crossbow', item_level=52, required_level=46,
  dmg_min1=48, dmg_max1=89, delay=2800, quality=2,
  sell_price=6240, buy_price=31200, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38308,
  name='Mithril Crossbow',
  nameSubtext='',
  description='Forges a Mithril Crossbow.',
  effect1=24,
  effectItemType1=90128,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=3860, reagentCount1=10,
  reagent2=42152, reagentCount2=2,
  reagent3=42006, reagentCount3=3,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38338, name='Mithril Crossbow', nameSubtext='', description='Teaches you how to make a Mithril Crossbow.',
  effect1=36, effectTriggerSpell1=38308, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Thorium Crossbow           ilvl 63  req 57   64-119 dmg / 2.8s  skill 265
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 15807;
UPDATE tmp_i SET entry=90129, name='Thorium Crossbow', item_level=63, required_level=57,
  dmg_min1=64, dmg_max1=119, delay=2800, quality=2,
  sell_price=7560, buy_price=37800, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38309,
  name='Thorium Crossbow',
  nameSubtext='',
  description='Forges a Thorium Crossbow.',
  effect1=24,
  effectItemType1=90129,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=12359, reagentCount1=10,
  reagent2=42153, reagentCount2=2,
  reagent3=42006, reagentCount3=3,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38339, name='Thorium Crossbow', nameSubtext='', description='Teaches you how to make a Thorium Crossbow.',
  effect1=36, effectTriggerSpell1=38309, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Copper Pike                ilvl 10  req 5    12-19 dmg / 2.7s  skill 40
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 7959;
UPDATE tmp_i SET entry=90130, name='Copper Pike', item_level=10, required_level=5,
  dmg_min1=12, dmg_max1=19, delay=2700, quality=2,
  sell_price=1200, buy_price=6000, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38310,
  name='Copper Pike',
  nameSubtext='',
  description='Forges a Copper Pike.',
  effect1=24,
  effectItemType1=90130,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=2840, reagentCount1=8,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38340, name='Copper Pike', nameSubtext='', description='Teaches you how to make a Copper Pike.',
  effect1=36, effectTriggerSpell1=38310, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Bronze Pike                ilvl 25  req 20   30-46 dmg / 2.7s  skill 110
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 7959;
UPDATE tmp_i SET entry=90131, name='Bronze Pike', item_level=25, required_level=20,
  dmg_min1=30, dmg_max1=46, delay=2700, quality=2,
  sell_price=3000, buy_price=15000, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38311,
  name='Bronze Pike',
  nameSubtext='',
  description='Forges a Bronze Pike.',
  effect1=24,
  effectItemType1=90131,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=2841, reagentCount1=10,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38341, name='Bronze Pike', nameSubtext='', description='Teaches you how to make a Bronze Pike.',
  effect1=36, effectTriggerSpell1=38311, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Iron Pike                  ilvl 38  req 32   50-76 dmg / 2.7s  skill 160
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 7959;
UPDATE tmp_i SET entry=90132, name='Iron Pike', item_level=38, required_level=32,
  dmg_min1=50, dmg_max1=76, delay=2700, quality=2,
  sell_price=4560, buy_price=22800, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38312,
  name='Iron Pike',
  nameSubtext='',
  description='Forges a Iron Pike.',
  effect1=24,
  effectItemType1=90132,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=3575, reagentCount1=10,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38342, name='Iron Pike', nameSubtext='', description='Teaches you how to make a Iron Pike.',
  effect1=36, effectTriggerSpell1=38312, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Mithril Claw               ilvl 52  req 46   44-82 dmg / 1.9s  skill 215
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 65013;
UPDATE tmp_i SET entry=90133, name='Mithril Claw', item_level=52, required_level=46,
  dmg_min1=44, dmg_max1=82, delay=1900, quality=2,
  sell_price=6240, buy_price=31200, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38313,
  name='Mithril Claw',
  nameSubtext='',
  description='Forges a Mithril Claw.',
  effect1=24,
  effectItemType1=90133,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=3860, reagentCount1=12,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38343, name='Mithril Claw', nameSubtext='', description='Teaches you how to make a Mithril Claw.',
  effect1=36, effectTriggerSpell1=38313, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Iron Maul                  ilvl 38  req 32   54-82 dmg / 3.2s  skill 160
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE item_template;
INSERT INTO tmp_i SELECT * FROM item_template WHERE entry = 1990;
UPDATE tmp_i SET entry=90134, name='Iron Maul', item_level=38, required_level=32,
  dmg_min1=54, dmg_max1=82, delay=3200, quality=2,
  sell_price=4560, buy_price=22800, random_property=0;
INSERT INTO item_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry=38314,
  name='Iron Maul',
  nameSubtext='',
  description='Forges a Iron Maul.',
  effect1=24,
  effectItemType1=90134,
  effect2=0, effect3=0,
  effectTriggerSpell1=0,
  reagent1=3575, reagentCount1=10,
  reagent2=0, reagentCount2=0,
  reagent3=0, reagentCount3=0,
  reagent4=0, reagentCount4=0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry=38344, name='Iron Maul', nameSubtext='', description='Teaches you how to make a Iron Maul.',
  effect1=36, effectTriggerSpell1=38314, effect2=0, effect3=0,
  effectImplicitTargetA1=0;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- File every recipe under Blacksmithing so it appears in the crafting window.
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, race_mask, class_mask, req_skill_value,
   superseded_by_spell, learn_on_get_skill, max_value, min_value, req_train_points)
VALUES
  (7260, 164, 38300, 0, 0, 40, 0, 0, 90, 55, 0),
  (7261, 164, 38301, 0, 0, 110, 0, 0, 160, 125, 0),
  (7262, 164, 38302, 0, 0, 160, 0, 0, 210, 175, 0),
  (7263, 164, 38303, 0, 0, 215, 0, 0, 265, 230, 0),
  (7264, 164, 38304, 0, 0, 265, 0, 0, 315, 280, 0),
  (7265, 164, 38305, 0, 0, 40, 0, 0, 90, 55, 0),
  (7266, 164, 38306, 0, 0, 110, 0, 0, 160, 125, 0),
  (7267, 164, 38307, 0, 0, 160, 0, 0, 210, 175, 0),
  (7268, 164, 38308, 0, 0, 215, 0, 0, 265, 230, 0),
  (7269, 164, 38309, 0, 0, 265, 0, 0, 315, 280, 0),
  (7270, 164, 38310, 0, 0, 40, 0, 0, 90, 55, 0),
  (7271, 164, 38311, 0, 0, 110, 0, 0, 160, 125, 0),
  (7272, 164, 38312, 0, 0, 160, 0, 0, 210, 175, 0),
  (7273, 164, 38313, 0, 0, 215, 0, 0, 265, 230, 0),
  (7274, 164, 38314, 0, 0, 160, 0, 0, 210, 175, 0);

-- Sell the plans at the Blacksmithing Master.
INSERT INTO npc_trainer (entry, spell, spellcost, reqskill, reqskillvalue, reqlevel)
VALUES
  (2600300, 38330, 2000, 164, 40, 0),
  (2600300, 38331, 5000, 164, 110, 0),
  (2600300, 38332, 7600, 164, 160, 0),
  (2600300, 38333, 10400, 164, 215, 0),
  (2600300, 38334, 12600, 164, 265, 0),
  (2600300, 38335, 2000, 164, 40, 0),
  (2600300, 38336, 5000, 164, 110, 0),
  (2600300, 38337, 7600, 164, 160, 0),
  (2600300, 38338, 10400, 164, 215, 0),
  (2600300, 38339, 12600, 164, 265, 0),
  (2600300, 38340, 2000, 164, 40, 0),
  (2600300, 38341, 5000, 164, 110, 0),
  (2600300, 38342, 7600, 164, 160, 0),
  (2600300, 38343, 10400, 164, 215, 0),
  (2600300, 38344, 7600, 164, 160, 0);


-- -------------------------------------------------------------------------------------
-- Icons. spell_template HAS a spellIconId column, so keep it in step with the
-- client DBC even though the CLIENT is what actually renders the icon - a
-- disagreement here would be invisible until something server-side reads it.
--
-- Every Blacksmithing craft spell in this database, the real ones included, uses
-- icon 140 (Spell_Shadow_SealOfKings) - a shadowy face. Cloning inherited it.
-- -------------------------------------------------------------------------------------
UPDATE spell_template SET spellIconId = 1505 WHERE entry IN (38300, 38330);
UPDATE spell_template SET spellIconId = 1505 WHERE entry IN (38301, 38331);
UPDATE spell_template SET spellIconId = 1505 WHERE entry IN (38302, 38332);
UPDATE spell_template SET spellIconId = 1505 WHERE entry IN (38303, 38333);
UPDATE spell_template SET spellIconId = 1505 WHERE entry IN (38304, 38334);
UPDATE spell_template SET spellIconId = 269 WHERE entry IN (38305, 38335);
UPDATE spell_template SET spellIconId = 269 WHERE entry IN (38306, 38336);
UPDATE spell_template SET spellIconId = 269 WHERE entry IN (38307, 38337);
UPDATE spell_template SET spellIconId = 269 WHERE entry IN (38308, 38338);
UPDATE spell_template SET spellIconId = 269 WHERE entry IN (38309, 38339);
UPDATE spell_template SET spellIconId = 370 WHERE entry IN (38310, 38340);
UPDATE spell_template SET spellIconId = 370 WHERE entry IN (38311, 38341);
UPDATE spell_template SET spellIconId = 370 WHERE entry IN (38312, 38342);
UPDATE spell_template SET spellIconId = 756 WHERE entry IN (38313, 38343);
UPDATE spell_template SET spellIconId = 367 WHERE entry IN (38314, 38344);

SELECT 'weapons' AS what, COUNT(*) AS n FROM item_template WHERE entry IN (90120,90121,90122,90123,90124,90125,90126,90127,90128,90129,90130,90131,90132,90133,90134);
SELECT 'recipes' AS what, COUNT(*) AS n FROM skill_line_ability WHERE spell_id IN (38300,38301,38302,38303,38304,38305,38306,38307,38308,38309,38310,38311,38312,38313,38314);
SELECT it.name, it.item_level AS ilvl, it.dmg_min1 AS dmin, it.dmg_max1 AS dmax, sla.req_skill_value AS skill
FROM item_template it JOIN spell_template s ON s.effectItemType1=it.entry
JOIN skill_line_ability sla ON sla.spell_id=s.entry
WHERE it.entry IN (90120,90121,90122,90123,90124,90125,90126,90127,90128,90129,90130,90131,90132,90133,90134) ORDER BY it.item_level;
