-- -------------------------------------------------------------------------------------
-- Blacksmithing shields - GENERATED by shields.py. Do not edit by hand.
--
--   18 shields, three per tier: all-metal (str/sta), leather+metal (int/spi),
--   and wood+metal (sta/agi). Blacksmithing previously made FOUR shields in total,
--   two of them item level 70, so nothing was craftable between level 18 and 60.
--
--   Armour and block are inherited by cloning a real shield of each item level, so
--   they sit on the existing curve rather than being invented.
--
-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART and a rebuilt patch-6.mpq.
-- -------------------------------------------------------------------------------------

USE tw_world;

DELETE FROM item_template      WHERE entry    IN (90140,90141,90142,90143,90144,90145,90146,90147,90148,90149,90150,90151,90152,90153,90154,90155,90156,90157);
DELETE FROM spell_template     WHERE entry    IN (38500,38501,38502,38503,38504,38505,38506,38507,38508,38509,38510,38511,38512,38513,38514,38515,38516,38517,38530,38531,38532,38533,38534,38535,38536,38537,38538,38539,38540,38541,38542,38543,38544,38545,38546,38547);
DELETE FROM npc_trainer        WHERE spell    IN (38500,38501,38502,38503,38504,38505,38506,38507,38508,38509,38510,38511,38512,38513,38514,38515,38516,38517,38530,38531,38532,38533,38534,38535,38536,38537,38538,38539,38540,38541,38542,38543,38544,38545,38546,38547);
DELETE FROM skill_line_ability WHERE spell_id IN (38500,38501,38502,38503,38504,38505,38506,38507,38508,38509,38510,38511,38512,38513,38514,38515,38516,38517,38530,38531,38532,38533,38534,38535,38536,38537,38538,38539,38540,38541,38542,38543,38544,38545,38546,38547);

-- Copper Bulwark           metal    skill 45    8 x item 2840
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 61370;
UPDATE tmp_s SET entry = 90140,
  name = 'Copper Bulwark',
  Quality = 2,
  random_property = 0,
  required_level = 5,
  display_id = 18655,
  stat_type1 = 4, stat_value1 = 2,
  stat_type2 = 7, stat_value2 = 1,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38500,
  name = 'Copper Bulwark',
  nameSubtext = '',
  description = 'Forges a Copper Bulwark.',
  effect1 = 24,
  effectItemType1 = 90140,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1955,
  reagent1 = 2840, reagentCount1 = 8,
  reagent2 = 0, reagentCount2 = 0,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38530, name = 'Copper Bulwark', nameSubtext = '', description = 'Teaches you how to make a Copper Bulwark.',
  effect1 = 36, effectTriggerSpell1 = 38500, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1955;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Bronze Bulwark           metal    skill 115   10 x item 2841
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 4820;
UPDATE tmp_s SET entry = 90141,
  name = 'Bronze Bulwark',
  Quality = 2,
  random_property = 0,
  required_level = 20,
  display_id = 18694,
  stat_type1 = 4, stat_value1 = 3,
  stat_type2 = 7, stat_value2 = 2,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38501,
  name = 'Bronze Bulwark',
  nameSubtext = '',
  description = 'Forges a Bronze Bulwark.',
  effect1 = 24,
  effectItemType1 = 90141,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1955,
  reagent1 = 2841, reagentCount1 = 10,
  reagent2 = 0, reagentCount2 = 0,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38531, name = 'Bronze Bulwark', nameSubtext = '', description = 'Teaches you how to make a Bronze Bulwark.',
  effect1 = 36, effectTriggerSpell1 = 38501, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1955;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Iron Bulwark             metal    skill 165   12 x item 3575
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 6828;
UPDATE tmp_s SET entry = 90142,
  name = 'Iron Bulwark',
  Quality = 2,
  random_property = 0,
  required_level = 33,
  display_id = 26060,
  stat_type1 = 4, stat_value1 = 4,
  stat_type2 = 7, stat_value2 = 3,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38502,
  name = 'Iron Bulwark',
  nameSubtext = '',
  description = 'Forges a Iron Bulwark.',
  effect1 = 24,
  effectItemType1 = 90142,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1955,
  reagent1 = 3575, reagentCount1 = 12,
  reagent2 = 0, reagentCount2 = 0,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38532, name = 'Iron Bulwark', nameSubtext = '', description = 'Teaches you how to make a Iron Bulwark.',
  effect1 = 36, effectTriggerSpell1 = 38502, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1955;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Steel Bulwark            metal    skill 190   14 x item 3859
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 8135;
UPDATE tmp_s SET entry = 90143,
  name = 'Steel Bulwark',
  Quality = 2,
  random_property = 0,
  required_level = 41,
  display_id = 26085,
  stat_type1 = 4, stat_value1 = 5,
  stat_type2 = 7, stat_value2 = 4,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38503,
  name = 'Steel Bulwark',
  nameSubtext = '',
  description = 'Forges a Steel Bulwark.',
  effect1 = 24,
  effectItemType1 = 90143,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1955,
  reagent1 = 3859, reagentCount1 = 14,
  reagent2 = 0, reagentCount2 = 0,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38533, name = 'Steel Bulwark', nameSubtext = '', description = 'Teaches you how to make a Steel Bulwark.',
  effect1 = 36, effectTriggerSpell1 = 38503, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1955;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Mithril Bulwark          metal    skill 220   16 x item 3860
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 9974;
UPDATE tmp_s SET entry = 90144,
  name = 'Mithril Bulwark',
  Quality = 2,
  random_property = 0,
  required_level = 47,
  display_id = 26844,
  stat_type1 = 4, stat_value1 = 6,
  stat_type2 = 7, stat_value2 = 5,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38504,
  name = 'Mithril Bulwark',
  nameSubtext = '',
  description = 'Forges a Mithril Bulwark.',
  effect1 = 24,
  effectItemType1 = 90144,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1955,
  reagent1 = 3860, reagentCount1 = 16,
  reagent2 = 0, reagentCount2 = 0,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38534, name = 'Mithril Bulwark', nameSubtext = '', description = 'Teaches you how to make a Mithril Bulwark.',
  effect1 = 36, effectTriggerSpell1 = 38504, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1955;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Thorium Bulwark          metal    skill 270   18 x item 12359
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 10366;
UPDATE tmp_s SET entry = 90145,
  name = 'Thorium Bulwark',
  Quality = 2,
  random_property = 0,
  required_level = 58,
  display_id = 26911,
  stat_type1 = 4, stat_value1 = 7,
  stat_type2 = 7, stat_value2 = 6,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38505,
  name = 'Thorium Bulwark',
  nameSubtext = '',
  description = 'Forges a Thorium Bulwark.',
  effect1 = 24,
  effectItemType1 = 90145,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1955,
  reagent1 = 12359, reagentCount1 = 18,
  reagent2 = 0, reagentCount2 = 0,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38535, name = 'Thorium Bulwark', nameSubtext = '', description = 'Teaches you how to make a Thorium Bulwark.',
  effect1 = 36, effectTriggerSpell1 = 38505, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1955;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Copper Wardingshield     leather  skill 45    5 x item 2840 + 4 x item 2318
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 61370;
UPDATE tmp_s SET entry = 90146,
  name = 'Copper Wardingshield',
  Quality = 2,
  random_property = 0,
  required_level = 5,
  display_id = 27782,
  stat_type1 = 5, stat_value1 = 2,
  stat_type2 = 6, stat_value2 = 1,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38506,
  name = 'Copper Wardingshield',
  nameSubtext = '',
  description = 'Forges a Copper Wardingshield.',
  effect1 = 24,
  effectItemType1 = 90146,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1953,
  reagent1 = 2840, reagentCount1 = 5,
  reagent2 = 2318, reagentCount2 = 4,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38536, name = 'Copper Wardingshield', nameSubtext = '', description = 'Teaches you how to make a Copper Wardingshield.',
  effect1 = 36, effectTriggerSpell1 = 38506, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1953;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Bronze Wardingshield     leather  skill 115   7 x item 2841 + 5 x item 2319
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 4820;
UPDATE tmp_s SET entry = 90147,
  name = 'Bronze Wardingshield',
  Quality = 2,
  random_property = 0,
  required_level = 20,
  display_id = 3445,
  stat_type1 = 5, stat_value1 = 3,
  stat_type2 = 6, stat_value2 = 2,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38507,
  name = 'Bronze Wardingshield',
  nameSubtext = '',
  description = 'Forges a Bronze Wardingshield.',
  effect1 = 24,
  effectItemType1 = 90147,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1953,
  reagent1 = 2841, reagentCount1 = 7,
  reagent2 = 2319, reagentCount2 = 5,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38537, name = 'Bronze Wardingshield', nameSubtext = '', description = 'Teaches you how to make a Bronze Wardingshield.',
  effect1 = 36, effectTriggerSpell1 = 38507, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1953;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Iron Wardingshield       leather  skill 165   9 x item 3575 + 6 x item 4234
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 6828;
UPDATE tmp_s SET entry = 90148,
  name = 'Iron Wardingshield',
  Quality = 2,
  random_property = 0,
  required_level = 33,
  display_id = 18488,
  stat_type1 = 5, stat_value1 = 4,
  stat_type2 = 6, stat_value2 = 3,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38508,
  name = 'Iron Wardingshield',
  nameSubtext = '',
  description = 'Forges a Iron Wardingshield.',
  effect1 = 24,
  effectItemType1 = 90148,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1953,
  reagent1 = 3575, reagentCount1 = 9,
  reagent2 = 4234, reagentCount2 = 6,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38538, name = 'Iron Wardingshield', nameSubtext = '', description = 'Teaches you how to make a Iron Wardingshield.',
  effect1 = 36, effectTriggerSpell1 = 38508, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1953;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Steel Wardingshield      leather  skill 190   11 x item 3859 + 7 x item 4304
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 8135;
UPDATE tmp_s SET entry = 90149,
  name = 'Steel Wardingshield',
  Quality = 2,
  random_property = 0,
  required_level = 41,
  display_id = 18451,
  stat_type1 = 5, stat_value1 = 5,
  stat_type2 = 6, stat_value2 = 4,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38509,
  name = 'Steel Wardingshield',
  nameSubtext = '',
  description = 'Forges a Steel Wardingshield.',
  effect1 = 24,
  effectItemType1 = 90149,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1953,
  reagent1 = 3859, reagentCount1 = 11,
  reagent2 = 4304, reagentCount2 = 7,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38539, name = 'Steel Wardingshield', nameSubtext = '', description = 'Teaches you how to make a Steel Wardingshield.',
  effect1 = 36, effectTriggerSpell1 = 38509, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1953;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Mithril Wardingshield    leather  skill 220   13 x item 3860 + 8 x item 8170
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 9974;
UPDATE tmp_s SET entry = 90150,
  name = 'Mithril Wardingshield',
  Quality = 2,
  random_property = 0,
  required_level = 47,
  display_id = 23835,
  stat_type1 = 5, stat_value1 = 6,
  stat_type2 = 6, stat_value2 = 5,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38510,
  name = 'Mithril Wardingshield',
  nameSubtext = '',
  description = 'Forges a Mithril Wardingshield.',
  effect1 = 24,
  effectItemType1 = 90150,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1953,
  reagent1 = 3860, reagentCount1 = 13,
  reagent2 = 8170, reagentCount2 = 8,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38540, name = 'Mithril Wardingshield', nameSubtext = '', description = 'Teaches you how to make a Mithril Wardingshield.',
  effect1 = 36, effectTriggerSpell1 = 38510, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1953;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Thorium Wardingshield    leather  skill 270   15 x item 12359 + 9 x item 8171
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 10366;
UPDATE tmp_s SET entry = 90151,
  name = 'Thorium Wardingshield',
  Quality = 2,
  random_property = 0,
  required_level = 58,
  display_id = 27803,
  stat_type1 = 5, stat_value1 = 7,
  stat_type2 = 6, stat_value2 = 6,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38511,
  name = 'Thorium Wardingshield',
  nameSubtext = '',
  description = 'Forges a Thorium Wardingshield.',
  effect1 = 24,
  effectItemType1 = 90151,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1953,
  reagent1 = 12359, reagentCount1 = 15,
  reagent2 = 8171, reagentCount2 = 9,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38541, name = 'Thorium Wardingshield', nameSubtext = '', description = 'Teaches you how to make a Thorium Wardingshield.',
  effect1 = 36, effectTriggerSpell1 = 38511, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1953;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Copper Roundshield       wood     skill 45    5 x item 2840 + 2 x item 42149
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 61370;
UPDATE tmp_s SET entry = 90152,
  name = 'Copper Roundshield',
  Quality = 2,
  random_property = 0,
  required_level = 5,
  display_id = 2552,
  stat_type1 = 7, stat_value1 = 2,
  stat_type2 = 3, stat_value2 = 1,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38512,
  name = 'Copper Roundshield',
  nameSubtext = '',
  description = 'Forges a Copper Roundshield.',
  effect1 = 24,
  effectItemType1 = 90152,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1959,
  reagent1 = 2840, reagentCount1 = 5,
  reagent2 = 42149, reagentCount2 = 2,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38542, name = 'Copper Roundshield', nameSubtext = '', description = 'Teaches you how to make a Copper Roundshield.',
  effect1 = 36, effectTriggerSpell1 = 38512, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1959;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Bronze Roundshield       wood     skill 115   7 x item 2841 + 3 x item 42150
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 4820;
UPDATE tmp_s SET entry = 90153,
  name = 'Bronze Roundshield',
  Quality = 2,
  random_property = 0,
  required_level = 20,
  display_id = 20826,
  stat_type1 = 7, stat_value1 = 3,
  stat_type2 = 3, stat_value2 = 2,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38513,
  name = 'Bronze Roundshield',
  nameSubtext = '',
  description = 'Forges a Bronze Roundshield.',
  effect1 = 24,
  effectItemType1 = 90153,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1959,
  reagent1 = 2841, reagentCount1 = 7,
  reagent2 = 42150, reagentCount2 = 3,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38543, name = 'Bronze Roundshield', nameSubtext = '', description = 'Teaches you how to make a Bronze Roundshield.',
  effect1 = 36, effectTriggerSpell1 = 38513, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1959;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Iron Roundshield         wood     skill 165   9 x item 3575 + 4 x item 42151
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 6828;
UPDATE tmp_s SET entry = 90154,
  name = 'Iron Roundshield',
  Quality = 2,
  random_property = 0,
  required_level = 33,
  display_id = 18824,
  stat_type1 = 7, stat_value1 = 4,
  stat_type2 = 3, stat_value2 = 3,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38514,
  name = 'Iron Roundshield',
  nameSubtext = '',
  description = 'Forges a Iron Roundshield.',
  effect1 = 24,
  effectItemType1 = 90154,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1959,
  reagent1 = 3575, reagentCount1 = 9,
  reagent2 = 42151, reagentCount2 = 4,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38544, name = 'Iron Roundshield', nameSubtext = '', description = 'Teaches you how to make a Iron Roundshield.',
  effect1 = 36, effectTriggerSpell1 = 38514, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1959;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Steel Roundshield        wood     skill 190   11 x item 3859 + 5 x item 42152
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 8135;
UPDATE tmp_s SET entry = 90155,
  name = 'Steel Roundshield',
  Quality = 2,
  random_property = 0,
  required_level = 41,
  display_id = 11925,
  stat_type1 = 7, stat_value1 = 5,
  stat_type2 = 3, stat_value2 = 4,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38515,
  name = 'Steel Roundshield',
  nameSubtext = '',
  description = 'Forges a Steel Roundshield.',
  effect1 = 24,
  effectItemType1 = 90155,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1959,
  reagent1 = 3859, reagentCount1 = 11,
  reagent2 = 42152, reagentCount2 = 5,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38545, name = 'Steel Roundshield', nameSubtext = '', description = 'Teaches you how to make a Steel Roundshield.',
  effect1 = 36, effectTriggerSpell1 = 38515, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1959;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Mithril Roundshield      wood     skill 220   13 x item 3860 + 6 x item 42153
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 9974;
UPDATE tmp_s SET entry = 90156,
  name = 'Mithril Roundshield',
  Quality = 2,
  random_property = 0,
  required_level = 47,
  display_id = 26176,
  stat_type1 = 7, stat_value1 = 6,
  stat_type2 = 3, stat_value2 = 5,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38516,
  name = 'Mithril Roundshield',
  nameSubtext = '',
  description = 'Forges a Mithril Roundshield.',
  effect1 = 24,
  effectItemType1 = 90156,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1959,
  reagent1 = 3860, reagentCount1 = 13,
  reagent2 = 42153, reagentCount2 = 6,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38546, name = 'Mithril Roundshield', nameSubtext = '', description = 'Teaches you how to make a Mithril Roundshield.',
  effect1 = 36, effectTriggerSpell1 = 38516, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1959;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- Thorium Roundshield      wood     skill 270   15 x item 12359 + 7 x item 42153
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE item_template;
INSERT INTO tmp_s SELECT * FROM item_template WHERE entry = 10366;
UPDATE tmp_s SET entry = 90157,
  name = 'Thorium Roundshield',
  Quality = 2,
  random_property = 0,
  required_level = 58,
  display_id = 26324,
  stat_type1 = 7, stat_value1 = 7,
  stat_type2 = 3, stat_value2 = 6,
  stat_type3 = 0, stat_value3 = 0,
  stat_type4 = 0, stat_value4 = 0,
  stat_type5 = 0, stat_value5 = 0;
INSERT INTO item_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
DROP TEMPORARY TABLE IF EXISTS tmp_c;
CREATE TEMPORARY TABLE tmp_c LIKE spell_template;
INSERT INTO tmp_c SELECT * FROM spell_template WHERE entry = 2660;
UPDATE tmp_c SET entry = 38517,
  name = 'Thorium Roundshield',
  nameSubtext = '',
  description = 'Forges a Thorium Roundshield.',
  effect1 = 24,
  effectItemType1 = 90157,
  effect2 = 0, effect3 = 0,
  effectTriggerSpell1 = 0,
  spellIconId = 1959,
  reagent1 = 12359, reagentCount1 = 15,
  reagent2 = 42153, reagentCount2 = 7,
  reagent3 = 0, reagentCount3 = 0,
  reagent4 = 0, reagentCount4 = 0;
INSERT INTO spell_template SELECT * FROM tmp_c;
DROP TEMPORARY TABLE tmp_c;
DROP TEMPORARY TABLE IF EXISTS tmp_t;
CREATE TEMPORARY TABLE tmp_t LIKE spell_template;
INSERT INTO tmp_t SELECT * FROM spell_template WHERE entry = 2754;
UPDATE tmp_t SET entry = 38547, name = 'Thorium Roundshield', nameSubtext = '', description = 'Teaches you how to make a Thorium Roundshield.',
  effect1 = 36, effectTriggerSpell1 = 38517, effect2 = 0, effect3 = 0,
  effectImplicitTargetA1 = 0, spellIconId = 1959;
INSERT INTO spell_template SELECT * FROM tmp_t;
DROP TEMPORARY TABLE tmp_t;

-- File each under Blacksmithing so it appears in the crafting window.
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, race_mask, class_mask, req_skill_value,
   superseded_by_spell, learn_on_get_skill, max_value, min_value, req_train_points)
VALUES
  (7300, 164, 38500, 0, 0, 45, 0, 0, 95, 60, 0),
  (7301, 164, 38501, 0, 0, 115, 0, 0, 165, 130, 0),
  (7302, 164, 38502, 0, 0, 165, 0, 0, 215, 180, 0),
  (7303, 164, 38503, 0, 0, 190, 0, 0, 240, 205, 0),
  (7304, 164, 38504, 0, 0, 220, 0, 0, 270, 235, 0),
  (7305, 164, 38505, 0, 0, 270, 0, 0, 320, 285, 0),
  (7306, 164, 38506, 0, 0, 45, 0, 0, 95, 60, 0),
  (7307, 164, 38507, 0, 0, 115, 0, 0, 165, 130, 0),
  (7308, 164, 38508, 0, 0, 165, 0, 0, 215, 180, 0),
  (7309, 164, 38509, 0, 0, 190, 0, 0, 240, 205, 0),
  (7310, 164, 38510, 0, 0, 220, 0, 0, 270, 235, 0),
  (7311, 164, 38511, 0, 0, 270, 0, 0, 320, 285, 0),
  (7312, 164, 38512, 0, 0, 45, 0, 0, 95, 60, 0),
  (7313, 164, 38513, 0, 0, 115, 0, 0, 165, 130, 0),
  (7314, 164, 38514, 0, 0, 165, 0, 0, 215, 180, 0),
  (7315, 164, 38515, 0, 0, 190, 0, 0, 240, 205, 0),
  (7316, 164, 38516, 0, 0, 220, 0, 0, 270, 235, 0),
  (7317, 164, 38517, 0, 0, 270, 0, 0, 320, 285, 0);

-- Sell the plans at the Blacksmithing Master.
INSERT INTO npc_trainer (entry, spell, spellcost, reqskill, reqskillvalue, reqlevel)
VALUES
  (2600300, 38530, 4050, 164, 45, 0),
  (2600300, 38531, 10350, 164, 115, 0),
  (2600300, 38532, 14850, 164, 165, 0),
  (2600300, 38533, 17100, 164, 190, 0),
  (2600300, 38534, 19800, 164, 220, 0),
  (2600300, 38535, 24300, 164, 270, 0),
  (2600300, 38536, 4050, 164, 45, 0),
  (2600300, 38537, 10350, 164, 115, 0),
  (2600300, 38538, 14850, 164, 165, 0),
  (2600300, 38539, 17100, 164, 190, 0),
  (2600300, 38540, 19800, 164, 220, 0),
  (2600300, 38541, 24300, 164, 270, 0),
  (2600300, 38542, 4050, 164, 45, 0),
  (2600300, 38543, 10350, 164, 115, 0),
  (2600300, 38544, 14850, 164, 165, 0),
  (2600300, 38545, 17100, 164, 190, 0),
  (2600300, 38546, 19800, 164, 220, 0),
  (2600300, 38547, 24300, 164, 270, 0);

SELECT it.name, it.item_level AS ilvl, it.armor, it.block,
       it.stat_type1, it.stat_value1, it.stat_type2, it.stat_value2,
       sla.req_skill_value AS skill
FROM item_template it JOIN spell_template s ON s.effectItemType1 = it.entry
JOIN skill_line_ability sla ON sla.spell_id = s.entry
WHERE it.entry IN (90140,90141,90142,90143,90144,90145,90146,90147,90148,90149,90150,90151,90152,90153,90154,90155,90156,90157) ORDER BY it.item_level, it.name;
