-- ---------------------------------------------------------------------------------------
-- Summonable services: a class-trainer call per class, plus a banker.
--
-- GENERATED by gen_summons.py from summons.py. Do not edit by hand.
-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART, a rebuilt patch-6.mpq, and
-- lua_scripts/summon_services.lua.
-- ---------------------------------------------------------------------------------------
--
-- WHY NINE SPELLS AND NOT ONE
--   Creature::IsTrainerOf enforces an exact class match for TRAINER_TYPE_CLASS, so there
--   are nine distinct trainer NPCs no matter what. Given that, a per-class spell costs one
--   extra row and lets a warrior see "Call Warrior Master" instead of something generic.
--
-- CLASS GATING IS BY GRANT, NOT BY SPELL DATA
--   Each spell is inserted into playercreateinfo_spell only for its own class, and granted
--   to existing characters only of that class. A warrior is never taught the paladin call,
--   so there is nothing to hide. No skill_line_ability row, so these sit in GENERAL.
--
-- THE BANKER NPC IS CUSTOM ON PURPOSE
--   Every stock banker is faction-specific - Olivia Burnside is faction 12 (Alliance),
--   Randolph Montague 68 (Horde) - so neither works for both sides. 2600400 is cloned from
--   21002 like the other custom NPCs, which gives faction 35: friendly to everyone.
--
--   UNIT_NPC_FLAG_BANKER is 0x100 (256) in this core, NOT the 0x80 you may expect. npc_flags
--   257 = GOSSIP + BANKER. Getting this wrong gives an NPC whose window silently never
--   opens, which is exactly the trap the VENDOR flag sets in setup-class-and-profession-npcs.
--
-- Strongbox (38601) is still the simpler way to reach your own bank. The summoned banker
-- exists because it is a PHYSICAL npc, so in a duo one summon serves both players.
-- ---------------------------------------------------------------------------------------

USE tw_world;

-- ---------------------------------------------------------------------------------------
-- 1. The banker NPC, cloned from 21002 (faction 35, level 1, no unit flags).
-- ---------------------------------------------------------------------------------------
DELETE FROM creature_template WHERE entry = 2600400;
DROP TEMPORARY TABLE IF EXISTS tmp_npc;
CREATE TEMPORARY TABLE tmp_npc LIKE creature_template;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET
  entry       = 2600400,
  name        = 'Banker',
  subname     = 'Summoned',
  npc_flags   = 257,          -- GOSSIP (0x01) + BANKER (0x100). NOT 0x80.
  display_id1 = 15420;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DROP TEMPORARY TABLE tmp_npc;

-- ---------------------------------------------------------------------------------------
-- 2. The spells. Cloned from Disenchant like Salvage and Strongbox, then retargeted at
--    the caster and stripped of cost, reagents and cooldown.
-- ---------------------------------------------------------------------------------------
DELETE FROM spell_template        WHERE entry   IN (38700,38701,38702,38703,38704,38705,38706,38707,38708,38710);
DELETE FROM skill_line_ability    WHERE spell_id IN (38700,38701,38702,38703,38704,38705,38706,38707,38708,38710);   -- GENERAL tab on purpose
DELETE FROM playercreateinfo_spell WHERE spell  IN (38700,38701,38702,38703,38704,38705,38706,38707,38708,38710);

-- Call Warrior Master    -> creature 2600200  (class 1 only)
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38700, name = 'Call Warrior Master', nameSubtext = '',
  description = 'Summons your Warrior Master for 5 minutes.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 319;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38700, 'TurtleMod: summon' FROM playercreateinfo
  WHERE class = 1;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38700, 1, 0 FROM tw_char.characters WHERE class = 1;

-- Call Paladin Master    -> creature 2600201  (class 2 only)
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38701, name = 'Call Paladin Master', nameSubtext = '',
  description = 'Summons your Paladin Master for 5 minutes.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 319;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38701, 'TurtleMod: summon' FROM playercreateinfo
  WHERE class = 2;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38701, 1, 0 FROM tw_char.characters WHERE class = 2;

-- Call Hunter Master     -> creature 2600202  (class 3 only)
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38702, name = 'Call Hunter Master', nameSubtext = '',
  description = 'Summons your Hunter Master for 5 minutes.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 319;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38702, 'TurtleMod: summon' FROM playercreateinfo
  WHERE class = 3;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38702, 1, 0 FROM tw_char.characters WHERE class = 3;

-- Call Rogue Master      -> creature 2600203  (class 4 only)
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38703, name = 'Call Rogue Master', nameSubtext = '',
  description = 'Summons your Rogue Master for 5 minutes.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 319;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38703, 'TurtleMod: summon' FROM playercreateinfo
  WHERE class = 4;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38703, 1, 0 FROM tw_char.characters WHERE class = 4;

-- Call Priest Master     -> creature 2600204  (class 5 only)
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38704, name = 'Call Priest Master', nameSubtext = '',
  description = 'Summons your Priest Master for 5 minutes.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 319;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38704, 'TurtleMod: summon' FROM playercreateinfo
  WHERE class = 5;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38704, 1, 0 FROM tw_char.characters WHERE class = 5;

-- Call Shaman Master     -> creature 2600205  (class 7 only)
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38705, name = 'Call Shaman Master', nameSubtext = '',
  description = 'Summons your Shaman Master for 5 minutes.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 319;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38705, 'TurtleMod: summon' FROM playercreateinfo
  WHERE class = 7;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38705, 1, 0 FROM tw_char.characters WHERE class = 7;

-- Call Mage Master       -> creature 2600206  (class 8 only)
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38706, name = 'Call Mage Master', nameSubtext = '',
  description = 'Summons your Mage Master for 5 minutes.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 319;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38706, 'TurtleMod: summon' FROM playercreateinfo
  WHERE class = 8;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38706, 1, 0 FROM tw_char.characters WHERE class = 8;

-- Call Warlock Master    -> creature 2600207  (class 9 only)
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38707, name = 'Call Warlock Master', nameSubtext = '',
  description = 'Summons your Warlock Master for 5 minutes.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 319;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38707, 'TurtleMod: summon' FROM playercreateinfo
  WHERE class = 9;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38707, 1, 0 FROM tw_char.characters WHERE class = 9;

-- Call Druid Master      -> creature 2600208  (class 11 only)
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38708, name = 'Call Druid Master', nameSubtext = '',
  description = 'Summons your Druid Master for 5 minutes.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 319;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38708, 'TurtleMod: summon' FROM playercreateinfo
  WHERE class = 11;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38708, 1, 0 FROM tw_char.characters WHERE class = 11;

-- Call Banker            -> creature 2600400
DROP TEMPORARY TABLE IF EXISTS tmp_s;
CREATE TEMPORARY TABLE tmp_s LIKE spell_template;
INSERT INTO tmp_s SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_s SET
  entry = 38710, name = 'Call Banker', nameSubtext = '',
  description = 'Summons a banker for 5 minutes. Anyone nearby can use it.',
  effect1 = 3, effect2 = 0, effect3 = 0,        -- DUMMY; the Lua script spawns it
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0, spellIconId = 1657;
INSERT INTO spell_template SELECT * FROM tmp_s;
DROP TEMPORARY TABLE tmp_s;
INSERT INTO playercreateinfo_spell (race, class, spell, note)
  SELECT DISTINCT race, class, 38710, 'TurtleMod: summon' FROM playercreateinfo;
INSERT IGNORE INTO tw_char.character_spell (guid, spell, active, disabled)
  SELECT guid, 38710, 1, 0 FROM tw_char.characters;

-- ---------------------------------------------------------------------------------------
SELECT entry, name, spellIconId FROM spell_template WHERE entry IN (38700,38701,38702,38703,38704,38705,38706,38707,38708,38710) ORDER BY entry;
SELECT entry, name, npc_flags FROM creature_template WHERE entry = 2600400;
SELECT s.name, COUNT(*) AS granted FROM tw_char.character_spell cs
  JOIN spell_template s ON s.entry = cs.spell
  WHERE cs.spell IN (38700,38701,38702,38703,38704,38705,38706,38707,38708,38710) GROUP BY s.name ORDER BY s.name;
