-- ---------------------------------------------------------------------------------------
-- Dungeon mentor scaling.
--
-- GENERATED by gen_scaling.py from scaling.py. Do not edit by hand.
-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART, a rebuilt patch-6.mpq, and
-- lua_scripts/dungeon_scaling.lua + dungeon_levels.lua.
-- ---------------------------------------------------------------------------------------
--
-- WHAT IT DOES
--   Walk into a dungeon well above its level and your damage done, healing done and maximum
--   health are scaled down toward that dungeon's level. Leave, and it is gone. A level 60
--   can run Ragefire Chasm with a level 15 friend without trivialising it.
--
-- WHAT IS *NOT* REDUCED, DELIBERATELY
--   Stats. The obvious implementation - SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE (137) - reduces
--   TOTAL stats, which includes everything your gear gives you. That makes good gear feel
--   worthless, which is the opposite of the intent: the gear should still feel great, the
--   numbers coming out the other end should just be level-appropriate. So the three auras
--   used are 79 (damage done), 136 (healing done) and 133 (max health), all percentage.
--
--   Abilities, talents, gear and skill are all untouched. You are still a level 60 - you
--   just hit like the dungeon expects.
--
-- WHY A LADDER OF 18 SPELLS
--   Eluna's Unit:AddAura applies a FIXED spell and there is no binding to set an aura's
--   magnitude at runtime, so the reduction is quantised into 5%% steps and the script picks
--   the nearest one down.
--
-- BASE POINTS
--   CalculateSimpleValue is EffectBasePoints + EffectBaseDice, and these carry a dice of 1,
--   so -40%% needs basePoints -41. Confirmed against stock spell 7000 "Tamed Pet Passive",
--   which uses basePoints -11 / dice 1 for -10%% damage.
--
-- THE OPT-OUT
--   38722 "Unrestrained". If a player KNOWS it, scaling is skipped for them. Default is therefore ON for
--   everyone with nothing to grant. Players toggle it themselves by typing  !scale  in say;
--   dungeon_scaling.lua consumes the message and learns/unlearns the marker.
-- ---------------------------------------------------------------------------------------

USE tw_world;

DELETE FROM spell_template     WHERE entry IN (38722,38730,38731,38732,38733,38734,38735,38736,38737,38738,38739,38740,38741,38742,38743,38744,38745,38746,38747);
DELETE FROM skill_line_ability WHERE spell_id IN (38722,38730,38731,38732,38733,38734,38735,38736,38737,38738,38739,38740,38741,38742,38743,38744,38745,38746,38747);

DROP TEMPORARY TABLE IF EXISTS tmp_sc;
CREATE TEMPORARY TABLE tmp_sc LIKE spell_template;

-- The opt-out marker. Passive and hidden: it is a flag, not a button.
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38722, name = 'Unrestrained', nameSubtext = '',
  description = 'Dungeon scaling will not be applied to you.',
  effect1 = 0, effect2 = 0, effect3 = 0,
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, effectImplicitTargetA1 = 1, effectImplicitTargetB1 = 0,
  spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0,
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64 | 128;   -- PASSIVE | HIDDEN_CLIENTSIDE
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -5% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38730, name = 'Mentor''s Restraint', nameSubtext = '5%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 5%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -6, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -6, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -6, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -10% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38731, name = 'Mentor''s Restraint', nameSubtext = '10%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 10%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -11, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -11, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -11, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -15% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38732, name = 'Mentor''s Restraint', nameSubtext = '15%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 15%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -16, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -16, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -16, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -20% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38733, name = 'Mentor''s Restraint', nameSubtext = '20%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 20%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -21, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -21, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -21, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -25% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38734, name = 'Mentor''s Restraint', nameSubtext = '25%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 25%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -26, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -26, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -26, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -30% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38735, name = 'Mentor''s Restraint', nameSubtext = '30%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 30%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -31, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -31, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -31, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -35% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38736, name = 'Mentor''s Restraint', nameSubtext = '35%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 35%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -36, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -36, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -36, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -40% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38737, name = 'Mentor''s Restraint', nameSubtext = '40%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 40%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -41, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -41, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -41, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -45% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38738, name = 'Mentor''s Restraint', nameSubtext = '45%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 45%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -46, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -46, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -46, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -50% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38739, name = 'Mentor''s Restraint', nameSubtext = '50%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 50%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -51, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -51, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -51, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -55% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38740, name = 'Mentor''s Restraint', nameSubtext = '55%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 55%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -56, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -56, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -56, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -60% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38741, name = 'Mentor''s Restraint', nameSubtext = '60%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 60%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -61, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -61, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -61, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -65% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38742, name = 'Mentor''s Restraint', nameSubtext = '65%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 65%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -66, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -66, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -66, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -70% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38743, name = 'Mentor''s Restraint', nameSubtext = '70%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 70%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -71, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -71, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -71, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -75% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38744, name = 'Mentor''s Restraint', nameSubtext = '75%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 75%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -76, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -76, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -76, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -80% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38745, name = 'Mentor''s Restraint', nameSubtext = '80%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 80%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -81, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -81, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -81, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -85% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38746, name = 'Mentor''s Restraint', nameSubtext = '85%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 85%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -86, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -86, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -86, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

-- -90% damage done, healing done and maximum health
INSERT INTO tmp_sc SELECT * FROM spell_template WHERE entry = 13262;
UPDATE tmp_sc SET
  entry = 38747, name = 'Mentor''s Restraint', nameSubtext = '90%',
  description = 'Your power is held back to suit this dungeon. Damage, healing and health reduced by 90%.',
  effect1 = 6, effect2 = 6, effect3 = 6,          -- SPELL_EFFECT_APPLY_AURA x3
  effectApplyAuraName1 = 79, effectBasePoints1 = -91, effectBaseDice1 = 1, effectDieSides1 = 1,
  effectApplyAuraName2 = 136, effectBasePoints2 = -91, effectBaseDice2 = 1, effectDieSides2 = 1,
  effectApplyAuraName3 = 133, effectBasePoints3 = -91, effectBaseDice3 = 1, effectDieSides3 = 1,
  effectImplicitTargetA1 = 1, effectImplicitTargetA2 = 1, effectImplicitTargetA3 = 1,
  effectImplicitTargetB1 = 0, effectImplicitTargetB2 = 0, effectImplicitTargetB3 = 0,
  effectMiscValue1 = 127, effectMiscValue2 = 0, effectMiscValue3 = 0,  -- 127 = all damage schools
  effectItemType1 = 0, effectTriggerSpell1 = 0,
  Targets = 0, spellLevel = 1, baseLevel = 1, manaCost = 0, powerType = 0,
  RecoveryTime = 0, categoryRecoveryTime = 0, DurationIndex = 21,   -- 21 = infinite
  reagent1 = 0, reagentCount1 = 0, reagent2 = 0, reagentCount2 = 0,
  EquippedItemClass = -1, RequiresSpellFocus = 0,
  Attributes = 64,          -- PASSIVE. Visible on purpose: you should see why you hit softer.
  AttributesEx = 0, spellIconId = 2458;
INSERT INTO spell_template SELECT * FROM tmp_sc;
TRUNCATE tmp_sc;

DROP TEMPORARY TABLE tmp_sc;

SELECT entry, name, nameSubtext, effectBasePoints1, effectApplyAuraName1, effectApplyAuraName2, effectApplyAuraName3
FROM spell_template WHERE entry IN (38722,38730,38731,38732,38733,38734,38735,38736,38737,38738,38739,38740,38741,38742,38743,38744,38745,38746,38747) ORDER BY entry;
