-- -------------------------------------------------------------------------------------
-- Inn teleports: one spell per inn, filed under the Adventuring skill (795).
--
-- GENERATED by gen_inns.py from inns.py - do not edit by hand.
-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART and a rebuilt patch-6.mpq.
-- -------------------------------------------------------------------------------------
--
-- Each spell is cloned from 3561 (Teleport: Stormwind), which already casts for ten
-- seconds, breaks on damage and has no cooldown. The destination is NOT in the spell -
-- it is a row in spell_target_position keyed by spell id, which is how 63 spells share
-- one template and still land in 63 different places.
--
-- You are not taught these. Walk into an inn and lua_scripts/inn_discovery.lua gives you
-- that one, so the tab fills in as you see the world rather than arriving complete.
-- -------------------------------------------------------------------------------------

USE tw_world;

-- Clean slate, so a re-run cannot leave a half-updated list behind.
DELETE FROM spell_template         WHERE entry    IN (44200,44201,44202,44203,44204,44205,44206,44207,44208,44209,44210,44211,44212,44213,44214,44215,44216,44217,44218,44219,44220,44221,44222,44223,44224,44225,44226,44227,44228,44229,44230,44231,44232,44233,44234,44235,44236,44237,44238,44239,44240,44241,44242,44243,44244,44245,44246,44247,44248,44249,44250,44251,44252,44253,44254,44255,44256,44257,44258,44259,44260,44261,44262);
DELETE FROM spell_target_position  WHERE id       IN (44200,44201,44202,44203,44204,44205,44206,44207,44208,44209,44210,44211,44212,44213,44214,44215,44216,44217,44218,44219,44220,44221,44222,44223,44224,44225,44226,44227,44228,44229,44230,44231,44232,44233,44234,44235,44236,44237,44238,44239,44240,44241,44242,44243,44244,44245,44246,44247,44248,44249,44250,44251,44252,44253,44254,44255,44256,44257,44258,44259,44260,44261,44262);
DELETE FROM skill_line_ability     WHERE spell_id IN (44200,44201,44202,44203,44204,44205,44206,44207,44208,44209,44210,44211,44212,44213,44214,44215,44216,44217,44218,44219,44220,44221,44222,44223,44224,44225,44226,44227,44228,44229,44230,44231,44232,44233,44234,44235,44236,44237,44238,44239,44240,44241,44242,44243,44244,44245,44246,44247,44248,44249,44250,44251,44252,44253,44254,44255,44256,44257,44258,44259,44260,44261,44262);

-- Hawk's Vigil                       Wetlands                   lvl --
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44200,
  name = 'Hawk''s Vigil',
  nameSubtext = 'Wetlands',
  description = 'Teleport to Hawk''s Vigil in Wetlands.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44200, 0, -3854.2100, -1872.2300, 142.1900, 2.8200);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7900, 795, 44200, 0, 0, 0);

-- Glenshire                          Tirisfal Uplands           lvl 3-16
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44201,
  name = 'Glenshire',
  nameSubtext = 'Tirisfal Uplands',
  description = 'Teleport to Glenshire in Tirisfal Uplands. The land around it suits levels 3 to 16.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44201, 0, 1793.0600, 2044.3500, 120.8900, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7901, 795, 44201, 0, 0, 0);

-- Alah'Thalas                        Quel'Thalas                lvl 5-57
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44202,
  name = 'Alah''Thalas',
  nameSubtext = 'Quel''Thalas',
  description = 'Teleport to Alah''Thalas in Quel''Thalas. The land around it suits levels 5 to 57.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44202, 0, 4232.6600, -2778.1100, 97.4700, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7902, 795, 44202, 0, 0, 0);

-- Caelan's Rest                      Lapidis Isle               lvl 45-53
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44203,
  name = 'Caelan''s Rest',
  nameSubtext = 'Lapidis Isle',
  description = 'Teleport to Caelan''s Rest in Lapidis Isle. The land around it suits levels 45 to 53.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44203, 0, -11886.6000, 3161.7700, 16.5100, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7903, 795, 44203, 0, 0, 0);

-- Maul'ogg Refuge                    Gillijim's Isle            lvl 49-52
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44204,
  name = 'Maul''ogg Refuge',
  nameSubtext = 'Gillijim''s Isle',
  description = 'Teleport to Maul''ogg Refuge in Gillijim''s Isle. The land around it suits levels 49 to 52.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44204, 0, -14014.2000, 2329.3200, 60.1200, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7904, 795, 44204, 0, 0, 0);

-- Karfang Hold                       Burning Steppes            lvl 50-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44205,
  name = 'Karfang Hold',
  nameSubtext = 'Burning Steppes',
  description = 'Teleport to Karfang Hold in Burning Steppes. The land around it suits levels 50 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44205, 0, -7471.8200, -2893.5500, 230.0600, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7905, 795, 44205, 0, 0, 0);

-- Earthen Ring Inn                   Stonetalon Mountains       lvl 10-19
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44206,
  name = 'Earthen Ring Inn',
  nameSubtext = 'Stonetalon Mountains',
  description = 'Teleport to Earthen Ring Inn in Stonetalon Mountains. The land around it suits levels 10 to 19.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44206, 1, 659.0000, 842.0000, 123.0000, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7906, 795, 44206, 0, 0, 0);

-- Moonhoof Village Inn               Moonwhisper Coast          lvl 43-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44207,
  name = 'Moonhoof Village Inn',
  nameSubtext = 'Moonwhisper Coast',
  description = 'Teleport to Moonhoof Village Inn in Moonwhisper Coast. The land around it suits levels 43 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44207, 1, 8305.5600, -6606.9800, 22.8300, 3.0100);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7907, 795, 44207, 0, 0, 0);

-- Sentinel Hill Inn                  Westfall                   lvl 11-16
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44208,
  name = 'Sentinel Hill Inn',
  nameSubtext = 'Westfall',
  description = 'Teleport to Sentinel Hill Inn in Westfall. The land around it suits levels 11 to 16.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44208, 0, -10653.3000, 1166.4300, 34.9300, 5.7800);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7908, 795, 44208, 0, 0, 0);

-- Strahnbrad Inn                     Strahnbrad, Strahnbrad     lvl 34-36
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44209,
  name = 'Strahnbrad Inn',
  nameSubtext = 'Strahnbrad',
  description = 'Teleport to Strahnbrad Inn in Strahnbrad, Strahnbrad. The land around it suits levels 34 to 36.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44209, 0, 683.7700, -912.1400, 174.5000, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7909, 795, 44209, 0, 0, 0);

-- Bael Hardul Inn                    Stonetalon Mountains       lvl 16-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44210,
  name = 'Bael Hardul Inn',
  nameSubtext = 'Stonetalon Mountains',
  description = 'Teleport to Bael Hardul Inn in Stonetalon Mountains. The land around it suits levels 16 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44210, 1, 928.1500, -830.0100, 166.1000, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7910, 795, 44210, 0, 0, 0);

-- Mudsprocket                        Dustwallow Marsh           lvl 40-42
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44211,
  name = 'Mudsprocket',
  nameSubtext = 'Dustwallow Marsh',
  description = 'Teleport to Mudsprocket in Dustwallow Marsh. The land around it suits levels 40 to 42.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44211, 1, -4593.9000, -3162.8100, 34.7000, 6.1900);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7911, 795, 44211, 0, 0, 0);

-- Sparkwater Port                    Durotar                    lvl 7-10
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44212,
  name = 'Sparkwater Port',
  nameSubtext = 'Durotar',
  description = 'Teleport to Sparkwater Port in Durotar. The land around it suits levels 7 to 10.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44212, 1, 921.1400, -5064.1000, 8.0200, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7912, 795, 44212, 0, 0, 0);

-- Lion's Pride Inn                   Goldshire, Elwynn Forest   lvl 5-6
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44213,
  name = 'Lion''s Pride Inn',
  nameSubtext = 'Elwynn Forest',
  description = 'Teleport to Lion''s Pride Inn in Goldshire, Elwynn Forest. The land around it suits levels 5 to 6.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44213, 0, -9466.3700, 21.4200, 56.3400, 1.5000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7913, 795, 44213, 0, 0, 0);

-- Lakeshire Inn                      Redridge Mountains         lvl 17-20
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44214,
  name = 'Lakeshire Inn',
  nameSubtext = 'Redridge Mountains',
  description = 'Teleport to Lakeshire Inn in Redridge Mountains. The land around it suits levels 17 to 20.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44214, 0, -9223.9800, -2157.1200, 64.0200, 3.0500);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7914, 795, 44214, 0, 0, 0);

-- Scarlet Raven Inn                  Darkshire, Duskwood        lvl 24-38
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44215,
  name = 'Scarlet Raven Inn',
  nameSubtext = 'Duskwood',
  description = 'Teleport to Scarlet Raven Inn in Darkshire, Duskwood. The land around it suits levels 24 to 38.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44215, 0, -10516.0000, -1161.2100, 28.1200, 4.0300);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7915, 795, 44215, 0, 0, 0);

-- Southshore Inn                     Hillsbrad Foothills        lvl 24-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44216,
  name = 'Southshore Inn',
  nameSubtext = 'Hillsbrad Foothills',
  description = 'Teleport to Southshore Inn in Hillsbrad Foothills. The land around it suits levels 24 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44216, 0, -857.1000, -570.7500, 11.2600, 1.5500);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7916, 795, 44216, 0, 0, 0);

-- Theramore Isle                     Dustwallow Marsh           lvl 36-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44217,
  name = 'Theramore Isle',
  nameSubtext = 'Dustwallow Marsh',
  description = 'Teleport to Theramore Isle in Dustwallow Marsh. The land around it suits levels 36 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44217, 1, -3616.1300, -4470.8200, 14.3300, 2.2200);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7917, 795, 44217, 0, 0, 0);

-- Thunderbrew Distillery             Kharanos, Dun Morogh       lvl 5-6
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44218,
  name = 'Thunderbrew Distillery',
  nameSubtext = 'Dun Morogh',
  description = 'Teleport to Thunderbrew Distillery in Kharanos, Dun Morogh. The land around it suits levels 5 to 6.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44218, 0, -5601.6000, -531.2000, 399.7400, 2.1300);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7918, 795, 44218, 0, 0, 0);

-- Stoutlager Inn                     Thelsamar, Loch Modan      lvl 10-11
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44219,
  name = 'Stoutlager Inn',
  nameSubtext = 'Loch Modan',
  description = 'Teleport to Stoutlager Inn in Thelsamar, Loch Modan. The land around it suits levels 10 to 11.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44219, 0, -5377.9100, -2973.9100, 323.2500, 1.7800);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7919, 795, 44219, 0, 0, 0);

-- Deepwater Tavern                   Menethil Harbor, Wetlands  lvl 28-38
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44220,
  name = 'Deepwater Tavern',
  nameSubtext = 'Wetlands',
  description = 'Teleport to Deepwater Tavern in Menethil Harbor, Wetlands. The land around it suits levels 28 to 38.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44220, 0, -3827.9300, -831.9000, 10.0900, 0.4000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7920, 795, 44220, 0, 0, 0);

-- Dolanaar                           Teldrassil                 lvl 5-5
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44221,
  name = 'Dolanaar',
  nameSubtext = 'Teldrassil',
  description = 'Teleport to Dolanaar in Teldrassil. The land around it suits levels 5 to 5.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44221, 1, 9802.2100, 982.6100, 1313.9800, 4.8000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7921, 795, 44221, 0, 0, 0);

-- Auberdine                          Darkshore                  lvl 10-12
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44222,
  name = 'Auberdine',
  nameSubtext = 'Darkshore',
  description = 'Teleport to Auberdine in Darkshore. The land around it suits levels 10 to 12.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44222, 1, 6406.5100, 515.3700, 8.7300, 1.2700);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7922, 795, 44222, 0, 0, 0);

-- Astranaar                          Ashenvale                  lvl 20-40
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44223,
  name = 'Astranaar',
  nameSubtext = 'Ashenvale',
  description = 'Teleport to Astranaar in Ashenvale. The land around it suits levels 20 to 40.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44223, 1, 2781.1600, -433.0000, 116.6700, 2.5800);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7923, 795, 44223, 0, 0, 0);

-- Gallows' End Tavern                Brill, Tirisfal Glades     lvl 5-9
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44224,
  name = 'Gallows'' End Tavern',
  nameSubtext = 'Tirisfal Glades',
  description = 'Teleport to Gallows'' End Tavern in Brill, Tirisfal Glades. The land around it suits levels 5 to 9.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44224, 0, 2269.5100, 244.9400, 34.3400, 3.7500);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7924, 795, 44224, 0, 0, 0);

-- The Sepulcher Inn                  The Sepulcher, Silverpine  lvl 10-13
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44225,
  name = 'The Sepulcher Inn',
  nameSubtext = 'Silverpine Forest',
  description = 'Teleport to The Sepulcher Inn in The Sepulcher, Silverpine Forest. The land around it suits levels 10 to 13.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44225, 0, 510.9200, 1636.4700, 126.0300, 4.3100);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7925, 795, 44225, 0, 0, 0);

-- Tarren Mill Inn                    Tarren Mill, Hillsbrad Foo lvl 20-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44226,
  name = 'Tarren Mill Inn',
  nameSubtext = 'Hillsbrad Foothills',
  description = 'Teleport to Tarren Mill Inn in Tarren Mill, Hillsbrad Foothills. The land around it suits levels 20 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44226, 0, -5.9700, -942.2800, 57.1600, 2.7400);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7926, 795, 44226, 0, 0, 0);

-- Bloodhoof Village Inn              Bloodhoof Village, Mulgore lvl 5-6
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44227,
  name = 'Bloodhoof Village Inn',
  nameSubtext = 'Mulgore',
  description = 'Teleport to Bloodhoof Village Inn in Bloodhoof Village, Mulgore. The land around it suits levels 5 to 6.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44227, 1, -2365.3700, -347.3100, -8.8700, 5.8500);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7927, 795, 44227, 0, 0, 0);

-- The Crossroads Inn                 The Crossroads, The Barren lvl 3-11
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44228,
  name = 'The Crossroads Inn',
  nameSubtext = 'The Barrens',
  description = 'Teleport to The Crossroads Inn in The Crossroads, The Barrens. The land around it suits levels 3 to 11.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44228, 1, -413.6000, -2644.8800, 96.2200, 3.3400);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7928, 795, 44228, 0, 0, 0);

-- Ratchet Inn                        Ratchet, The Barrens       lvl 14-57
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44229,
  name = 'Ratchet Inn',
  nameSubtext = 'The Barrens',
  description = 'Teleport to Ratchet Inn in Ratchet, The Barrens. The land around it suits levels 14 to 57.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44229, 1, -1050.0400, -3664.8000, 23.9700, 6.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7929, 795, 44229, 0, 0, 0);

-- Razor Hill Inn                     Razor Hill, Durotar        lvl 6-7
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44230,
  name = 'Razor Hill Inn',
  nameSubtext = 'Durotar',
  description = 'Teleport to Razor Hill Inn in Razor Hill, Durotar. The land around it suits levels 6 to 7.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44230, 1, 340.3600, -4686.2900, 16.5400, 4.1900);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7930, 795, 44230, 0, 0, 0);

-- Stonard Inn                        Stonard, Swamp of Sorrows  lvl 36-50
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44231,
  name = 'Stonard Inn',
  nameSubtext = 'Swamp of Sorrows',
  description = 'Teleport to Stonard Inn in Stonard, Swamp of Sorrows. The land around it suits levels 36 to 50.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44231, 0, -10487.3000, -3258.8400, 21.1100, 0.1000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7931, 795, 44231, 0, 0, 0);

-- Booty Bay Inn                      Booty Bay, Stranglethorn V lvl 41-57
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44232,
  name = 'Booty Bay Inn',
  nameSubtext = 'Stranglethorn Vale',
  description = 'Teleport to Booty Bay Inn in Booty Bay, Stranglethorn Vale. The land around it suits levels 41 to 57.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44232, 0, -14457.7000, 495.3500, 15.2100, 3.9800);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7932, 795, 44232, 0, 0, 0);

-- Camp Taurajo Inn                   Camp Taurajo, The Barrens  lvl 11-20
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44233,
  name = 'Camp Taurajo Inn',
  nameSubtext = 'The Barrens',
  description = 'Teleport to Camp Taurajo Inn in Camp Taurajo, The Barrens. The land around it suits levels 11 to 20.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44233, 1, -2376.2700, -1995.7400, 96.7900, 1.0600);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7933, 795, 44233, 0, 0, 0);

-- Sun Rock Retreat Inn               Sun Rock Retreat, Stonetal lvl 10-17
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44234,
  name = 'Sun Rock Retreat Inn',
  nameSubtext = 'Stonetalon Mountains',
  description = 'Teleport to Sun Rock Retreat Inn in Sun Rock Retreat, Stonetalon Mountains. The land around it suits levels 10 to 17.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44234, 1, 893.6500, 927.9500, 106.3600, 5.7100);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7934, 795, 44234, 0, 0, 0);

-- Gadgetzan Inn                      Gadgetzan, Tanaris         lvl 40-57
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44235,
  name = 'Gadgetzan Inn',
  nameSubtext = 'Tanaris',
  description = 'Teleport to Gadgetzan Inn in Gadgetzan, Tanaris. The land around it suits levels 40 to 57.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44235, 1, -7158.9600, -3841.6100, 8.8500, 1.9500);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7935, 795, 44235, 0, 0, 0);

-- Feathermoon Stronghold Inn         Feathermoon Stronghold, Fe lvl 40-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44236,
  name = 'Feathermoon Stronghold Inn',
  nameSubtext = 'Feralas',
  description = 'Teleport to Feathermoon Stronghold Inn in Feathermoon Stronghold, Feralas. The land around it suits levels 40 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44236, 1, -4381.5900, 3289.4500, 13.6300, 0.0300);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7936, 795, 44236, 0, 0, 0);

-- Camp Mojache Inn                   Camp Mojache, Feralas      lvl 40-41
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44237,
  name = 'Camp Mojache Inn',
  nameSubtext = 'Feralas',
  description = 'Teleport to Camp Mojache Inn in Camp Mojache, Feralas. The land around it suits levels 40 to 41.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44237, 1, -4460.1000, 242.7200, 39.1900, 0.5100);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7937, 795, 44237, 0, 0, 0);

-- Aerie Peak Inn                     Aerie Peak, Wildhammer Kee lvl 40-41
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44238,
  name = 'Aerie Peak Inn',
  nameSubtext = 'Wildhammer Keep',
  description = 'Teleport to Aerie Peak Inn in Aerie Peak, Wildhammer Keep. The land around it suits levels 40 to 41.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44238, 0, 394.6600, -2097.1400, 131.5600, 4.9300);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7938, 795, 44238, 0, 0, 0);

-- Kargath Inn                        Kargath, Badlands          lvl 39-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44239,
  name = 'Kargath Inn',
  nameSubtext = 'Badlands',
  description = 'Teleport to Kargath Inn in Kargath, Badlands. The land around it suits levels 39 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44239, 0, -6650.1000, -2149.4100, 245.3500, 4.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7939, 795, 44239, 0, 0, 0);

-- Hammerfall Inn                     Hammerfall, Arathi Highlan lvl 31-50
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44240,
  name = 'Hammerfall Inn',
  nameSubtext = 'Arathi Highlands',
  description = 'Teleport to Hammerfall Inn in Hammerfall, Arathi Highlands. The land around it suits levels 31 to 50.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44240, 0, -912.3700, -3524.9200, 72.7700, 3.1400);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7940, 795, 44240, 0, 0, 0);

-- Ambershire Inn                     Northwind                  lvl 28-29
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44241,
  name = 'Ambershire Inn',
  nameSubtext = 'Northwind',
  description = 'Teleport to Ambershire Inn in Northwind. The land around it suits levels 28 to 29.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44241, 0, -7623.8900, 621.2400, 50.3300, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7941, 795, 44241, 0, 0, 0);

-- Shatterblade Point Inn             Grim Reaches               lvl 35-37
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44242,
  name = 'Shatterblade Point Inn',
  nameSubtext = 'Grim Reaches',
  description = 'Teleport to Shatterblade Point Inn in Grim Reaches. The land around it suits levels 35 to 37.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44242, 0, -4024.2500, -5291.4000, 206.6900, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7942, 795, 44242, 0, 0, 0);

-- Dun Kithas Inn                     Grim Reaches               lvl 31-40
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44243,
  name = 'Dun Kithas Inn',
  nameSubtext = 'Grim Reaches',
  description = 'Teleport to Dun Kithas Inn in Grim Reaches. The land around it suits levels 31 to 40.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44243, 0, -4938.0900, -4837.0400, 172.7200, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7943, 795, 44243, 0, 0, 0);

-- Steepcliff Port Inn                Tirisfal Glades            lvl 15-17
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44244,
  name = 'Steepcliff Port Inn',
  nameSubtext = 'Tirisfal Glades',
  description = 'Teleport to Steepcliff Port Inn in Tirisfal Glades. The land around it suits levels 15 to 17.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44244, 0, 1959.9100, 2828.6500, 3.6200, 4.7200);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7944, 795, 44244, 0, 0, 0);

-- Nordanaar Inn                      Hyjal                      lvl 60-60
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44245,
  name = 'Nordanaar Inn',
  nameSubtext = 'Hyjal',
  description = 'Teleport to Nordanaar Inn in Hyjal. The land around it suits levels 60 to 60.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44245, 1, 5501.8500, -3805.4500, 1609.5900, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7945, 795, 44245, 0, 0, 0);

-- Nijel's Point Inn                  Nijel's Point, Desolace    lvl --
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44246,
  name = 'Nijel''s Point Inn',
  nameSubtext = 'Desolace',
  description = 'Teleport to Nijel''s Point Inn in Nijel''s Point, Desolace.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44246, 1, 255.6200, 1253.7600, 192.2200, 3.2500);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7946, 795, 44246, 0, 0, 0);

-- Shadowprey Village Inn             Shadowprey Village, Desola lvl 37-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44247,
  name = 'Shadowprey Village Inn',
  nameSubtext = 'Desolace',
  description = 'Teleport to Shadowprey Village Inn in Shadowprey Village, Desolace. The land around it suits levels 37 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44247, 1, -1592.8400, 3150.2700, 46.5800, 4.1900);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7947, 795, 44247, 0, 0, 0);

-- Freewind Post Inn                  Freewind Post, Thousand Ne lvl 25-45
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44248,
  name = 'Freewind Post Inn',
  nameSubtext = 'Thousand Needles',
  description = 'Teleport to Freewind Post Inn in Freewind Post, Thousand Needles. The land around it suits levels 25 to 45.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44248, 1, -5477.8500, -2460.4300, 89.3700, 0.3100);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7948, 795, 44248, 0, 0, 0);

-- Everlook Inn                       Everlook, Winterspring     lvl 55-57
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44249,
  name = 'Everlook Inn',
  nameSubtext = 'Winterspring',
  description = 'Teleport to Everlook Inn in Everlook, Winterspring. The land around it suits levels 55 to 57.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44249, 1, 6695.1500, -4673.0400, 721.6500, 0.5400);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7949, 795, 44249, 0, 0, 0);

-- Splintertree Post Inn              Splintertree Post, Ashenva lvl 25-40
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44250,
  name = 'Splintertree Post Inn',
  nameSubtext = 'Ashenvale',
  description = 'Teleport to Splintertree Post Inn in Splintertree Post, Ashenvale. The land around it suits levels 25 to 40.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44250, 1, 2341.8600, -2566.9900, 102.8600, 2.2900);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7950, 795, 44250, 0, 0, 0);

-- Brinthilien Inn                    Thalassian Highlands       lvl 3-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44251,
  name = 'Brinthilien Inn',
  nameSubtext = 'Thalassian Highlands',
  description = 'Teleport to Brinthilien Inn in Thalassian Highlands. The land around it suits levels 3 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44251, 0, 3169.5700, -2530.0200, 110.9000, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7951, 795, 44251, 0, 0, 0);

-- farm Inn                           farm, Stormwind backup res lvl 5-9
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44252,
  name = 'farm Inn',
  nameSubtext = 'Stormwind backup rest',
  description = 'Teleport to farm Inn in farm, Stormwind backup rest. The land around it suits levels 5 to 9.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44252, 0, -9050.8700, 445.4600, 93.0600, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7952, 795, 44252, 0, 0, 0);

-- Undercity Inn                      Undercity, The Undercity   lvl 7-60
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44253,
  name = 'Undercity Inn',
  nameSubtext = 'The Undercity',
  description = 'Teleport to Undercity Inn in Undercity, The Undercity. The land around it suits levels 7 to 60.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44253, 0, 1642.1000, 239.8400, 62.5900, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7953, 795, 44253, 0, 0, 0);

-- Revantusk Village Inn              Revantusk Village, Revantu lvl 55-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44254,
  name = 'Revantusk Village Inn',
  nameSubtext = 'Revantusk Village',
  description = 'Teleport to Revantusk Village Inn in Revantusk Village, Revantusk Village. The land around it suits levels 55 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44254, 0, -622.1400, -4582.1400, 22.5800, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7954, 795, 44254, 0, 0, 0);

-- z2 Inn                             z2, Grom'gol Base Camp     lvl 35-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44255,
  name = 'z2 Inn',
  nameSubtext = 'Grom''gol Base Camp',
  description = 'Teleport to z2 Inn in z2, Grom''gol Base Camp. The land around it suits levels 35 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44255, 0, -12434.4000, 211.5600, 2.4500, 0.9100);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7955, 795, 44255, 0, 0, 0);

-- Cenarion Hold Inn                  Cenarion Hold, Cenarion Ho lvl 57-60
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44256,
  name = 'Cenarion Hold Inn',
  nameSubtext = 'Cenarion Hold',
  description = 'Teleport to Cenarion Hold Inn in Cenarion Hold, Cenarion Hold. The land around it suits levels 57 to 60.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44256, 1, -6864.9800, 731.6100, 50.0000, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7956, 795, 44256, 0, 0, 0);

-- Light's Hope Chapel Inn            Light's Hope Chapel, Light lvl 54-60
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44257,
  name = 'Light''s Hope Chapel Inn',
  nameSubtext = 'Light''s Hope Chapel',
  description = 'Teleport to Light''s Hope Chapel Inn in Light''s Hope Chapel, Light''s Hope Chapel. The land around it suits levels 54 to 60.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44257, 0, 2298.1700, -5340.9800, 90.8800, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7957, 795, 44257, 0, 0, 0);

-- Stonetalon Peak Inn                Stonetalon Peak, Stonetalo lvl 22-24
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44258,
  name = 'Stonetalon Peak Inn',
  nameSubtext = 'Stonetalon Peak',
  description = 'Teleport to Stonetalon Peak Inn in Stonetalon Peak, Stonetalon Peak. The land around it suits levels 22 to 24.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44258, 1, 2729.8800, 1498.1400, 237.5900, 4.0500);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7958, 795, 44258, 0, 0, 0);

-- Powder Town Inn                    Stonetalon Mountains       lvl 22-25
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44259,
  name = 'Powder Town Inn',
  nameSubtext = 'Stonetalon Mountains',
  description = 'Teleport to Powder Town Inn in Stonetalon Mountains. The land around it suits levels 22 to 25.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44259, 1, 1375.7500, 1719.4100, 144.7200, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7959, 795, 44259, 0, 0, 0);

-- Tel Co. Basecamp                   Tel'Abim                   lvl 53-55
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44260,
  name = 'Tel Co. Basecamp',
  nameSubtext = 'Tel''Abim',
  description = 'Teleport to Tel Co. Basecamp in Tel''Abim. The land around it suits levels 53 to 55.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44260, 1, -8849.2100, -6506.4800, 12.8100, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7960, 795, 44260, 0, 0, 0);

-- Rustgate Inn                       Blackstone Island          lvl 3-7
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44261,
  name = 'Rustgate Inn',
  nameSubtext = 'Blackstone Island',
  description = 'Teleport to Rustgate Inn in Blackstone Island. The land around it suits levels 3 to 7.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44261, 1, -344.6000, -7465.1300, 80.3200, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7961, 795, 44261, 0, 0, 0);

-- Shademore Tavern                   Gilneas                    lvl 39-41
DROP TEMPORARY TABLE IF EXISTS tmp_i;
CREATE TEMPORARY TABLE tmp_i LIKE spell_template;
INSERT INTO tmp_i SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_i SET
  entry = 44262,
  name = 'Shademore Tavern',
  nameSubtext = 'Gilneas',
  description = 'Teleport to Shademore Tavern in Gilneas. The land around it suits levels 39 to 41.',
  spellIconId = 2179,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_i;
DROP TEMPORARY TABLE tmp_i;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44262, 0, -1664.7000, 2028.8700, 54.6900, 0.0000);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (7962, 795, 44262, 0, 0, 0);

-- -------------------------------------------------------------------------------------
-- Verification
-- -------------------------------------------------------------------------------------
SELECT 'spells' AS what, COUNT(*) AS n FROM spell_template WHERE entry IN (44200,44201,44202,44203,44204,44205,44206,44207,44208,44209,44210,44211,44212,44213,44214,44215,44216,44217,44218,44219,44220,44221,44222,44223,44224,44225,44226,44227,44228,44229,44230,44231,44232,44233,44234,44235,44236,44237,44238,44239,44240,44241,44242,44243,44244,44245,44246,44247,44248,44249,44250,44251,44252,44253,44254,44255,44256,44257,44258,44259,44260,44261,44262)
UNION ALL SELECT 'destinations', COUNT(*) FROM spell_target_position WHERE id IN (44200,44201,44202,44203,44204,44205,44206,44207,44208,44209,44210,44211,44212,44213,44214,44215,44216,44217,44218,44219,44220,44221,44222,44223,44224,44225,44226,44227,44228,44229,44230,44231,44232,44233,44234,44235,44236,44237,44238,44239,44240,44241,44242,44243,44244,44245,44246,44247,44248,44249,44250,44251,44252,44253,44254,44255,44256,44257,44258,44259,44260,44261,44262)
UNION ALL SELECT 'skill lines', COUNT(*) FROM skill_line_ability WHERE spell_id IN (44200,44201,44202,44203,44204,44205,44206,44207,44208,44209,44210,44211,44212,44213,44214,44215,44216,44217,44218,44219,44220,44221,44222,44223,44224,44225,44226,44227,44228,44229,44230,44231,44232,44233,44234,44235,44236,44237,44238,44239,44240,44241,44242,44243,44244,44245,44246,44247,44248,44249,44250,44251,44252,44253,44254,44255,44256,44257,44258,44259,44260,44261,44262);

-- Every destination should be on map 0 or 1 and nowhere near the origin.
SELECT id, target_map, ROUND(target_position_x) x, ROUND(target_position_y) y
FROM spell_target_position WHERE id IN (44200,44201,44202,44203,44204,44205,44206,44207,44208,44209,44210,44211,44212,44213,44214,44215,44216,44217,44218,44219,44220,44221,44222,44223,44224,44225,44226,44227,44228,44229,44230,44231,44232,44233,44234,44235,44236,44237,44238,44239,44240,44241,44242,44243,44244,44245,44246,44247,44248,44249,44250,44251,44252,44253,44254,44255,44256,44257,44258,44259,44260,44261,44262)
  AND (ABS(target_position_x) < 1 AND ABS(target_position_y) < 1);
