-- -------------------------------------------------------------------------------------
-- Dungeon portals: one teleport per dungeon, earned at its summoning stone.
--
-- GENERATED by gen_dungeon_portals.py - do not edit by hand.
-- Run against tw_world. IDEMPOTENT. Needs a mangosd RESTART and a rebuilt patch-6.mpq.
-- -------------------------------------------------------------------------------------
--
-- Filed under Adventuring (795), the same skill as the inn teleports, so travel collects
-- in one tab: inns are where you rest, dungeons are where you go.
--
-- YOU LAND OUTSIDE THE DOOR, NOT INSIDE. areatrigger_teleport holds the position inside
-- the instance; the AreaTrigger.dbc position for the same trigger is the doorway in the
-- outside world, and that is the destination here. You still walk in.
-- -------------------------------------------------------------------------------------

USE tw_world;

DELETE FROM spell_template        WHERE entry    IN (44300,44301,44302,44303,44304,44305,44306,44307,44308,44309,44310,44311,44312,44313,44314,44315,44316,44317,44318,44319,44320,44321,44322,44323,44324,44325,44326,44327,44328);
DELETE FROM spell_target_position WHERE id       IN (44300,44301,44302,44303,44304,44305,44306,44307,44308,44309,44310,44311,44312,44313,44314,44315,44316,44317,44318,44319,44320,44321,44322,44323,44324,44325,44326,44327,44328);
DELETE FROM skill_line_ability    WHERE spell_id IN (44300,44301,44302,44303,44304,44305,44306,44307,44308,44309,44310,44311,44312,44313,44314,44315,44316,44317,44318,44319,44320,44321,44322,44323,44324,44325,44326,44327,44328);

-- Shadowfang Keep                  map 33    requires level 10
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44300,
  name = 'Shadowfang Keep',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Shadowfang Keep. The door requires level 10.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44300, 0, -229.4900, 1576.3500, 78.8909, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8000, 795, 44300, 0, 0, 0);

-- Stormwind Stockade               map 34    requires level 15
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44301,
  name = 'Stormwind Stockade',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Stormwind Stockade. The door requires level 15.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44301, 0, -8761.8496, 848.5570, 87.8052, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8001, 795, 44301, 0, 0, 0);

-- Stormwind Vault                  map 35    requires level 58
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44302,
  name = 'Stormwind Vault',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Stormwind Vault. The door requires level 58.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44302, 0, -8667.5596, 623.5630, 85.4054, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8002, 795, 44302, 0, 0, 0);

-- Deadmines                        map 36    requires level 10
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44303,
  name = 'Deadmines',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Deadmines. The door requires level 10.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44303, 0, -11208.5000, 1685.3400, 25.7612, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8003, 795, 44303, 0, 0, 0);

-- Wailing Caverns                  map 43    requires level 10
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44304,
  name = 'Wailing Caverns',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Wailing Caverns. The door requires level 10.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44304, 1, -753.5960, -2212.7800, 21.5403, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8004, 795, 44304, 0, 0, 0);

-- Razorfen Kraul                   map 47    requires level 15
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44305,
  name = 'Razorfen Kraul',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Razorfen Kraul. The door requires level 15.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44305, 1, -4456.7002, -1655.9900, 86.1095, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8005, 795, 44305, 0, 0, 0);

-- Blackfathom Deeps                map 48    requires level 10
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44306,
  name = 'Blackfathom Deeps',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Blackfathom Deeps. The door requires level 10.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44306, 1, 4252.3701, 756.9740, -23.0632, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8006, 795, 44306, 0, 0, 0);

-- Uldaman                          map 70    requires level 30
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44307,
  name = 'Uldaman',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Uldaman. The door requires level 30.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44307, 0, -6053.7300, -2954.6299, 213.6860, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8007, 795, 44307, 0, 0, 0);

-- Gnomeregan                       map 90    requires level 15
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44308,
  name = 'Gnomeregan',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Gnomeregan. The door requires level 15.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44308, 0, -5161.3301, 939.6230, 258.2880, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8008, 795, 44308, 0, 0, 0);

-- Sunken Temple                    map 109   requires level 35
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44309,
  name = 'Sunken Temple',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Sunken Temple. The door requires level 35.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44309, 0, -10162.7002, -3998.6499, -107.9780, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8009, 795, 44309, 0, 0, 0);

-- Razorfen Downs                   map 129   requires level 25
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44310,
  name = 'Razorfen Downs',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Razorfen Downs. The door requires level 25.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44310, 1, -4666.5200, -2536.8201, 86.9671, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8010, 795, 44310, 0, 0, 0);

-- Scarlet Monastery                map 189   requires level 20
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44311,
  name = 'Scarlet Monastery',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Scarlet Monastery. The door requires level 20.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44311, 0, 2924.3799, -798.4290, 161.6110, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8011, 795, 44311, 0, 0, 0);

-- Zul'Farrak                       map 209   requires level 35
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44312,
  name = 'Zul''Farrak',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Zul''Farrak. The door requires level 35.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44312, 1, -6773.4902, -2889.7700, 15.1063, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8012, 795, 44312, 0, 0, 0);

-- Blackrock Spire                  map 229   requires level 45
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44313,
  name = 'Blackrock Spire',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Blackrock Spire. The door requires level 45.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44313, 0, -7518.1899, -1239.1300, 287.2430, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8013, 795, 44313, 0, 0, 0);

-- Blackrock Depths                 map 230   requires level 40
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44314,
  name = 'Blackrock Depths',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Blackrock Depths. The door requires level 40.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44314, 0, -7176.6299, -937.6670, 170.2060, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8014, 795, 44314, 0, 0, 0);

-- Black Morass                     map 269   requires level 58
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44315,
  name = 'Black Morass',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Black Morass. The door requires level 58.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44315, 1, -8799.1904, -4115.1602, -199.9990, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8015, 795, 44315, 0, 0, 0);

-- Scholomance                      map 289   requires level 45
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44316,
  name = 'Scholomance',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Scholomance. The door requires level 45.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44316, 0, 1282.0500, -2548.7300, 85.3994, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8016, 795, 44316, 0, 0, 0);

-- Stratholme                       map 329   requires level 45
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44317,
  name = 'Stratholme',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Stratholme. The door requires level 45.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44317, 0, 3237.4600, -4060.6001, 112.0100, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8017, 795, 44317, 0, 0, 0);

-- Maraudon                         map 349   requires level 30
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44318,
  name = 'Maraudon',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Maraudon. The door requires level 30.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44318, 1, -1484.0699, 2617.5701, 75.7144, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8018, 795, 44318, 0, 0, 0);

-- Ragefire Chasm                   map 389   requires level 8
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44319,
  name = 'Ragefire Chasm',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Ragefire Chasm. The door requires level 8.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44319, 1, 1818.4000, -4427.2598, -10.4478, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8019, 795, 44319, 0, 0, 0);

-- Dire Maul                        map 429   requires level 45
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44320,
  name = 'Dire Maul',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Dire Maul. The door requires level 45.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44320, 1, -3730.4800, 933.9750, 160.9730, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8020, 795, 44320, 0, 0, 0);

-- Karazhan Crypt                   map 800   requires level 55
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44321,
  name = 'Karazhan Crypt',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Karazhan Crypt. The door requires level 55.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44321, 0, -11068.2998, -1811.6899, 53.0000, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8021, 795, 44321, 0, 0, 0);

-- Crescent Grove                   map 802   requires level 32
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44322,
  name = 'Crescent Grove',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Crescent Grove. The door requires level 32.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44322, 1, 1689.7800, -1272.1500, 161.6780, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8022, 795, 44322, 0, 0, 0);

-- Hateforge Quarry                 map 808   requires level 48
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44323,
  name = 'Hateforge Quarry',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Hateforge Quarry. The door requires level 48.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44323, 0, -8173.0000, -3114.5701, 201.2180, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8023, 795, 44323, 0, 0, 0);

-- Gilneas City                     map 815   requires level 40
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44324,
  name = 'Gilneas City',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Gilneas City. The door requires level 40.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44324, 0, -1096.8101, 2234.7700, 182.8600, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8024, 795, 44324, 0, 0, 0);

-- Dragonmaw Retreat                map 816   requires level 25
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44325,
  name = 'Dragonmaw Retreat',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Dragonmaw Retreat. The door requires level 25.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44325, 0, -3812.2800, -3595.8000, -45.9500, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8025, 795, 44325, 0, 0, 0);

-- Stormwrought Ruins               map 818   requires level 35
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44326,
  name = 'Stormwrought Ruins',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Stormwrought Ruins. The door requires level 35.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44326, 0, -8823.0996, 2903.1699, 135.4920, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8026, 795, 44326, 0, 0, 0);

-- Windhorn Canyon                  map 820   requires level 26
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44327,
  name = 'Windhorn Canyon',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Windhorn Canyon. The door requires level 26.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44327, 1, -5117.5200, -3534.2900, 3.9660, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8027, 795, 44327, 0, 0, 0);

-- Frostmane Hollow                 map 822   requires level 13
DROP TEMPORARY TABLE IF EXISTS tmp_d;
CREATE TEMPORARY TABLE tmp_d LIKE spell_template;
INSERT INTO tmp_d SELECT * FROM spell_template WHERE entry = 3561;
UPDATE tmp_d SET
  entry = 44328,
  name = 'Frostmane Hollow',
  nameSubtext = 'Dungeon',
  description = 'Teleport to the entrance of Frostmane Hollow. The door requires level 13.',
  spellIconId = 237,
  manaCost = 0, manaCostPercentage = 0, powerType = 0,
  spellLevel = 1, baseLevel = 1;
INSERT INTO spell_template SELECT * FROM tmp_d;
DROP TEMPORARY TABLE tmp_d;
INSERT INTO spell_target_position
  (id, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
  VALUES (44328, 0, -5020.4399, -1449.4301, 500.0760, 0);
INSERT INTO skill_line_ability
  (id, skill_id, spell_id, req_skill_value, max_value, min_value)
  VALUES (8028, 795, 44328, 0, 0, 0);

SELECT 'spells' AS what, COUNT(*) n FROM spell_template WHERE entry IN (44300,44301,44302,44303,44304,44305,44306,44307,44308,44309,44310,44311,44312,44313,44314,44315,44316,44317,44318,44319,44320,44321,44322,44323,44324,44325,44326,44327,44328)
UNION ALL SELECT 'destinations', COUNT(*) FROM spell_target_position WHERE id IN (44300,44301,44302,44303,44304,44305,44306,44307,44308,44309,44310,44311,44312,44313,44314,44315,44316,44317,44318,44319,44320,44321,44322,44323,44324,44325,44326,44327,44328)
UNION ALL SELECT 'skill lines', COUNT(*) FROM skill_line_ability WHERE spell_id IN (44300,44301,44302,44303,44304,44305,44306,44307,44308,44309,44310,44311,44312,44313,44314,44315,44316,44317,44318,44319,44320,44321,44322,44323,44324,44325,44326,44327,44328);
