-- ---------------------------------------------------------------------------------------
-- Prices for the 438 custom items (90100-90719), measured against real peers.
--
-- GENERATED by gen_item_prices.py - do not edit by hand.
-- Run against tw_world. IDEMPOTENT.
-- ---------------------------------------------------------------------------------------

USE tw_world;

-- Runed Copper Shield            sell   1200 ->    794   buy       0 ->    3970
UPDATE item_template SET sell_price = 794, buy_price = 3970 WHERE entry = 90100;
-- Copper Throwing Blade          sell   1200 ->      9   buy    6000 ->      45
UPDATE item_template SET sell_price = 9, buy_price = 45 WHERE entry = 90120;
-- Bronze Throwing Blade          sell   3000 ->    179   buy   15000 ->     895
UPDATE item_template SET sell_price = 179, buy_price = 895 WHERE entry = 90121;
-- Iron Throwing Blade            sell   4560 ->    179   buy   22800 ->     895
UPDATE item_template SET sell_price = 179, buy_price = 895 WHERE entry = 90122;
-- Mithril Throwing Blade         sell   6240 ->    179   buy   31200 ->     895
UPDATE item_template SET sell_price = 179, buy_price = 895 WHERE entry = 90123;
-- Thorium Throwing Blade         sell   7560 ->    179   buy   37800 ->     895
UPDATE item_template SET sell_price = 179, buy_price = 895 WHERE entry = 90124;
-- Copper Crossbow                sell   1200 ->   2546   buy    6000 ->   12730
UPDATE item_template SET sell_price = 2546, buy_price = 12730 WHERE entry = 90125;
-- Bronze Crossbow                sell   3000 ->   2546   buy   15000 ->   12730
UPDATE item_template SET sell_price = 2546, buy_price = 12730 WHERE entry = 90126;
-- Iron Crossbow                  sell   4560 ->   2546   buy   22800 ->   12730
UPDATE item_template SET sell_price = 2546, buy_price = 12730 WHERE entry = 90127;
-- Mithril Crossbow               sell   6240 ->   2546   buy   31200 ->   12730
UPDATE item_template SET sell_price = 2546, buy_price = 12730 WHERE entry = 90128;
-- Thorium Crossbow               sell   7560 ->  41559   buy   37800 ->  207795
UPDATE item_template SET sell_price = 41559, buy_price = 207795 WHERE entry = 90129;
-- Copper Pike                    sell   1200 ->   2323   buy    6000 ->   11615
UPDATE item_template SET sell_price = 2323, buy_price = 11615 WHERE entry = 90130;
-- Bronze Pike                    sell   3000 ->   2323   buy   15000 ->   11615
UPDATE item_template SET sell_price = 2323, buy_price = 11615 WHERE entry = 90131;
-- Iron Pike                      sell   4560 ->  10224   buy   22800 ->   51120
UPDATE item_template SET sell_price = 10224, buy_price = 51120 WHERE entry = 90132;
-- Mithril Claw                   sell   6240 ->  30734   buy   31200 ->  153670
UPDATE item_template SET sell_price = 30734, buy_price = 153670 WHERE entry = 90133;
-- Iron Maul                      sell   4560 ->  12543   buy   22800 ->   62715
UPDATE item_template SET sell_price = 12543, buy_price = 62715 WHERE entry = 90134;
-- Copper Bulwark                 sell    150 ->    364   buy     600 ->    1820
UPDATE item_template SET sell_price = 364, buy_price = 1820 WHERE entry = 90140;
-- Iron Bulwark                   sell   6268 ->   6246   buy   31340 ->   31230
UPDATE item_template SET sell_price = 6246, buy_price = 31230 WHERE entry = 90142;
-- Steel Bulwark                  sell  11234 ->  10537   buy   56171 ->   52685
UPDATE item_template SET sell_price = 10537, buy_price = 52685 WHERE entry = 90143;
-- Mithril Bulwark                sell  16449 ->  16851   buy   82246 ->   84255
UPDATE item_template SET sell_price = 16851, buy_price = 84255 WHERE entry = 90144;
-- Thorium Bulwark                sell  32052 ->  28785   buy  160263 ->  143925
UPDATE item_template SET sell_price = 28785, buy_price = 143925 WHERE entry = 90145;
-- Copper Wardingshield           sell    150 ->    364   buy     600 ->    1820
UPDATE item_template SET sell_price = 364, buy_price = 1820 WHERE entry = 90146;
-- Iron Wardingshield             sell   6268 ->   6246   buy   31340 ->   31230
UPDATE item_template SET sell_price = 6246, buy_price = 31230 WHERE entry = 90148;
-- Steel Wardingshield            sell  11234 ->  10537   buy   56171 ->   52685
UPDATE item_template SET sell_price = 10537, buy_price = 52685 WHERE entry = 90149;
-- Mithril Wardingshield          sell  16449 ->  16851   buy   82246 ->   84255
UPDATE item_template SET sell_price = 16851, buy_price = 84255 WHERE entry = 90150;
-- Thorium Wardingshield          sell  32052 ->  28785   buy  160263 ->  143925
UPDATE item_template SET sell_price = 28785, buy_price = 143925 WHERE entry = 90151;
-- Copper Roundshield             sell    150 ->    364   buy     600 ->    1820
UPDATE item_template SET sell_price = 364, buy_price = 1820 WHERE entry = 90152;
-- Iron Roundshield               sell   6268 ->   6246   buy   31340 ->   31230
UPDATE item_template SET sell_price = 6246, buy_price = 31230 WHERE entry = 90154;
-- Steel Roundshield              sell  11234 ->  10537   buy   56171 ->   52685
UPDATE item_template SET sell_price = 10537, buy_price = 52685 WHERE entry = 90155;
-- Mithril Roundshield            sell  16449 ->  16851   buy   82246 ->   84255
UPDATE item_template SET sell_price = 16851, buy_price = 84255 WHERE entry = 90156;
-- Thorium Roundshield            sell  32052 ->  28785   buy  160263 ->  143925
UPDATE item_template SET sell_price = 28785, buy_price = 143925 WHERE entry = 90157;
-- Copper Hatchet                 sell    138 ->     93   buy     691 ->     465
UPDATE item_template SET sell_price = 93, buy_price = 465 WHERE entry = 90200;
-- Heavy Copper Hatchet           sell    685 ->    231   buy    3426 ->    1155
UPDATE item_template SET sell_price = 231, buy_price = 1155 WHERE entry = 90201;
-- Bronze Hatchet                 sell    883 ->   1076   buy    4419 ->    5380
UPDATE item_template SET sell_price = 1076, buy_price = 5380 WHERE entry = 90202;
-- Heavy Bronze Hatchet           sell   2755 ->   1269   buy   13778 ->    6345
UPDATE item_template SET sell_price = 1269, buy_price = 6345 WHERE entry = 90203;
-- Iron Hatchet                   sell   4094 ->   1329   buy   20472 ->    6645
UPDATE item_template SET sell_price = 1329, buy_price = 6645 WHERE entry = 90204;
-- Heavy Iron Hatchet             sell   4509 ->   1390   buy   22548 ->    6950
UPDATE item_template SET sell_price = 1390, buy_price = 6950 WHERE entry = 90205;
-- Steel Hatchet                  sell  11354 ->   1390   buy   56770 ->    6950
UPDATE item_template SET sell_price = 1390, buy_price = 6950 WHERE entry = 90206;
-- Heavy Steel Hatchet            sell  14659 ->   1390   buy   73296 ->    6950
UPDATE item_template SET sell_price = 1390, buy_price = 6950 WHERE entry = 90207;
-- Mithril Hatchet                sell  24159 ->   1390   buy  120797 ->    6950
UPDATE item_template SET sell_price = 1390, buy_price = 6950 WHERE entry = 90208;
-- Heavy Mithril Hatchet          sell  33079 ->   7476   buy  165399 ->   37380
UPDATE item_template SET sell_price = 7476, buy_price = 37380 WHERE entry = 90209;
-- Thorium Hatchet                sell  42409 ->   7476   buy  212049 ->   37380
UPDATE item_template SET sell_price = 7476, buy_price = 37380 WHERE entry = 90210;
-- Heavy Thorium Hatchet          sell  49281 ->   7476   buy  246405 ->   37380
UPDATE item_template SET sell_price = 7476, buy_price = 37380 WHERE entry = 90211;
-- Copper Waraxe                  sell    298 ->    119   buy    1491 ->     595
UPDATE item_template SET sell_price = 119, buy_price = 595 WHERE entry = 90212;
-- Heavy Copper Waraxe            sell    555 ->    555   buy    2777 ->    2775
UPDATE item_template SET sell_price = 555, buy_price = 2775 WHERE entry = 90213;
-- Bronze Waraxe                  sell   1717 ->   1060   buy    8587 ->    5300
UPDATE item_template SET sell_price = 1060, buy_price = 5300 WHERE entry = 90214;
-- Heavy Bronze Waraxe            sell   3387 ->   1956   buy   16936 ->    9780
UPDATE item_template SET sell_price = 1956, buy_price = 9780 WHERE entry = 90215;
-- Iron Waraxe                    sell   5626 ->   2435   buy   28134 ->   12175
UPDATE item_template SET sell_price = 2435, buy_price = 12175 WHERE entry = 90216;
-- Heavy Iron Waraxe              sell   5657 ->   4046   buy   28285 ->   20230
UPDATE item_template SET sell_price = 4046, buy_price = 20230 WHERE entry = 90217;
-- Steel Waraxe                   sell  14221 ->   4046   buy   71106 ->   20230
UPDATE item_template SET sell_price = 4046, buy_price = 20230 WHERE entry = 90218;
-- Heavy Steel Waraxe             sell  11233 ->   4046   buy   56169 ->   20230
UPDATE item_template SET sell_price = 4046, buy_price = 20230 WHERE entry = 90219;
-- Mithril Waraxe                 sell  28460 ->   4046   buy  142301 ->   20230
UPDATE item_template SET sell_price = 4046, buy_price = 20230 WHERE entry = 90220;
-- Heavy Mithril Waraxe           sell  41050 ->   4046   buy  205250 ->   20230
UPDATE item_template SET sell_price = 4046, buy_price = 20230 WHERE entry = 90221;
-- Thorium Waraxe                 sell  52104 ->   8445   buy  208416 ->   42225
UPDATE item_template SET sell_price = 8445, buy_price = 42225 WHERE entry = 90222;
-- Heavy Thorium Waraxe           sell  57576 ->   8445   buy  287882 ->   42225
UPDATE item_template SET sell_price = 8445, buy_price = 42225 WHERE entry = 90223;
-- Copper Cudgel                  sell    146 ->     66   buy     731 ->     330
UPDATE item_template SET sell_price = 66, buy_price = 330 WHERE entry = 90224;
-- Heavy Copper Cudgel            sell    698 ->    185   buy    3494 ->     925
UPDATE item_template SET sell_price = 185, buy_price = 925 WHERE entry = 90225;
-- Bronze Cudgel                  sell   1363 ->   1119   buy    6816 ->    5595
UPDATE item_template SET sell_price = 1119, buy_price = 5595 WHERE entry = 90226;
-- Heavy Bronze Cudgel            sell   2611 ->   1119   buy   13058 ->    5595
UPDATE item_template SET sell_price = 1119, buy_price = 5595 WHERE entry = 90227;
-- Iron Cudgel                    sell   4552 ->   3838   buy   22764 ->   19190
UPDATE item_template SET sell_price = 3838, buy_price = 19190 WHERE entry = 90228;
-- Heavy Iron Cudgel              sell   7227 ->   3838   buy   36136 ->   19190
UPDATE item_template SET sell_price = 3838, buy_price = 19190 WHERE entry = 90229;
-- Steel Cudgel                   sell  10863 ->   4022   buy   43452 ->   20110
UPDATE item_template SET sell_price = 4022, buy_price = 20110 WHERE entry = 90230;
-- Heavy Steel Cudgel             sell  15556 ->   7271   buy   77783 ->   36355
UPDATE item_template SET sell_price = 7271, buy_price = 36355 WHERE entry = 90231;
-- Mithril Cudgel                 sell  21925 ->   7271   buy  109625 ->   36355
UPDATE item_template SET sell_price = 7271, buy_price = 36355 WHERE entry = 90232;
-- Heavy Mithril Cudgel           sell  30156 ->   7271   buy  150783 ->   36355
UPDATE item_template SET sell_price = 7271, buy_price = 36355 WHERE entry = 90233;
-- Thorium Cudgel                 sell  44982 ->   7271   buy  224911 ->   36355
UPDATE item_template SET sell_price = 7271, buy_price = 36355 WHERE entry = 90234;
-- Heavy Thorium Cudgel           sell  44982 ->  14948   buy  224911 ->   74740
UPDATE item_template SET sell_price = 14948, buy_price = 74740 WHERE entry = 90235;
-- Copper Sledge                  sell    140 ->    100   buy     701 ->     500
UPDATE item_template SET sell_price = 100, buy_price = 500 WHERE entry = 90236;
-- Heavy Copper Sledge            sell    533 ->    533   buy    2666 ->    2665
UPDATE item_template SET sell_price = 533, buy_price = 2665 WHERE entry = 90237;
-- Bronze Sledge                  sell   1470 ->    926   buy    7350 ->    4630
UPDATE item_template SET sell_price = 926, buy_price = 4630 WHERE entry = 90238;
-- Heavy Bronze Sledge            sell   1944 ->   1944   buy    9722 ->    9720
UPDATE item_template SET sell_price = 1944, buy_price = 9720 WHERE entry = 90239;
-- Iron Sledge                    sell   5632 ->   2194   buy   28160 ->   10970
UPDATE item_template SET sell_price = 2194, buy_price = 10970 WHERE entry = 90240;
-- Heavy Iron Sledge              sell   5297 ->   3745   buy   26489 ->   18725
UPDATE item_template SET sell_price = 3745, buy_price = 18725 WHERE entry = 90241;
-- Steel Sledge                   sell  13530 ->   3745   buy   67653 ->   18725
UPDATE item_template SET sell_price = 3745, buy_price = 18725 WHERE entry = 90242;
-- Heavy Steel Sledge             sell  12221 ->   3745   buy   61107 ->   18725
UPDATE item_template SET sell_price = 3745, buy_price = 18725 WHERE entry = 90243;
-- Mithril Sledge                 sell  28889 ->   3745   buy  144448 ->   18725
UPDATE item_template SET sell_price = 3745, buy_price = 18725 WHERE entry = 90244;
-- Heavy Mithril Sledge           sell  38871 ->   3745   buy  194357 ->   18725
UPDATE item_template SET sell_price = 3745, buy_price = 18725 WHERE entry = 90245;
-- Thorium Sledge                 sell  51451 ->   8759   buy  257259 ->   43795
UPDATE item_template SET sell_price = 8759, buy_price = 43795 WHERE entry = 90246;
-- Heavy Thorium Sledge           sell  60203 ->   8759   buy  301018 ->   43795
UPDATE item_template SET sell_price = 8759, buy_price = 43795 WHERE entry = 90247;
-- Copper Halberd                 sell      2 ->   2029   buy      14 ->   10145
UPDATE item_template SET sell_price = 2029, buy_price = 10145 WHERE entry = 90248;
-- Heavy Copper Halberd           sell   2079 ->   2029   buy   10398 ->   10145
UPDATE item_template SET sell_price = 2029, buy_price = 10145 WHERE entry = 90249;
-- Bronze Halberd                 sell   2079 ->   2029   buy   10398 ->   10145
UPDATE item_template SET sell_price = 2029, buy_price = 10145 WHERE entry = 90250;
-- Iron Halberd                   sell   1496 ->   2029   buy    5982 ->   10145
UPDATE item_template SET sell_price = 2029, buy_price = 10145 WHERE entry = 90252;
-- Heavy Iron Halberd             sell   5426 ->   3727   buy   27132 ->   18635
UPDATE item_template SET sell_price = 3727, buy_price = 18635 WHERE entry = 90253;
-- Steel Halberd                  sell   1896 ->   3727   buy    7584 ->   18635
UPDATE item_template SET sell_price = 3727, buy_price = 18635 WHERE entry = 90254;
-- Heavy Steel Halberd            sell   1896 ->   3727   buy    7584 ->   18635
UPDATE item_template SET sell_price = 3727, buy_price = 18635 WHERE entry = 90255;
-- Mithril Halberd                sell  34108 ->   3727   buy  170542 ->   18635
UPDATE item_template SET sell_price = 3727, buy_price = 18635 WHERE entry = 90256;
-- Heavy Mithril Halberd          sell  48127 ->   3727   buy  192509 ->   18635
UPDATE item_template SET sell_price = 3727, buy_price = 18635 WHERE entry = 90257;
-- Thorium Halberd                sell  10688 ->   5426   buy   42752 ->   27130
UPDATE item_template SET sell_price = 5426, buy_price = 27130 WHERE entry = 90258;
-- Heavy Thorium Halberd          sell  62785 ->   5426   buy  311428 ->   27130
UPDATE item_template SET sell_price = 5426, buy_price = 27130 WHERE entry = 90259;
-- Copper Shortblade              sell    146 ->     36   buy     732 ->     180
UPDATE item_template SET sell_price = 36, buy_price = 180 WHERE entry = 90260;
-- Heavy Copper Shortblade        sell    688 ->    179   buy    3441 ->     895
UPDATE item_template SET sell_price = 179, buy_price = 895 WHERE entry = 90261;
-- Bronze Shortblade              sell   1484 ->    763   buy    7423 ->    3815
UPDATE item_template SET sell_price = 763, buy_price = 3815 WHERE entry = 90262;
-- Heavy Bronze Shortblade        sell      0 ->   1101   buy       0 ->    5505
UPDATE item_template SET sell_price = 1101, buy_price = 5505 WHERE entry = 90263;
-- Iron Shortblade                sell   4436 ->   1748   buy   22180 ->    8740
UPDATE item_template SET sell_price = 1748, buy_price = 8740 WHERE entry = 90264;
-- Heavy Iron Shortblade          sell   7304 ->   7646   buy   36523 ->   38230
UPDATE item_template SET sell_price = 7646, buy_price = 38230 WHERE entry = 90265;
-- Steel Shortblade               sell  11356 ->  12324   buy   56781 ->   61620
UPDATE item_template SET sell_price = 12324, buy_price = 61620 WHERE entry = 90266;
-- Heavy Steel Shortblade         sell  15891 ->  14281   buy   79459 ->   71405
UPDATE item_template SET sell_price = 14281, buy_price = 71405 WHERE entry = 90267;
-- Mithril Shortblade             sell  14333 ->  14281   buy   71669 ->   71405
UPDATE item_template SET sell_price = 14281, buy_price = 71405 WHERE entry = 90268;
-- Heavy Mithril Shortblade       sell  30996 ->  23721   buy  154980 ->  118605
UPDATE item_template SET sell_price = 23721, buy_price = 118605 WHERE entry = 90269;
-- Thorium Shortblade             sell  41472 ->  24843   buy  207361 ->  124215
UPDATE item_template SET sell_price = 24843, buy_price = 124215 WHERE entry = 90270;
-- Heavy Thorium Shortblade       sell  51946 ->  24843   buy  259732 ->  124215
UPDATE item_template SET sell_price = 24843, buy_price = 124215 WHERE entry = 90271;
-- Copper Greatblade              sell    306 ->    106   buy    1531 ->     530
UPDATE item_template SET sell_price = 106, buy_price = 530 WHERE entry = 90272;
-- Heavy Copper Greatblade        sell    535 ->    142   buy    2676 ->     710
UPDATE item_template SET sell_price = 142, buy_price = 710 WHERE entry = 90273;
-- Bronze Greatblade              sell   1768 ->   1710   buy    8842 ->    8550
UPDATE item_template SET sell_price = 1710, buy_price = 8550 WHERE entry = 90274;
-- Heavy Bronze Greatblade        sell   2854 ->   2306   buy   14273 ->   11530
UPDATE item_template SET sell_price = 2306, buy_price = 11530 WHERE entry = 90275;
-- Iron Greatblade                sell   5709 ->   2407   buy   28547 ->   12035
UPDATE item_template SET sell_price = 2407, buy_price = 12035 WHERE entry = 90276;
-- Heavy Iron Greatblade          sell   9295 ->   2710   buy   46478 ->   13550
UPDATE item_template SET sell_price = 2710, buy_price = 13550 WHERE entry = 90277;
-- Steel Greatblade               sell  14120 ->   3014   buy   70603 ->   15070
UPDATE item_template SET sell_price = 3014, buy_price = 15070 WHERE entry = 90278;
-- Heavy Steel Greatblade         sell      0 ->   3014   buy       0 ->   15070
UPDATE item_template SET sell_price = 3014, buy_price = 15070 WHERE entry = 90279;
-- Mithril Greatblade             sell  27906 ->   3014   buy  139530 ->   15070
UPDATE item_template SET sell_price = 3014, buy_price = 15070 WHERE entry = 90280;
-- Heavy Mithril Greatblade       sell  35584 ->   3014   buy  177922 ->   15070
UPDATE item_template SET sell_price = 3014, buy_price = 15070 WHERE entry = 90281;
-- Thorium Greatblade             sell  47531 ->   9592   buy  237656 ->   47960
UPDATE item_template SET sell_price = 9592, buy_price = 47960 WHERE entry = 90282;
-- Heavy Thorium Greatblade       sell  64185 ->   9592   buy  320928 ->   47960
UPDATE item_template SET sell_price = 9592, buy_price = 47960 WHERE entry = 90283;
-- Copper Grips                   sell    244 ->   1025   buy    1224 ->    5125
UPDATE item_template SET sell_price = 1025, buy_price = 5125 WHERE entry = 90284;
-- Heavy Copper Grips             sell    426 ->   1025   buy    2130 ->    5125
UPDATE item_template SET sell_price = 1025, buy_price = 5125 WHERE entry = 90285;
-- Bronze Grips                   sell    426 ->   1025   buy    2130 ->    5125
UPDATE item_template SET sell_price = 1025, buy_price = 5125 WHERE entry = 90286;
-- Heavy Bronze Grips             sell   1623 ->   1635   buy    8117 ->    8175
UPDATE item_template SET sell_price = 1635, buy_price = 8175 WHERE entry = 90287;
-- Iron Grips                     sell   2975 ->   2994   buy   11900 ->   14970
UPDATE item_template SET sell_price = 2994, buy_price = 14970 WHERE entry = 90288;
-- Heavy Iron Grips               sell   4421 ->   2994   buy   22107 ->   14970
UPDATE item_template SET sell_price = 2994, buy_price = 14970 WHERE entry = 90289;
-- Steel Grips                    sell  11550 ->   2994   buy   46200 ->   14970
UPDATE item_template SET sell_price = 2994, buy_price = 14970 WHERE entry = 90290;
-- Heavy Steel Grips              sell  27191 ->   2994   buy  135957 ->   14970
UPDATE item_template SET sell_price = 2994, buy_price = 14970 WHERE entry = 90291;
-- Mithril Grips                  sell  27191 ->   2994   buy  135957 ->   14970
UPDATE item_template SET sell_price = 2994, buy_price = 14970 WHERE entry = 90292;
-- Heavy Mithril Grips            sell  30734 ->   2994   buy  153672 ->   14970
UPDATE item_template SET sell_price = 2994, buy_price = 14970 WHERE entry = 90293;
-- Thorium Grips                  sell  41319 ->   4381   buy  206595 ->   21905
UPDATE item_template SET sell_price = 4381, buy_price = 21905 WHERE entry = 90294;
-- Heavy Thorium Grips            sell  41319 ->   4381   buy  206595 ->   21905
UPDATE item_template SET sell_price = 4381, buy_price = 21905 WHERE entry = 90295;
-- Copper Dirk                    sell    142 ->     80   buy     713 ->     400
UPDATE item_template SET sell_price = 80, buy_price = 400 WHERE entry = 90296;
-- Heavy Copper Dirk              sell    685 ->    188   buy    3428 ->     940
UPDATE item_template SET sell_price = 188, buy_price = 940 WHERE entry = 90297;
-- Bronze Dirk                    sell   1379 ->    730   buy    6896 ->    3650
UPDATE item_template SET sell_price = 730, buy_price = 3650 WHERE entry = 90298;
-- Heavy Bronze Dirk              sell   2731 ->    943   buy   13658 ->    4715
UPDATE item_template SET sell_price = 943, buy_price = 4715 WHERE entry = 90299;
-- Iron Dirk                      sell   4426 ->   1423   buy   22133 ->    7115
UPDATE item_template SET sell_price = 1423, buy_price = 7115 WHERE entry = 90300;
-- Heavy Iron Dirk                sell  11460 ->   3867   buy   57300 ->   19335
UPDATE item_template SET sell_price = 3867, buy_price = 19335 WHERE entry = 90301;
-- Steel Dirk                     sell   3738 ->   3867   buy   18694 ->   19335
UPDATE item_template SET sell_price = 3867, buy_price = 19335 WHERE entry = 90302;
-- Heavy Steel Dirk               sell  15775 ->   3867   buy   78876 ->   19335
UPDATE item_template SET sell_price = 3867, buy_price = 19335 WHERE entry = 90303;
-- Mithril Dirk                   sell  23284 ->   3867   buy  116423 ->   19335
UPDATE item_template SET sell_price = 3867, buy_price = 19335 WHERE entry = 90304;
-- Heavy Mithril Dirk             sell  41319 ->   3867   buy  165277 ->   19335
UPDATE item_template SET sell_price = 3867, buy_price = 19335 WHERE entry = 90305;
-- Thorium Dirk                   sell  43292 ->   3867   buy  216460 ->   19335
UPDATE item_template SET sell_price = 3867, buy_price = 19335 WHERE entry = 90306;
-- Heavy Thorium Dirk             sell  50576 ->   9086   buy  252880 ->   45430
UPDATE item_template SET sell_price = 9086, buy_price = 45430 WHERE entry = 90307;
-- Copper Throwing Knife          sell     20 ->     20   buy      30 ->     100
UPDATE item_template SET sell_price = 20, buy_price = 100 WHERE entry = 90308;
-- Heavy Copper Throwing Knife    sell      0 ->     45   buy       0 ->     225
UPDATE item_template SET sell_price = 45, buy_price = 225 WHERE entry = 90309;
-- Bronze Throwing Knife          sell      0 ->     45   buy       0 ->     225
UPDATE item_template SET sell_price = 45, buy_price = 225 WHERE entry = 90310;
-- Heavy Bronze Throwing Knife    sell      0 ->     45   buy       0 ->     225
UPDATE item_template SET sell_price = 45, buy_price = 225 WHERE entry = 90311;
-- Iron Throwing Knife            sell     90 ->    145   buy     135 ->     725
UPDATE item_template SET sell_price = 145, buy_price = 725 WHERE entry = 90312;
-- Heavy Iron Throwing Knife      sell      9 ->     90   buy     150 ->     450
UPDATE item_template SET sell_price = 90, buy_price = 450 WHERE entry = 90313;
-- Steel Throwing Knife           sell    200 ->    200   buy     300 ->    1000
UPDATE item_template SET sell_price = 200, buy_price = 1000 WHERE entry = 90314;
-- Heavy Steel Throwing Knife     sell      1 ->    200   buy       4 ->    1000
UPDATE item_template SET sell_price = 200, buy_price = 1000 WHERE entry = 90315;
-- Mithril Throwing Knife         sell    350 ->    200   buy   25000 ->    1000
UPDATE item_template SET sell_price = 200, buy_price = 1000 WHERE entry = 90316;
-- Heavy Mithril Throwing Knife   sell    150 ->    200   buy     600 ->    1000
UPDATE item_template SET sell_price = 200, buy_price = 1000 WHERE entry = 90317;
-- Thorium Throwing Knife         sell    150 ->    200   buy     600 ->    1000
UPDATE item_template SET sell_price = 200, buy_price = 1000 WHERE entry = 90318;
-- Heavy Thorium Throwing Knife   sell    400 ->    200   buy     600 ->    1000
UPDATE item_template SET sell_price = 200, buy_price = 1000 WHERE entry = 90319;
-- Copper Handbow                 sell     58 ->    728   buy     294 ->    3640
UPDATE item_template SET sell_price = 728, buy_price = 3640 WHERE entry = 90320;
-- Heavy Bronze Handbow           sell   2546 ->    728   buy   12733 ->    3640
UPDATE item_template SET sell_price = 728, buy_price = 3640 WHERE entry = 90323;
-- Iron Handbow                   sell   2546 ->    728   buy   12733 ->    3640
UPDATE item_template SET sell_price = 728, buy_price = 3640 WHERE entry = 90324;
-- Heavy Iron Handbow             sell   5570 ->    728   buy   27850 ->    3640
UPDATE item_template SET sell_price = 728, buy_price = 3640 WHERE entry = 90325;
-- Steel Handbow                  sell   5570 ->   1833   buy   27850 ->    9165
UPDATE item_template SET sell_price = 1833, buy_price = 9165 WHERE entry = 90326;
-- Heavy Steel Handbow            sell   5570 ->   1833   buy   27850 ->    9165
UPDATE item_template SET sell_price = 1833, buy_price = 9165 WHERE entry = 90327;
-- Mithril Handbow                sell   5570 ->   1833   buy   27850 ->    9165
UPDATE item_template SET sell_price = 1833, buy_price = 9165 WHERE entry = 90328;
-- Heavy Mithril Handbow          sell   5570 ->   2938   buy   27850 ->   14690
UPDATE item_template SET sell_price = 2938, buy_price = 14690 WHERE entry = 90329;
-- Thorium Handbow                sell   5570 ->   2938   buy   27850 ->   14690
UPDATE item_template SET sell_price = 2938, buy_price = 14690 WHERE entry = 90330;
-- Heavy Thorium Handbow          sell   5570 ->   2546   buy   27850 ->   12730
UPDATE item_template SET sell_price = 2546, buy_price = 12730 WHERE entry = 90331;
-- Grand Valor Helm               sell  11861 ->  19377   buy   59309 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90400;
-- Grand Valor Pauldrons          sell  10105 ->  19377   buy   50528 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90401;
-- Grand Valor Chestguard         sell  12938 ->  19377   buy   64694 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90402;
-- Grand Valor Bracers            sell   5982 ->  19377   buy   23928 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90403;
-- Grand Valor Gauntlets          sell   6867 ->  19377   buy   34337 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90404;
-- Grand Valor Girdle             sell   7055 ->  19377   buy   28220 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90405;
-- Grand Valor Legguards          sell  12926 ->  19377   buy   64634 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90406;
-- Grand Valor Boots              sell  10486 ->  19377   buy   52430 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90407;
-- Hallowed Valor Helm            sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90408;
-- Hallowed Valor Pauldrons       sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90409;
-- Hallowed Valor Chestguard      sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90410;
-- Hallowed Valor Bracers         sell  17699 ->  33804   buy   88497 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90411;
-- Hallowed Valor Gauntlets       sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90412;
-- Hallowed Valor Girdle          sell  16334 ->  33804   buy   81672 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90413;
-- Hallowed Valor Legguards       sell  33269 ->  33804   buy  166347 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90414;
-- Hallowed Valor Boots           sell  17205 ->  33804   buy   86028 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90415;
-- Grand Bastion Helm             sell  11861 ->  19377   buy   59309 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90416;
-- Grand Bastion Pauldrons        sell  10105 ->  19377   buy   50528 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90417;
-- Grand Bastion Chestguard       sell  12938 ->  19377   buy   64694 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90418;
-- Grand Bastion Bracers          sell   5982 ->  19377   buy   23928 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90419;
-- Grand Bastion Gauntlets        sell   6867 ->  19377   buy   34337 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90420;
-- Grand Bastion Girdle           sell   7055 ->  19377   buy   28220 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90421;
-- Grand Bastion Legguards        sell  12926 ->  19377   buy   64634 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90422;
-- Grand Bastion Boots            sell  10486 ->  19377   buy   52430 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90423;
-- Hallowed Bastion Helm          sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90424;
-- Hallowed Bastion Pauldrons     sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90425;
-- Hallowed Bastion Chestguard    sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90426;
-- Hallowed Bastion Bracers       sell  17699 ->  33804   buy   88497 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90427;
-- Hallowed Bastion Gauntlets     sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90428;
-- Hallowed Bastion Girdle        sell  16334 ->  33804   buy   81672 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90429;
-- Hallowed Bastion Legguards     sell  33269 ->  33804   buy  166347 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90430;
-- Hallowed Bastion Boots         sell  17205 ->  33804   buy   86028 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90431;
-- Grand Dawn Helm                sell  11861 ->  19377   buy   59309 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90432;
-- Grand Dawn Pauldrons           sell  10105 ->  19377   buy   50528 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90433;
-- Grand Dawn Chestguard          sell  12938 ->  19377   buy   64694 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90434;
-- Grand Dawn Bracers             sell   5982 ->  19377   buy   23928 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90435;
-- Grand Dawn Gauntlets           sell   6867 ->  19377   buy   34337 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90436;
-- Grand Dawn Girdle              sell   7055 ->  19377   buy   28220 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90437;
-- Grand Dawn Legguards           sell  12926 ->  19377   buy   64634 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90438;
-- Grand Dawn Boots               sell  10486 ->  19377   buy   52430 ->   96885
UPDATE item_template SET sell_price = 19377, buy_price = 96885 WHERE entry = 90439;
-- Hallowed Dawn Helm             sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90440;
-- Hallowed Dawn Pauldrons        sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90441;
-- Hallowed Dawn Chestguard       sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90442;
-- Hallowed Dawn Bracers          sell  17699 ->  33804   buy   88497 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90443;
-- Hallowed Dawn Gauntlets        sell  25000 ->  33804   buy  100000 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90444;
-- Hallowed Dawn Girdle           sell  16334 ->  33804   buy   81672 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90445;
-- Hallowed Dawn Legguards        sell  33269 ->  33804   buy  166347 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90446;
-- Hallowed Dawn Boots            sell  17205 ->  33804   buy   86028 ->  169020
UPDATE item_template SET sell_price = 33804, buy_price = 169020 WHERE entry = 90447;
-- Hunt Helm                      sell   3900 ->    818   buy   15601 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90448;
-- Hunt Pauldrons                 sell    485 ->    818   buy    2428 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90449;
-- Hunt Chestguard                sell    711 ->    818   buy    3555 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90450;
-- Hunt Bracers                   sell    336 ->    818   buy    1684 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90451;
-- Hunt Gauntlets                 sell    557 ->    818   buy    2788 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90452;
-- Hunt Girdle                    sell    572 ->    818   buy    2861 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90453;
-- Hunt Legguards                 sell    645 ->    818   buy    3229 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90454;
-- Hunt Boots                     sell    488 ->    818   buy    2441 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90455;
-- Fine Hunt Helm                 sell   5646 ->   6081   buy   22584 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90456;
-- Fine Hunt Pauldrons            sell   4738 ->   6081   buy   23693 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90457;
-- Fine Hunt Chestguard           sell   6488 ->   6081   buy   32440 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90458;
-- Fine Hunt Bracers              sell   4000 ->   6081   buy   16000 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90459;
-- Fine Hunt Gauntlets            sell   4041 ->   6081   buy   16166 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90460;
-- Fine Hunt Girdle               sell   3294 ->   6081   buy   16474 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90461;
-- Fine Hunt Legguards            sell   6753 ->   6081   buy   33766 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90462;
-- Fine Hunt Boots                sell   5221 ->   6081   buy   26105 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90463;
-- Grand Hunt Helm                sell  15785 ->  28019   buy   78925 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90464;
-- Grand Hunt Pauldrons           sell  14551 ->  28019   buy   72757 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90465;
-- Grand Hunt Chestguard          sell  20233 ->  28019   buy  101168 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90466;
-- Grand Hunt Bracers             sell  10406 ->  28019   buy   52034 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90467;
-- Grand Hunt Gauntlets           sell  12590 ->  28019   buy   62954 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90468;
-- Grand Hunt Girdle              sell  10113 ->  28019   buy   50568 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90469;
-- Grand Hunt Legguards           sell  20358 ->  28019   buy  101790 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90470;
-- Grand Hunt Boots               sell  10681 ->  28019   buy   42724 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90471;
-- Hallowed Hunt Helm             sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90472;
-- Hallowed Hunt Pauldrons        sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90473;
-- Hallowed Hunt Chestguard       sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90474;
-- Hallowed Hunt Bracers          sell  24220 ->  47500   buy  121103 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90475;
-- Hallowed Hunt Gauntlets        sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90476;
-- Hallowed Hunt Girdle           sell  33708 ->  47500   buy  168542 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90477;
-- Hallowed Hunt Legguards        sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90478;
-- Hallowed Hunt Boots            sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90479;
-- Tempest Helm                   sell   3900 ->    818   buy   15601 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90480;
-- Tempest Pauldrons              sell    485 ->    818   buy    2428 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90481;
-- Tempest Chestguard             sell    711 ->    818   buy    3555 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90482;
-- Tempest Bracers                sell    336 ->    818   buy    1684 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90483;
-- Tempest Gauntlets              sell    557 ->    818   buy    2788 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90484;
-- Tempest Girdle                 sell    572 ->    818   buy    2861 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90485;
-- Tempest Legguards              sell    645 ->    818   buy    3229 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90486;
-- Tempest Boots                  sell    488 ->    818   buy    2441 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90487;
-- Fine Tempest Helm              sell   5646 ->   6081   buy   22584 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90488;
-- Fine Tempest Pauldrons         sell   4738 ->   6081   buy   23693 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90489;
-- Fine Tempest Chestguard        sell   6488 ->   6081   buy   32440 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90490;
-- Fine Tempest Bracers           sell   4000 ->   6081   buy   16000 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90491;
-- Fine Tempest Gauntlets         sell   4041 ->   6081   buy   16166 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90492;
-- Fine Tempest Girdle            sell   3294 ->   6081   buy   16474 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90493;
-- Fine Tempest Legguards         sell   6753 ->   6081   buy   33766 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90494;
-- Fine Tempest Boots             sell   5221 ->   6081   buy   26105 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90495;
-- Grand Tempest Helm             sell  15785 ->  28019   buy   78925 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90496;
-- Grand Tempest Pauldrons        sell  14551 ->  28019   buy   72757 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90497;
-- Grand Tempest Chestguard       sell  20233 ->  28019   buy  101168 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90498;
-- Grand Tempest Bracers          sell  10406 ->  28019   buy   52034 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90499;
-- Grand Tempest Gauntlets        sell  12590 ->  28019   buy   62954 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90500;
-- Grand Tempest Girdle           sell  10113 ->  28019   buy   50568 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90501;
-- Grand Tempest Legguards        sell  20358 ->  28019   buy  101790 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90502;
-- Grand Tempest Boots            sell  10681 ->  28019   buy   42724 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90503;
-- Hallowed Tempest Helm          sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90504;
-- Hallowed Tempest Pauldrons     sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90505;
-- Hallowed Tempest Chestguard    sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90506;
-- Hallowed Tempest Bracers       sell  24220 ->  47500   buy  121103 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90507;
-- Hallowed Tempest Gauntlets     sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90508;
-- Hallowed Tempest Girdle        sell  33708 ->  47500   buy  168542 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90509;
-- Hallowed Tempest Legguards     sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90510;
-- Hallowed Tempest Boots         sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90511;
-- Tide Helm                      sell   3900 ->    818   buy   15601 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90512;
-- Tide Pauldrons                 sell    485 ->    818   buy    2428 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90513;
-- Tide Chestguard                sell    711 ->    818   buy    3555 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90514;
-- Tide Bracers                   sell    336 ->    818   buy    1684 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90515;
-- Tide Gauntlets                 sell    557 ->    818   buy    2788 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90516;
-- Tide Girdle                    sell    572 ->    818   buy    2861 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90517;
-- Tide Legguards                 sell    645 ->    818   buy    3229 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90518;
-- Tide Boots                     sell    488 ->    818   buy    2441 ->    4090
UPDATE item_template SET sell_price = 818, buy_price = 4090 WHERE entry = 90519;
-- Fine Tide Helm                 sell   5646 ->   6081   buy   22584 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90520;
-- Fine Tide Pauldrons            sell   4738 ->   6081   buy   23693 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90521;
-- Fine Tide Chestguard           sell   6488 ->   6081   buy   32440 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90522;
-- Fine Tide Bracers              sell   4000 ->   6081   buy   16000 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90523;
-- Fine Tide Gauntlets            sell   4041 ->   6081   buy   16166 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90524;
-- Fine Tide Girdle               sell   3294 ->   6081   buy   16474 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90525;
-- Fine Tide Legguards            sell   6753 ->   6081   buy   33766 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90526;
-- Fine Tide Boots                sell   5221 ->   6081   buy   26105 ->   30405
UPDATE item_template SET sell_price = 6081, buy_price = 30405 WHERE entry = 90527;
-- Grand Tide Helm                sell  15785 ->  28019   buy   78925 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90528;
-- Grand Tide Pauldrons           sell  14551 ->  28019   buy   72757 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90529;
-- Grand Tide Chestguard          sell  20233 ->  28019   buy  101168 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90530;
-- Grand Tide Bracers             sell  10406 ->  28019   buy   52034 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90531;
-- Grand Tide Gauntlets           sell  12590 ->  28019   buy   62954 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90532;
-- Grand Tide Girdle              sell  10113 ->  28019   buy   50568 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90533;
-- Grand Tide Legguards           sell  20358 ->  28019   buy  101790 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90534;
-- Grand Tide Boots               sell  10681 ->  28019   buy   42724 ->  140095
UPDATE item_template SET sell_price = 28019, buy_price = 140095 WHERE entry = 90535;
-- Hallowed Tide Helm             sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90536;
-- Hallowed Tide Pauldrons        sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90537;
-- Hallowed Tide Chestguard       sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90538;
-- Hallowed Tide Bracers          sell  24220 ->  47500   buy  121103 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90539;
-- Hallowed Tide Gauntlets        sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90540;
-- Hallowed Tide Girdle           sell  33708 ->  47500   buy  168542 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90541;
-- Hallowed Tide Legguards        sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90542;
-- Hallowed Tide Boots            sell  22500 ->  47500   buy   90000 ->  237500
UPDATE item_template SET sell_price = 47500, buy_price = 237500 WHERE entry = 90543;
-- Shadow Helm                    sell   2125 ->    689   buy    8500 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90544;
-- Shadow Pauldrons               sell    409 ->    689   buy    2045 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90545;
-- Shadow Chestguard              sell    574 ->    689   buy    2870 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90546;
-- Shadow Bracers                 sell    472 ->    689   buy    2360 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90547;
-- Shadow Gauntlets               sell    282 ->    689   buy    1413 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90548;
-- Shadow Girdle                  sell    447 ->    689   buy    2235 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90549;
-- Shadow Legguards               sell    929 ->    689   buy    4646 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90550;
-- Shadow Boots                   sell    422 ->    689   buy    2112 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90551;
-- Fine Shadow Helm               sell   3991 ->   4174   buy   19956 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90552;
-- Fine Shadow Pauldrons          sell   4320 ->   4174   buy   21602 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90553;
-- Fine Shadow Chestguard         sell   8072 ->   4174   buy   32289 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90554;
-- Fine Shadow Bracers            sell   2675 ->   4174   buy   13377 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90555;
-- Fine Shadow Gauntlets          sell   3321 ->   4174   buy   16608 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90556;
-- Fine Shadow Girdle             sell   2804 ->   4174   buy   14022 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90557;
-- Fine Shadow Legguards          sell   5250 ->   4174   buy   26251 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90558;
-- Fine Shadow Boots              sell   3054 ->   4174   buy   12216 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90559;
-- Grand Shadow Helm              sell  14454 ->  23347   buy   72270 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90560;
-- Grand Shadow Pauldrons         sell  12124 ->  23347   buy   60620 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90561;
-- Grand Shadow Chestguard        sell  16287 ->  23347   buy   81437 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90562;
-- Grand Shadow Bracers           sell   7988 ->  23347   buy   39940 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90563;
-- Grand Shadow Gauntlets         sell   8182 ->  23347   buy   40910 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90564;
-- Grand Shadow Girdle            sell   8024 ->  23347   buy   40120 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90565;
-- Grand Shadow Legguards         sell  16233 ->  23347   buy   81169 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90566;
-- Grand Shadow Boots             sell  13012 ->  23347   buy   65062 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90567;
-- Hallowed Shadow Helm           sell  15438 ->  45000   buy   77190 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90568;
-- Hallowed Shadow Pauldrons      sell  15854 ->  45000   buy   79271 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90569;
-- Hallowed Shadow Chestguard     sell  20000 ->  45000   buy   80000 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90570;
-- Hallowed Shadow Bracers        sell  20183 ->  45000   buy  100919 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90571;
-- Hallowed Shadow Gauntlets      sell  20262 ->  45000   buy  101314 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90572;
-- Hallowed Shadow Girdle         sell  21845 ->  45000   buy  109226 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90573;
-- Hallowed Shadow Legguards      sell  20000 ->  45000   buy   80000 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90574;
-- Hallowed Shadow Boots          sell  20647 ->  45000   buy  103238 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90575;
-- Grove Helm                     sell   2125 ->    689   buy    8500 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90576;
-- Grove Pauldrons                sell    409 ->    689   buy    2045 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90577;
-- Grove Chestguard               sell    574 ->    689   buy    2870 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90578;
-- Grove Bracers                  sell    472 ->    689   buy    2360 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90579;
-- Grove Gauntlets                sell    282 ->    689   buy    1413 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90580;
-- Grove Girdle                   sell    447 ->    689   buy    2235 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90581;
-- Grove Legguards                sell    929 ->    689   buy    4646 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90582;
-- Grove Boots                    sell    422 ->    689   buy    2112 ->    3445
UPDATE item_template SET sell_price = 689, buy_price = 3445 WHERE entry = 90583;
-- Fine Grove Helm                sell   3991 ->   4174   buy   19956 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90584;
-- Fine Grove Pauldrons           sell   4320 ->   4174   buy   21602 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90585;
-- Fine Grove Chestguard          sell   8072 ->   4174   buy   32289 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90586;
-- Fine Grove Bracers             sell   2675 ->   4174   buy   13377 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90587;
-- Fine Grove Gauntlets           sell   3321 ->   4174   buy   16608 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90588;
-- Fine Grove Girdle              sell   2804 ->   4174   buy   14022 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90589;
-- Fine Grove Legguards           sell   5250 ->   4174   buy   26251 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90590;
-- Fine Grove Boots               sell   3054 ->   4174   buy   12216 ->   20870
UPDATE item_template SET sell_price = 4174, buy_price = 20870 WHERE entry = 90591;
-- Grand Grove Helm               sell  14454 ->  23347   buy   72270 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90592;
-- Grand Grove Pauldrons          sell  12124 ->  23347   buy   60620 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90593;
-- Grand Grove Chestguard         sell  16287 ->  23347   buy   81437 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90594;
-- Grand Grove Bracers            sell   7988 ->  23347   buy   39940 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90595;
-- Grand Grove Gauntlets          sell   8182 ->  23347   buy   40910 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90596;
-- Grand Grove Girdle             sell   8024 ->  23347   buy   40120 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90597;
-- Grand Grove Legguards          sell  16233 ->  23347   buy   81169 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90598;
-- Grand Grove Boots              sell  13012 ->  23347   buy   65062 ->  116735
UPDATE item_template SET sell_price = 23347, buy_price = 116735 WHERE entry = 90599;
-- Hallowed Grove Helm            sell  15438 ->  45000   buy   77190 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90600;
-- Hallowed Grove Pauldrons       sell  15854 ->  45000   buy   79271 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90601;
-- Hallowed Grove Chestguard      sell  20000 ->  45000   buy   80000 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90602;
-- Hallowed Grove Bracers         sell  20183 ->  45000   buy  100919 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90603;
-- Hallowed Grove Gauntlets       sell  20262 ->  45000   buy  101314 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90604;
-- Hallowed Grove Girdle          sell  21845 ->  45000   buy  109226 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90605;
-- Hallowed Grove Legguards       sell  20000 ->  45000   buy   80000 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90606;
-- Hallowed Grove Boots           sell  20647 ->  45000   buy  103238 ->  225000
UPDATE item_template SET sell_price = 45000, buy_price = 225000 WHERE entry = 90607;
-- Runeweave Helm                 sell    408 ->    563   buy    2043 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90608;
-- Runeweave Pauldrons            sell    346 ->    563   buy    1730 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90609;
-- Runeweave Chestguard           sell    454 ->    563   buy    2270 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90610;
-- Runeweave Bracers              sell    217 ->    563   buy    1085 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90611;
-- Runeweave Gauntlets            sell    229 ->    563   buy    1147 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90612;
-- Runeweave Girdle               sell    361 ->    563   buy    1809 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90613;
-- Runeweave Legguards            sell    455 ->    563   buy    2278 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90614;
-- Runeweave Boots                sell    570 ->    563   buy    2852 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90615;
-- Fine Runeweave Helm            sell   3396 ->   3866   buy   16983 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90616;
-- Fine Runeweave Pauldrons       sell   3406 ->   3866   buy   17033 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90617;
-- Fine Runeweave Chestguard      sell   6644 ->   3866   buy   26577 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90618;
-- Fine Runeweave Bracers         sell   2294 ->   3866   buy   11473 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90619;
-- Fine Runeweave Gauntlets       sell   2146 ->   3866   buy   10734 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90620;
-- Fine Runeweave Girdle          sell      0 ->   3866   buy       0 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90621;
-- Fine Runeweave Legguards       sell   5094 ->   3866   buy   25470 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90622;
-- Fine Runeweave Boots           sell   3146 ->   3866   buy   15733 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90623;
-- Grand Runeweave Helm           sell   9857 ->  19312   buy   49287 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90624;
-- Grand Runeweave Pauldrons      sell   9574 ->  19312   buy   47873 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90625;
-- Grand Runeweave Chestguard     sell  12922 ->  19312   buy   64614 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90626;
-- Grand Runeweave Bracers        sell   6637 ->  19312   buy   33186 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90627;
-- Grand Runeweave Gauntlets      sell   6517 ->  19312   buy   32587 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90628;
-- Grand Runeweave Girdle         sell   6866 ->  19312   buy   34334 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90629;
-- Grand Runeweave Legguards      sell  13683 ->  19312   buy   68415 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90630;
-- Grand Runeweave Boots          sell  12375 ->  19312   buy   61875 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90631;
-- Hallowed Runeweave Helm        sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90632;
-- Hallowed Runeweave Pauldrons   sell  12964 ->  35068   buy   64821 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90633;
-- Hallowed Runeweave Chestguard  sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90634;
-- Hallowed Runeweave Bracers     sell  17509 ->  35068   buy   87549 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90635;
-- Hallowed Runeweave Gauntlets   sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90636;
-- Hallowed Runeweave Girdle      sell  21611 ->  35068   buy  108057 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90637;
-- Hallowed Runeweave Legguards   sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90638;
-- Hallowed Runeweave Boots       sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90639;
-- Vestment Helm                  sell    408 ->    563   buy    2043 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90640;
-- Vestment Pauldrons             sell    346 ->    563   buy    1730 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90641;
-- Vestment Chestguard            sell    454 ->    563   buy    2270 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90642;
-- Vestment Bracers               sell    217 ->    563   buy    1085 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90643;
-- Vestment Gauntlets             sell    229 ->    563   buy    1147 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90644;
-- Vestment Girdle                sell    361 ->    563   buy    1809 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90645;
-- Vestment Legguards             sell    455 ->    563   buy    2278 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90646;
-- Vestment Boots                 sell    570 ->    563   buy    2852 ->    2815
UPDATE item_template SET sell_price = 563, buy_price = 2815 WHERE entry = 90647;
-- Fine Vestment Helm             sell   3396 ->   3866   buy   16983 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90648;
-- Fine Vestment Pauldrons        sell   3406 ->   3866   buy   17033 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90649;
-- Fine Vestment Chestguard       sell   6644 ->   3866   buy   26577 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90650;
-- Fine Vestment Bracers          sell   2294 ->   3866   buy   11473 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90651;
-- Fine Vestment Gauntlets        sell   2146 ->   3866   buy   10734 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90652;
-- Fine Vestment Girdle           sell      0 ->   3866   buy       0 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90653;
-- Fine Vestment Legguards        sell   5094 ->   3866   buy   25470 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90654;
-- Fine Vestment Boots            sell   3146 ->   3866   buy   15733 ->   19330
UPDATE item_template SET sell_price = 3866, buy_price = 19330 WHERE entry = 90655;
-- Grand Vestment Helm            sell   9857 ->  19312   buy   49287 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90656;
-- Grand Vestment Pauldrons       sell   9574 ->  19312   buy   47873 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90657;
-- Grand Vestment Chestguard      sell  12922 ->  19312   buy   64614 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90658;
-- Grand Vestment Bracers         sell   6637 ->  19312   buy   33186 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90659;
-- Grand Vestment Gauntlets       sell   6517 ->  19312   buy   32587 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90660;
-- Grand Vestment Girdle          sell   6866 ->  19312   buy   34334 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90661;
-- Grand Vestment Legguards       sell  13683 ->  19312   buy   68415 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90662;
-- Grand Vestment Boots           sell  12375 ->  19312   buy   61875 ->   96560
UPDATE item_template SET sell_price = 19312, buy_price = 96560 WHERE entry = 90663;
-- Hallowed Vestment Helm         sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90664;
-- Hallowed Vestment Pauldrons    sell  12964 ->  35068   buy   64821 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90665;
-- Hallowed Vestment Chestguard   sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90666;
-- Hallowed Vestment Bracers      sell  17509 ->  35068   buy   87549 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90667;
-- Hallowed Vestment Gauntlets    sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90668;
-- Hallowed Vestment Girdle       sell  21611 ->  35068   buy  108057 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90669;
-- Hallowed Vestment Legguards    sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90670;
-- Hallowed Vestment Boots        sell  15000 ->  35068   buy   60000 ->  175340
UPDATE item_template SET sell_price = 35068, buy_price = 175340 WHERE entry = 90671;

SELECT COUNT(*) AS repriced FROM item_template WHERE entry BETWEEN 90100 AND 90719 AND sell_price > 0;
