-- ---------------------------------------------------------------------------------------
-- Class trainers (2600200-2600208) and profession masters (2600300-2600313).
--
-- Run against tw_world. IDEMPOTENT. Requires a mangosd RESTART.
-- Summon with `.npc summon <entry>`.
-- GENERATED by scratchpad/gen_npcs.py - edit that and regenerate, not this file.
--
-- WHY ONE NPC PER CLASS
--   Creature::IsTrainerOf enforces an exact match for TRAINER_TYPE_CLASS:
--       if (pPlayer->GetClass() != GetCreatureInfo()->trainer_class) ...refuse...
--   No bypass exists, so a single all-class trainer is impossible. Nine NPCs.
--
--   The profession gate is looser:
--       if (GetCreatureInfo()->trainer_spell && !pPlayer->HasSpell(...)) ...refuse...
--   Note `trainer_spell &&` - setting it to 0 skips the check entirely, so a profession
--   master serves anyone. That also keeps these working if the start-with-professions
--   grant is ever reverted.
--
-- NPC FLAGS IN THIS CORE (UnitDefines.h:446-450)
--   GOSSIP 0x01, QUESTGIVER 0x02, VENDOR 0x04, TRAINER 0x10.
--   19 = gossip+questgiver+trainer, matching the stock warrior trainers.
--   23 = that plus vendor, for the profession masters.
--   VENDOR is 0x04 here, NOT stock MaNGOS's 0x80 - using 0x80 gives an NPC whose vendor
--   window silently never opens.
--
-- WHY CLONE-THEN-UPDATE
--   A first attempt enumerated creature_template's columns in INSERT..SELECT and failed:
--   this core has display_id1, not modelid_1. Cloning the whole row with LIKE + SELECT *
--   and then UPDATEing only the fields that differ needs no column list at all.
--
-- NO TRAINER LIST CAP
--   Unlike vendors (MAX_VENDOR_ITEMS 128, which truncates silently), SMSG_TRAINER_LIST
--   carries a uint32 count and the core imposes no limit, so ~190 spells is fine.
-- ---------------------------------------------------------------------------------------

USE tw_world;

DELETE FROM creature_template          WHERE entry BETWEEN 2600200 AND 2600399;
DELETE FROM npc_trainer                WHERE entry BETWEEN 2600200 AND 2600399;
DELETE FROM npc_vendor                 WHERE entry BETWEEN 2600200 AND 2600399;
DELETE FROM creature_questrelation     WHERE id    BETWEEN 2600200 AND 2600399;
DELETE FROM creature_involvedrelation  WHERE id    BETWEEN 2600200 AND 2600399;

DROP TEMPORARY TABLE IF EXISTS tmp_npc;
CREATE TEMPORARY TABLE tmp_npc LIKE creature_template;

-- ---------------------------------------------------------------------------------------
-- 1. The NPCs themselves, each a clone of template 21002 with its identity corrected.
-- ---------------------------------------------------------------------------------------
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600200, name='Warrior Master', subname='Class Trainer & Quests',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=1,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=7166, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600201, name='Paladin Master', subname='Class Trainer & Quests',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=2,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=1299, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600202, name='Hunter Master', subname='Class Trainer & Quests',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=3,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=2879, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600203, name='Rogue Master', subname='Class Trainer & Quests',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=4,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=15300, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600204, name='Priest Master', subname='Class Trainer & Quests',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=5,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=2200, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600205, name='Shaman Master', subname='Class Trainer & Quests',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=7,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=3746, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600206, name='Mage Master', subname='Class Trainer & Quests',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=8,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=3108, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600207, name='Warlock Master', subname='Class Trainer & Quests',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=9,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=9780, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600208, name='Druid Master', subname='Class Trainer & Quests',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=11,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=1824, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600300, name='Blacksmithing Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=3549, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600301, name='Leatherworking Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=10620, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600302, name='Alchemy Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=2624, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600303, name='Tailoring Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=2575, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600304, name='Engineering Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=10454, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600305, name='Enchanting Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=2101, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600306, name='Jewelcrafting Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=3360, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600307, name='Cooking Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=2662, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600308, name='First Aid Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=3469, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600309, name='Mining Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=7341, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600310, name='Herbalism Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=3445, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600311, name='Skinning Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=4986, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600312, name='Fishing Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=3470, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600313, name='Survivalist Master', subname='Trainer, Supplies & Quests',
  npc_flags=23, faction=35, trainer_type=2, trainer_class=0,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=6554, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600209, name='Pet Master', subname='Pet Trainer & Stable Master',
  npc_flags=8211, faction=35, trainer_type=3, trainer_class=3,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=4295, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;
DELETE FROM tmp_npc;
INSERT INTO tmp_npc SELECT * FROM creature_template WHERE entry = 21002;
UPDATE tmp_npc SET entry=2600210, name='Demon Master', subname='Warlock Demon Trainer',
  npc_flags=19, faction=35, trainer_type=0, trainer_class=9,
  trainer_spell=0, trainer_id=0, vendor_id=0,
  display_id1=5087, display_id2=0, display_id3=0, display_id4=0;
INSERT INTO creature_template SELECT * FROM tmp_npc;

-- ---------------------------------------------------------------------------------------
-- 2. Definition tables driving everything below.
-- ---------------------------------------------------------------------------------------
DROP TEMPORARY TABLE IF EXISTS tmp_class;
CREATE TEMPORARY TABLE tmp_class (entry MEDIUMINT UNSIGNED PRIMARY KEY,
  cls TINYINT UNSIGNED, mask INT UNSIGNED) ENGINE=MEMORY;
INSERT INTO tmp_class VALUES
  (2600200,1,1),
  (2600201,2,2),
  (2600202,3,4),
  (2600203,4,8),
  (2600204,5,16),
  (2600205,7,64),
  (2600206,8,128),
  (2600207,9,256),
  (2600208,11,1024);

DROP TEMPORARY TABLE IF EXISTS tmp_prof;
CREATE TEMPORARY TABLE tmp_prof (entry MEDIUMINT UNSIGNED PRIMARY KEY,
  skill SMALLINT UNSIGNED) ENGINE=MEMORY;
INSERT INTO tmp_prof VALUES
  (2600300,164),
  (2600301,165),
  (2600302,171),
  (2600303,197),
  (2600304,202),
  (2600305,333),
  (2600306,755),
  (2600307,185),
  (2600308,129),
  (2600309,186),
  (2600310,182),
  (2600311,393),
  (2600312,356),
  (2600313,142);

-- Every spell any trainer in the world teaches, from both storage shapes.
DROP TEMPORARY TABLE IF EXISTS tmp_taught;
CREATE TEMPORARY TABLE tmp_taught (npc MEDIUMINT UNSIGNED, spell MEDIUMINT UNSIGNED,
  cost INT UNSIGNED, reqlevel TINYINT UNSIGNED,
  reqskill SMALLINT UNSIGNED, reqskillvalue SMALLINT UNSIGNED,
  KEY(npc), KEY(spell)) ENGINE=MEMORY;
INSERT INTO tmp_taught SELECT entry, spell, spellcost, reqlevel, reqskill, reqskillvalue
FROM npc_trainer WHERE entry NOT BETWEEN 2600200 AND 2600399;
INSERT INTO tmp_taught SELECT ct.entry, ntt.spell, ntt.spellcost, ntt.reqlevel,
       ntt.reqskill, ntt.reqskillvalue
FROM creature_template ct JOIN npc_trainer_template ntt ON ntt.entry = ct.trainer_id
WHERE ct.trainer_id > 0;

-- ---------------------------------------------------------------------------------------
-- 3. Class trainers: the union of every spell taught by any trainer of that class.
--    reqlevel is carried through so a low-level character still sees a sensible list
--    rather than everything at once.
--    Source trainers exclude our own range, so re-running cannot feed on itself.
-- ---------------------------------------------------------------------------------------
INSERT IGNORE INTO npc_trainer (entry, spell, spellcost, reqskill, reqskillvalue, reqlevel)
SELECT c.entry, t.spell, MIN(t.cost), 0, 0, MIN(t.reqlevel)
FROM tmp_class c
JOIN creature_template src ON src.trainer_type = 0 AND src.trainer_class = c.cls
                          AND src.entry NOT BETWEEN 2600200 AND 2600399
JOIN tmp_taught t ON t.npc = src.entry
GROUP BY c.entry, t.spell;

-- ---------------------------------------------------------------------------------------
-- 4. Profession masters: what each profession's trainers actually teach.
--
--    NOT via skill_line_ability alone. That table covers recipes only PARTIALLY here:
--    it has 146 rows for Alchemy, but the specific spells a real Alchemy trainer teaches
--    (Lesser Healing Potion at 2337 vs 2341, and so on) are largely absent, so joining
--    through it produced profession masters that taught almost nothing.
--
--    Nor via creature_template.trainer_spell, which is 0 on 374 of the 400-odd tradeskill
--    trainers, so it identifies almost nothing.
--
--    Two signals are combined instead, because neither is complete on its own:
--      (a) npc_trainer.reqskill - set on the recipes that need a skill level, and it names
--          the profession directly. Covers the mid and high ranks.
--      (b) the teaching NPC's subname - catches the early recipes, which have reqskill 0
--          because they need no skill and so are invisible to (a).
-- ---------------------------------------------------------------------------------------
DROP TEMPORARY TABLE IF EXISTS tmp_prof_npc;
CREATE TEMPORARY TABLE tmp_prof_npc (skill SMALLINT UNSIGNED, npc MEDIUMINT UNSIGNED,
  PRIMARY KEY(skill, npc)) ENGINE=MEMORY;

INSERT IGNORE INTO tmp_prof_npc (skill, npc)
SELECT x.skill, ct.entry
FROM creature_template ct
JOIN (SELECT 164 AS skill, 'Blacksmith|Weaponsmith|Armorsmith' AS pat
      UNION ALL SELECT 165, 'Leatherwork'
      UNION ALL SELECT 171, 'Alchem'
      UNION ALL SELECT 197, 'Tailor'
      UNION ALL SELECT 202, 'Engineer'
      UNION ALL SELECT 333, 'Enchant'
      UNION ALL SELECT 755, 'Jewel'
      UNION ALL SELECT 185, 'Cook'
      UNION ALL SELECT 129, 'First Aid'
      UNION ALL SELECT 186, 'Mining|Miner'
      UNION ALL SELECT 182, 'Herbal'
      UNION ALL SELECT 393, 'Skinning'
      UNION ALL SELECT 356, 'Fishing'
      UNION ALL SELECT 142, 'Survival') x
  ON ct.subname REGEXP x.pat
WHERE ct.trainer_type = 2 AND ct.entry NOT BETWEEN 2600200 AND 2600399;

--    THE REQUIREMENTS MUST BE CARRIED THROUGH, NOT ZEROED.
--    An earlier version inserted `0, 0, 0` for reqskill/reqskillvalue/reqlevel, and the
--    result was a trainer where every recipe showed as available and nothing sorted.
--    Player::GetTrainerSpellState gates on precisely those fields:
--        if (trainer_spell->reqSkill &&
--            GetSkillValueBase(trainer_spell->reqSkill) < trainer_spell->reqSkillValue)
--            return TRAINER_SPELL_RED;
--    With reqSkill 0 the check is skipped entirely and everything comes back green.
--
--    MAX is used for the skill requirement so that if one source NPC lists a recipe with
--    a requirement and another lists it without, the stricter one wins - that keeps the
--    list sorted the way a normal trainer does. MIN is used for cost and level, which is
--    the friendlier direction for those.

-- (a) by declared required skill
INSERT IGNORE INTO npc_trainer (entry, spell, spellcost, reqskill, reqskillvalue, reqlevel)
SELECT p.entry, nt.spell, MIN(nt.spellcost),
       p.skill, MAX(nt.reqskillvalue), MIN(nt.reqlevel)
FROM tmp_prof p
JOIN npc_trainer nt ON nt.reqskill = p.skill
WHERE nt.entry NOT BETWEEN 2600200 AND 2600399
GROUP BY p.entry, nt.spell;

-- (b) by teaching NPC, for the early recipes that declare no skill requirement
INSERT IGNORE INTO npc_trainer (entry, spell, spellcost, reqskill, reqskillvalue, reqlevel)
SELECT p.entry, t.spell, MIN(t.cost),
       MAX(t.reqskill), MAX(t.reqskillvalue), MIN(t.reqlevel)
FROM tmp_prof p
JOIN tmp_prof_npc pn ON pn.skill = p.skill
JOIN tmp_taught t ON t.npc = pn.npc
GROUP BY p.entry, t.spell;

-- ---------------------------------------------------------------------------------------
-- 4b. Pet trainer (2600209) and demon trainer (2600210).
--
--     The pet trainer takes the union of every genuine TRAINER_TYPE_PETS spell - Growl,
--     the Pet Hardiness ranks and so on. The core hard-gates type 3 to hunters.
--
--     The demon trainer has far less to offer, and that is not a fault in this script:
--     only three demon spells are trainer-taught in vanilla (Demon Armor, Sense Demons,
--     Enslave Demon). The actual summons - Imp, Voidwalker, Succubus, Felhunter - are
--     QUEST rewards, so the demon quests are attached below and the Warlock Master
--     (2600207) already carries all 171 warlock quests including them.
-- ---------------------------------------------------------------------------------------
INSERT IGNORE INTO npc_trainer (entry, spell, spellcost, reqskill, reqskillvalue, reqlevel)
SELECT 2600209, nt.spell, MIN(nt.spellcost), MAX(nt.reqskill), MAX(nt.reqskillvalue), MIN(nt.reqlevel)
FROM npc_trainer nt JOIN creature_template ct ON ct.entry = nt.entry
WHERE ct.trainer_type = 3 AND ct.entry NOT BETWEEN 2600200 AND 2600399
GROUP BY nt.spell;

INSERT IGNORE INTO npc_trainer (entry, spell, spellcost, reqskill, reqskillvalue, reqlevel)
SELECT 2600210, nt.spell, MIN(nt.spellcost), MAX(nt.reqskill), MAX(nt.reqskillvalue), MIN(nt.reqlevel)
FROM npc_trainer nt
JOIN spell_template st ON st.entry = nt.spell
JOIN creature_template ct ON ct.entry = nt.entry
WHERE ct.trainer_type = 0 AND ct.trainer_class = 9
  AND ct.entry NOT BETWEEN 2600200 AND 2600399
  AND st.name REGEXP 'Imp|Voidwalker|Succubus|Felhunter|Infernal|Doomguard|Demon|Fel |Soul Link|Sacrifice|Soulstone|Health Funnel|Blood Pact'
GROUP BY nt.spell;

INSERT IGNORE INTO creature_questrelation (id, quest)
SELECT 2600210, q.entry FROM quest_template q
WHERE (q.RequiredClasses & 256) <> 0
  AND q.Title REGEXP 'Imp|Voidwalker|Succubus|Felhunter|Demon|Infernal|Summon';
INSERT IGNORE INTO creature_involvedrelation (id, quest)
SELECT 2600210, q.entry FROM quest_template q
WHERE (q.RequiredClasses & 256) <> 0
  AND q.Title REGEXP 'Imp|Voidwalker|Succubus|Felhunter|Demon|Infernal|Summon';

INSERT IGNORE INTO creature_questrelation (id, quest)
SELECT 2600209, q.entry FROM quest_template q
WHERE (q.RequiredClasses & 4) <> 0 AND q.Title REGEXP 'Pet|Beast|Taming|Tame';
INSERT IGNORE INTO creature_involvedrelation (id, quest)
SELECT 2600209, q.entry FROM quest_template q
WHERE (q.RequiredClasses & 4) <> 0 AND q.Title REGEXP 'Pet|Beast|Taming|Tame';

-- ---------------------------------------------------------------------------------------
-- 4c. Strip the profession RANK spells from every trainer we built.
--
--     Apprentice / Journeyman / Expert / Artisan Blacksmith and their 46 siblings are
--     useless on these NPCs: tuning-start-with-professions.sql grants every character the
--     ARTISAN rank of all 14 professions at creation, so clicking any of them just says
--     "you already know that". 50 dead entries cluttering the lists.
--
--     Identified by SPELL_EFFECT_SKILL_STEP (44) rather than by name, so it catches every
--     rank spell including Turtle's custom Survivalist ones, and does not depend on the
--     English wording.
--
--     Riding is unaffected - these NPCs never offered it, and it is still trained from the
--     real riding trainers at level 20 and 40.
-- ---------------------------------------------------------------------------------------
DELETE nt FROM npc_trainer nt
JOIN spell_template st ON st.entry = nt.spell
WHERE nt.entry BETWEEN 2600200 AND 2600399
  AND (st.effect1 = 44 OR st.effect2 = 44 OR st.effect3 = 44);

-- ---------------------------------------------------------------------------------------
-- 5. Quests: class by bitmask, profession by RequiredSkill.
--    Both questrelation (offer) and involvedrelation (turn-in), so they are completable
--    at the same NPC rather than sending you across the world.
-- ---------------------------------------------------------------------------------------
INSERT IGNORE INTO creature_questrelation (id, quest)
SELECT c.entry, q.entry FROM tmp_class c JOIN quest_template q
  ON (q.RequiredClasses & c.mask) <> 0;
INSERT IGNORE INTO creature_involvedrelation (id, quest)
SELECT c.entry, q.entry FROM tmp_class c JOIN quest_template q
  ON (q.RequiredClasses & c.mask) <> 0;

INSERT IGNORE INTO creature_questrelation (id, quest)
SELECT p.entry, q.entry FROM tmp_prof p JOIN quest_template q ON q.RequiredSkill = p.skill;
INSERT IGNORE INTO creature_involvedrelation (id, quest)
SELECT p.entry, q.entry FROM tmp_prof p JOIN quest_template q ON q.RequiredSkill = p.skill;

-- ---------------------------------------------------------------------------------------
-- 6. Profession vendor stock: the reagents that profession's own recipes call for,
--    limited to what vendors actually sell, and excluding anything gatherable - the same
--    rule as the Master Supplier, so herbalism/mining/skinning stay worth doing.
-- ---------------------------------------------------------------------------------------
DROP TEMPORARY TABLE IF EXISTS tmp_sold;
CREATE TEMPORARY TABLE tmp_sold (item MEDIUMINT UNSIGNED PRIMARY KEY) ENGINE=MEMORY;
INSERT IGNORE INTO tmp_sold SELECT item FROM npc_vendor;
INSERT IGNORE INTO tmp_sold SELECT item FROM npc_vendor_template;

DROP TEMPORARY TABLE IF EXISTS tmp_reagent;
CREATE TEMPORARY TABLE tmp_reagent (skill SMALLINT UNSIGNED, item MEDIUMINT UNSIGNED,
  PRIMARY KEY(skill,item)) ENGINE=MEMORY;
INSERT IGNORE INTO tmp_reagent
SELECT sla.skill_id, r.item FROM skill_line_ability sla
JOIN (SELECT entry, reagent1 AS item FROM spell_template WHERE reagent1>0
      UNION ALL SELECT entry, reagent2 FROM spell_template WHERE reagent2>0
      UNION ALL SELECT entry, reagent3 FROM spell_template WHERE reagent3>0
      UNION ALL SELECT entry, reagent4 FROM spell_template WHERE reagent4>0
      UNION ALL SELECT entry, reagent5 FROM spell_template WHERE reagent5>0
      UNION ALL SELECT entry, reagent6 FROM spell_template WHERE reagent6>0
      UNION ALL SELECT entry, reagent7 FROM spell_template WHERE reagent7>0
      UNION ALL SELECT entry, reagent8 FROM spell_template WHERE reagent8>0) r
  ON r.entry = sla.spell_id
JOIN tmp_sold s ON s.item = r.item
JOIN tmp_prof p ON p.skill = sla.skill_id
JOIN item_template ri ON ri.entry = r.item
WHERE NOT EXISTS (SELECT 1 FROM gameobject_loot_template g
                  WHERE g.item = r.item AND g.mincountOrRef > 0)
  -- Sanity filter on the reagent itself. Turtle's spell data contains genuine errors:
  -- spell 47009 "Cauldron of Major Shadow Protection" lists item 17578, the epic PvP
  -- helm Field Marshal's Coronal, as reagent1. Without this the Alchemy Master cheerfully
  -- sold it. A real crafting reagent is never equipment and never epic.
  AND ri.class NOT IN (2, 4)     -- no weapons, no armor
  AND ri.Quality <= 2;           -- no rare or better

SET @slot := 0;
INSERT IGNORE INTO npc_vendor (entry, slot, item, maxcount, incrtime, itemflags, condition_id)
SELECT x.entry, (@slot := @slot + 1), x.item, 0, 0, 0, 0 FROM
  (SELECT p.entry, r.item FROM tmp_prof p JOIN tmp_reagent r ON r.skill = p.skill
   ORDER BY p.entry, r.item) x;

-- ---------------------------------------------------------------------------------------
-- 6b. Profession bags.
--
--     bag_family is NOT the field to use here - in this database it is set only on
--     deprecated and test items ("Test Herb Bag", "Deprecated Big Quiver"). The real
--     profession bags are identified by class 1 (Container) SUBCLASS:
--        1 soul  2 herb  3 enchanting  4 engineering  6 mining  7 leather  8 rations
--        9 fishing
--     Quivers and ammo pouches are class 11, subclass 2 and 3.
--
--     Deprecated and unobtainable items are filtered out the same way as elsewhere:
--     flags 0x10 is ITEM_FLAG_DEPRECATED and extra_flags 0x04 is ITEM_EXTRA_NOT_OBTAINABLE.
-- ---------------------------------------------------------------------------------------
DROP TEMPORARY TABLE IF EXISTS tmp_bagmap;
CREATE TEMPORARY TABLE tmp_bagmap (skill SMALLINT UNSIGNED, cls TINYINT UNSIGNED,
  sub TINYINT UNSIGNED) ENGINE=MEMORY;
INSERT INTO tmp_bagmap VALUES
  (182,1,2),   -- Herbalism   -> herb bags
  (333,1,3),   -- Enchanting  -> enchanting bags
  (202,1,4),   -- Engineering -> engineering bags
  (186,1,6),   -- Mining      -> mining bags
  (393,1,7),   -- Skinning    -> leather bags
  (165,1,7),   -- Leatherworking too
  (185,1,8),   -- Cooking     -> rations bags
  (356,1,9);   -- Fishing     -> fishing bags

INSERT IGNORE INTO npc_vendor (entry, slot, item, maxcount, incrtime, itemflags, condition_id)
SELECT p.entry, 300 + it.entry MOD 90, it.entry, 0, 0, 0, 0
FROM tmp_prof p
JOIN tmp_bagmap b ON b.skill = p.skill
JOIN item_template it ON it.class = b.cls AND it.subclass = b.sub AND it.container_slots > 0
WHERE (it.flags & 16) = 0 AND (it.extra_flags & 4) = 0
  AND it.name NOT LIKE 'Deprecated%' AND it.name NOT LIKE 'Test %';

-- Quivers and ammo pouches onto the Hunter Master; soul bags onto the Demon Master.
INSERT IGNORE INTO npc_vendor (entry, slot, item, maxcount, incrtime, itemflags, condition_id)
SELECT 2600202, 300 + it.entry MOD 90, it.entry, 0, 0, 0, 0
FROM item_template it WHERE it.class = 11 AND it.subclass IN (2,3) AND it.container_slots > 0
  AND (it.flags & 16) = 0 AND (it.extra_flags & 4) = 0
  AND it.name NOT LIKE 'Deprecated%' AND it.name NOT LIKE 'Test %';

INSERT IGNORE INTO npc_vendor (entry, slot, item, maxcount, incrtime, itemflags, condition_id)
SELECT 2600210, 300 + it.entry MOD 90, it.entry, 0, 0, 0, 0
FROM item_template it WHERE it.class = 1 AND it.subclass = 1 AND it.container_slots > 0
  AND (it.flags & 16) = 0 AND (it.extra_flags & 4) = 0
  AND it.name NOT LIKE 'Deprecated%' AND it.name NOT LIKE 'D''Sak%';

-- ---------------------------------------------------------------------------------------
-- 6c. Vendor-sold recipes.
--
--     Only recipes some vendor ALREADY sells - deliberately not quest or drop recipes,
--     which should stay earned. Recipe class 9 subclass identifies the profession:
--        1 leatherworking  2 tailoring  3 engineering  4 blacksmithing  5 cooking
--        6 alchemy  7 first aid  8 enchanting  9 fishing  10 jewelcrafting
--     Subclass 0 is books - the warlock Grimoires - so those go to the Demon Master.
-- ---------------------------------------------------------------------------------------
DROP TEMPORARY TABLE IF EXISTS tmp_recmap;
CREATE TEMPORARY TABLE tmp_recmap (skill SMALLINT UNSIGNED, sub TINYINT UNSIGNED) ENGINE=MEMORY;
INSERT INTO tmp_recmap VALUES
  (165,1),(197,2),(202,3),(164,4),(185,5),(171,6),(129,7),(333,8),(356,9),(755,10);

INSERT IGNORE INTO npc_vendor (entry, slot, item, maxcount, incrtime, itemflags, condition_id)
SELECT p.entry, 400 + it.entry MOD 200, it.entry, 0, 0, 0, 0
FROM tmp_prof p
JOIN tmp_recmap m ON m.skill = p.skill
JOIN item_template it ON it.class = 9 AND it.subclass = m.sub
WHERE EXISTS (SELECT 1 FROM npc_vendor v WHERE v.item = it.entry
              AND v.entry NOT BETWEEN 2600200 AND 2600399)
  AND (it.flags & 16) = 0 AND (it.extra_flags & 4) = 0;

INSERT IGNORE INTO npc_vendor (entry, slot, item, maxcount, incrtime, itemflags, condition_id)
SELECT 2600210, 400 + it.entry MOD 200, it.entry, 0, 0, 0, 0
FROM item_template it WHERE it.class = 9 AND it.subclass = 0
  AND EXISTS (SELECT 1 FROM npc_vendor v WHERE v.item = it.entry
              AND v.entry NOT BETWEEN 2600200 AND 2600399)
  AND (it.flags & 16) = 0 AND (it.extra_flags & 4) = 0
  AND it.name LIKE 'Grimoire%';

-- Each profession master also carries the five tools, so one NPC covers a fresh start.
INSERT IGNORE INTO npc_vendor (entry, slot, item, maxcount, incrtime, itemflags, condition_id)
SELECT p.entry, 200 + t.n, t.item, 0, 0, 0, 0 FROM tmp_prof p
JOIN (SELECT 1 AS n, 2901 AS item UNION ALL SELECT 2, 5956 UNION ALL SELECT 3, 7005
      UNION ALL SELECT 4, 6256 UNION ALL SELECT 5, 6365) t;

-- ---------------------------------------------------------------------------------------
-- 7. Report.
-- ---------------------------------------------------------------------------------------
SELECT ct.entry, ct.name, ct.subname,
       (SELECT COUNT(*) FROM npc_trainer n WHERE n.entry=ct.entry) AS trains,
       (SELECT COUNT(*) FROM creature_questrelation q WHERE q.id=ct.entry) AS quests,
       (SELECT COUNT(*) FROM npc_vendor v WHERE v.entry=ct.entry) AS sells
FROM creature_template ct WHERE ct.entry BETWEEN 2600200 AND 2600399 ORDER BY ct.entry;

SELECT 'vendors over the 128 cap (want 0)' AS check_, COUNT(*) AS n FROM
  (SELECT entry FROM npc_vendor WHERE entry BETWEEN 2600200 AND 2600399
   GROUP BY entry HAVING COUNT(*) > 128) x;

-- ---------------------------------------------------------------------------------------
-- TO REMOVE: run the five DELETE statements from the top of this file on their own.
-- ---------------------------------------------------------------------------------------
