-- Dungeon portals. GENERATED by gen_dungeon_portals.py - do not edit by hand.
--
-- Read lazily by dungeon_portals.lua: ElunaLoader sorts by path, so
-- "dungeon_portal_targets" loads AFTER "dungeon_portals" and the global is not
-- there when that script's chunk first runs.

TerapinDungeonPortals = {
    {spell = 44300, name = "Shadowfang Keep", req = 10, map = 0, x = -229.49, y = 1576.35, z = 78.89},
    {spell = 44301, name = "Stormwind Stockade", req = 15, map = 0, x = -8761.85, y = 848.56, z = 87.81},
    {spell = 44302, name = "Stormwind Vault", req = 58, map = 0, x = -8667.56, y = 623.56, z = 85.41},
    {spell = 44303, name = "Deadmines", req = 10, map = 0, x = -11208.50, y = 1685.34, z = 25.76},
    {spell = 44304, name = "Wailing Caverns", req = 10, map = 1, x = -753.60, y = -2212.78, z = 21.54},
    {spell = 44305, name = "Razorfen Kraul", req = 15, map = 1, x = -4456.70, y = -1655.99, z = 86.11},
    {spell = 44306, name = "Blackfathom Deeps", req = 10, map = 1, x = 4252.37, y = 756.97, z = -23.06},
    {spell = 44307, name = "Uldaman", req = 30, map = 0, x = -6053.73, y = -2954.63, z = 213.69},
    {spell = 44308, name = "Gnomeregan", req = 15, map = 0, x = -5161.33, y = 939.62, z = 258.29},
    {spell = 44309, name = "Sunken Temple", req = 35, map = 0, x = -10162.70, y = -3998.65, z = -107.98},
    {spell = 44310, name = "Razorfen Downs", req = 25, map = 1, x = -4666.52, y = -2536.82, z = 86.97},
    {spell = 44311, name = "Scarlet Monastery", req = 20, map = 0, x = 2924.38, y = -798.43, z = 161.61},
    {spell = 44312, name = "Zul'Farrak", req = 35, map = 1, x = -6773.49, y = -2889.77, z = 15.11},
    {spell = 44313, name = "Blackrock Spire", req = 45, map = 0, x = -7518.19, y = -1239.13, z = 287.24},
    {spell = 44314, name = "Blackrock Depths", req = 40, map = 0, x = -7176.63, y = -937.67, z = 170.21},
    {spell = 44315, name = "Black Morass", req = 58, map = 1, x = -8799.19, y = -4115.16, z = -200.00},
    {spell = 44316, name = "Scholomance", req = 45, map = 0, x = 1282.05, y = -2548.73, z = 85.40},
    {spell = 44317, name = "Stratholme", req = 45, map = 0, x = 3237.46, y = -4060.60, z = 112.01},
    {spell = 44318, name = "Maraudon", req = 30, map = 1, x = -1484.07, y = 2617.57, z = 75.71},
    {spell = 44319, name = "Ragefire Chasm", req = 8, map = 1, x = 1818.40, y = -4427.26, z = -10.45},
    {spell = 44320, name = "Dire Maul", req = 45, map = 1, x = -3730.48, y = 933.97, z = 160.97},
    {spell = 44321, name = "Karazhan Crypt", req = 55, map = 0, x = -11068.30, y = -1811.69, z = 53.00},
    {spell = 44322, name = "Crescent Grove", req = 32, map = 1, x = 1689.78, y = -1272.15, z = 161.68},
    {spell = 44323, name = "Hateforge Quarry", req = 48, map = 0, x = -8173.00, y = -3114.57, z = 201.22},
    {spell = 44324, name = "Gilneas City", req = 40, map = 0, x = -1096.81, y = 2234.77, z = 182.86},
    {spell = 44325, name = "Dragonmaw Retreat", req = 25, map = 0, x = -3812.28, y = -3595.80, z = -45.95},
    {spell = 44326, name = "Stormwrought Ruins", req = 35, map = 0, x = -8823.10, y = 2903.17, z = 135.49},
    {spell = 44327, name = "Windhorn Canyon", req = 26, map = 1, x = -5117.52, y = -3534.29, z = 3.97},
    {spell = 44328, name = "Frostmane Hollow", req = 13, map = 0, x = -5020.44, y = -1449.43, z = 500.08},
}

-- Every meeting stone template. The use hook is keyed by gameobject ENTRY
-- (Eluna::OnGameObjectUse passes GetEntry() as the binding key), so each one must
-- be registered individually - a global handler would never fire.
TerapinMeetingStones = {178824, 178825, 178826, 178827, 178828, 178829, 178831, 178832, 178833, 178834, 178844, 178845, 178854, 178884, 179554, 179555, 179584, 179585, 179586, 179587, 179595, 179596, 179597, 179598, 179865, 179866, 379546, 379547, 379548, 1772020, 1772027, 1872030}
