-- GENERATED by TurtleMod/gen_scaling.py - do not edit by hand.
--
-- map id -> the level the dungeon requires to enter, read from
-- areatrigger_teleport.required_level. All 29 dungeons in this database carry one.
-- dungeon_scaling.lua adds TARGET_OFFSET (10) to get the level it scales you toward.

TERAPIN_DUNGEON_LEVELS = {
  [33] = 10,      -- Shadowfang Keep
  [34] = 15,      -- Stormwind Stockade
  [35] = 58,      -- Stormwind Vault
  [36] = 10,      -- Deadmines
  [43] = 61,      -- Wailing Caverns
  [47] = 15,      -- Razorfen Kraul
  [48] = 10,      -- Blackfathom Deeps
  [70] = 30,      -- Uldaman
  [90] = 15,      -- Gnomeregan
  [109] = 35,     -- Sunken Temple
  [129] = 25,     -- Razorfen Downs
  [189] = 20,     -- Scarlet Monastery
  [209] = 35,     -- Zul'Farrak
  [229] = 45,     -- Blackrock Spire
  [230] = 40,     -- Blackrock Depths
  [269] = 58,     -- Black Morass
  [289] = 45,     -- Scholomance
  [329] = 45,     -- Stratholme
  [349] = 30,     -- Maraudon
  [389] = 8,      -- Ragefire Chasm
  [429] = 45,     -- Dire Maul
  [800] = 55,     -- Karazhan Crypt
  [802] = 32,     -- Crescent Grove
  [808] = 48,     -- Hateforge Quarry
  [815] = 40,     -- Gilneas City
  [816] = 25,     -- Dragonmaw Retreat
  [818] = 35,     -- Stormwrought Ruins
  [820] = 26,     -- Windhorn Canyon
  [822] = 13,     -- Frostmane Hollow
}
