-- GENERATED by TurtleMod/gen_summons.py - do not edit by hand.
--
-- spell id -> creature entry. Which NPC each summon spawns; WHO may cast it is decided
-- by the grant in sql/23, not here.

TERAPIN_SUMMONS = {
  [38700] = 2600200,   -- Call Warrior Master
  [38701] = 2600201,   -- Call Paladin Master
  [38702] = 2600202,   -- Call Hunter Master
  [38703] = 2600203,   -- Call Rogue Master
  [38704] = 2600204,   -- Call Priest Master
  [38705] = 2600205,   -- Call Shaman Master
  [38706] = 2600206,   -- Call Mage Master
  [38707] = 2600207,   -- Call Warlock Master
  [38708] = 2600208,   -- Call Druid Master
  [38710] = 2600400,   -- Call Banker
  [38711] = 2600401,   -- Call Challenge Master
}
